import { useEffect, useMemo, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { api, errorMessage } from '../api';
import { money } from '../currency';
import { useLanguage } from '../i18n';
import OverlayPortal from '../components/OverlayPortal';
import HouseContextSwitcher from '../components/HouseContextSwitcher';
import type { ExpenseSummary, House, HouseMember, Receipt } from '../types';

type Lang='en'|'gu'|'hi'|'fr';
const copy:Record<Lang,any>={
 en:{title:'Shared expenses',sub:'Split grocery and household costs fairly, see who owes whom, and attach receipts when useful.',add:'Add expense',settle:'Record payment',balances:'Balances',history:'Expense history',suggest:'Suggested payments',paid:'paid',split:'Split between',equal:'Equal split',custom:'Custom amounts',payer:'Paid by',amount:'Amount',category:'Category',date:'Date',notes:'Notes',receipt:'Linked receipt',save:'Save expense',cancel:'Cancel',owes:'owes',gets:'gets back',settled:'All settled up',delete:'Delete',participants:'Participants',selectAll:'All members',from:'From',to:'To'},
 gu:{title:'સાંઝા ખર્ચ',sub:'કિરાણા અને ઘરખર્ચ ન્યાયથી વહેંચો, કોને કોને આપવાનું છે તે જુઓ અને જરૂર હોય ત્યારે રસીદ જોડો.',add:'ખર્ચ ઉમેરો',settle:'ચુકવણી નોંધો',balances:'બેલેન્સ',history:'ખર્ચ ઇતિહાસ',suggest:'સૂચવેલી ચુકવણીઓ',paid:'ચૂકવ્યું',split:'વહેંચો',equal:'સમાન વહેંચણી',custom:'કસ્ટમ રકમ',payer:'ચુકવનાર',amount:'રકમ',category:'શ્રેણી',date:'તારીખ',notes:'નોંધ',receipt:'જોડાયેલી રસીદ',save:'ખર્ચ સાચવો',cancel:'રદ કરો',owes:'આપવાના',gets:'મેળવવાના',settled:'બધું સેટલ છે',delete:'કાઢી નાખો',participants:'સભ્યો',selectAll:'બધા સભ્યો',from:'કોણે આપ્યું',to:'કોને આપ્યું'},
 hi:{title:'साझा खर्च',sub:'किराना और घर के खर्च को आसानी से बाँटें, देखें किसे किसको देना है, और जरूरत पर रसीद जोड़ें।',add:'खर्च जोड़ें',settle:'भुगतान दर्ज करें',balances:'बैलेंस',history:'खर्च इतिहास',suggest:'सुझाए गए भुगतान',paid:'ने भुगतान किया',split:'इनमें बाँटें',equal:'बराबर बाँटें',custom:'कस्टम राशि',payer:'भुगतान किसने किया',amount:'राशि',category:'श्रेणी',date:'तारीख',notes:'नोट्स',receipt:'जुड़ी रसीद',save:'खर्च सेव करें',cancel:'रद्द करें',owes:'देना है',gets:'पाना है',settled:'सबका हिसाब बराबर है',delete:'हटाएँ',participants:'सदस्य',selectAll:'सभी सदस्य',from:'किससे',to:'किसको'},
 fr:{title:'Dépenses partagées',sub:'Partagez les courses et dépenses du foyer, voyez qui doit quoi et joignez un reçu au besoin.',add:'Ajouter une dépense',settle:'Enregistrer un paiement',balances:'Soldes',history:'Historique',suggest:'Paiements suggérés',paid:'a payé',split:'Partager entre',equal:'Partage égal',custom:'Montants personnalisés',payer:'Payé par',amount:'Montant',category:'Catégorie',date:'Date',notes:'Notes',receipt:'Reçu lié',save:'Enregistrer',cancel:'Annuler',owes:'doit',gets:'doit recevoir',settled:'Tout est réglé',delete:'Supprimer',participants:'Participants',selectAll:'Tous les membres',from:'De',to:'À'}
};

export default function ExpensesPage(){
 const {houseId}=useParams(); const id=Number(houseId); const [params]=useSearchParams(); const {language}=useLanguage(); const c=copy[language as Lang]||copy.en;
 const [house,setHouse]=useState<House|null>(null); const [members,setMembers]=useState<HouseMember[]>([]); const [receipts,setReceipts]=useState<Receipt[]>([]); const [summary,setSummary]=useState<ExpenseSummary|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [open,setOpen]=useState(false); const [settleOpen,setSettleOpen]=useState(false);
 const [title,setTitle]=useState('Groceries'); const [amount,setAmount]=useState(''); const [payer,setPayer]=useState<number|''>(''); const [category,setCategory]=useState('Groceries'); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [notes,setNotes]=useState(''); const [receiptId,setReceiptId]=useState<number|''>(''); const [splitMode,setSplitMode]=useState<'equal'|'custom'>('equal'); const [participants,setParticipants]=useState<number[]>([]); const [shares,setShares]=useState<Record<number,string>>({});
 const [fromUser,setFromUser]=useState<number|''>(''); const [toUser,setToUser]=useState<number|''>(''); const [settleAmount,setSettleAmount]=useState('');
 async function load(){try{const [h,m,r,e]=await Promise.all([api.get<House>(`/houses/${id}`),api.get<HouseMember[]>(`/houses/${id}/members`),api.get<Receipt[]>(`/houses/${id}/receipts`),api.get<ExpenseSummary>(`/houses/${id}/expenses`)]);setHouse(h.data);setMembers(m.data);setReceipts(r.data);setSummary(e.data);setError(''); if(!payer&&m.data.length)setPayer(m.data[0].user_id); if(!participants.length)setParticipants(m.data.map(x=>x.user_id));}catch(err){setError(errorMessage(err));}}
 useEffect(()=>{load();},[id]);
 useEffect(()=>{const rid=Number(params.get('receiptId')||0); if(!rid||!receipts.length)return; const r=receipts.find(x=>x.id===rid); if(!r)return; setReceiptId(r.id);setTitle(`${r.store_name||'Grocery'} receipt`);if(r.total_amount!=null)setAmount(String(r.total_amount));if(r.receipt_date)setDate(r.receipt_date);setOpen(true);},[receipts,params]);
 const equalShares=useMemo(()=>{const n=participants.length||1; const total=Number(amount)||0; const each=Math.floor((total/n)*100)/100; let rem=Math.round(total*100)/100; const out:Record<number,number>={};participants.forEach((uid,i)=>{const v=i===participants.length-1?Math.round(rem*100)/100:each;out[uid]=v;rem-=v;});return out;},[participants,amount]);
 function reset(){setTitle('Groceries');setAmount('');setCategory('Groceries');setNotes('');setReceiptId('');setSplitMode('equal');setParticipants(members.map(x=>x.user_id));setShares({});}
 async function save(){const total=Number(amount); if(!title.trim()||!total||!payer||!participants.length){setError('Enter the expense, payer, and at least one participant.');return;} const split=participants.map(uid=>({user_id:uid,share_amount:splitMode==='equal'?(equalShares[uid]||0):Number(shares[uid]||0)})); try{setBusy(true);const {data}=await api.post<ExpenseSummary>(`/houses/${id}/expenses`,{title:title.trim(),amount:total,currency:'CAD',category,paid_by_user_id:payer,expense_date:date||null,notes:notes||null,receipt_id:receiptId||null,shares:split});setSummary(data);setOpen(false);reset();setError('');}catch(err){setError(errorMessage(err));}finally{setBusy(false)}}
 async function saveSettlement(){if(!fromUser||!toUser||fromUser===toUser||Number(settleAmount)<=0)return;try{setBusy(true);const {data}=await api.post<ExpenseSummary>(`/houses/${id}/expenses/settlements`,{from_user_id:fromUser,to_user_id:toUser,amount:Number(settleAmount),currency:'CAD'});setSummary(data);setSettleOpen(false);setSettleAmount('');}catch(err){setError(errorMessage(err));}finally{setBusy(false)}}
 async function remove(expenseId:number){if(!confirm('Delete this shared expense?'))return;const {data}=await api.delete<ExpenseSummary>(`/houses/${id}/expenses/${expenseId}`);setSummary(data)}
 return <main className="page shell wide expenses-page"><header className="page-hero creative-hero"><div><Link className="breadcrumb" to={`/houses/${id}`}>← {house?.name||'House'}</Link><p className="eyebrow">HOUSE MONEY</p><h1>💸 {c.title}</h1><p>{c.sub}</p></div><div className="hero-actions"><button onClick={()=>setOpen(true)}>{c.add}</button><button className="secondary" onClick={()=>setSettleOpen(true)}>{c.settle}</button></div></header><HouseContextSwitcher currentHouseId={id} currentHouseName={house?.name} section="expenses" />{error&&<div className="error">{error}</div>}
 <section className="expense-balance-grid">{(summary?.balances||[]).map(b=><article className={`panel expense-balance ${b.balance<-.009?'owes':b.balance>.009?'gets':'even'}`} key={b.user_id}><span>{b.user_name}</span><strong>{money(Math.abs(b.balance))}</strong><small>{b.balance<-.009?c.owes:b.balance>.009?c.gets:c.settled}</small></article>)}</section>
 <div className="expenses-layout"><section className="panel"><div className="panel-title-row"><div><p className="eyebrow">SMART SETTLE</p><h2>{c.suggest}</h2></div></div>{summary?.suggested_payments?.length?(summary.suggested_payments.map((x,i)=><button className="suggested-payment" key={i} onClick={()=>{setFromUser(x.from_user_id);setToUser(x.to_user_id);setSettleAmount(String(x.amount));setSettleOpen(true)}}><span><strong>{x.from_user_name}</strong> → <strong>{x.to_user_name}</strong></span><b>{money(x.amount)}</b></button>)):<div className="success compact-message">✓ {c.settled}</div>}</section>
 <section className="panel"><div className="panel-title-row"><h2>{c.history}</h2><button onClick={()=>setOpen(true)}>{c.add}</button></div><div className="expense-list">{(summary?.expenses||[]).map(x=><article className="expense-row" key={x.id}><div><strong>{x.title}</strong><small>{x.expense_date} · {x.category}{x.receipt_id?` · Receipt #${x.receipt_id}`:''}</small><span>{x.paid_by_name} {c.paid} · {x.shares.map(s=>`${s.user_name} ${money(s.share_amount)}`).join(' · ')}</span></div><div><b>{money(x.amount)}</b><button className="ghost tiny" onClick={()=>remove(x.id)}>{c.delete}</button></div></article>)}</div></section></div>
 {open&&<OverlayPortal><div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><section className="modal focus-dialog expense-modal" role="dialog" aria-modal="true" aria-label={c.add}><header className="focus-dialog-titlebar"><div><p className="eyebrow">SHARED COST</p><h2>{c.add}</h2></div><button data-dialog-close="true" className="icon-btn" onClick={()=>setOpen(false)}>×</button></header><div className="focus-dialog-scroll"><div className="form-grid two"><label>{c.amount}<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{c.payer}<select value={payer} onChange={e=>setPayer(Number(e.target.value))}>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||`Member ${m.user_id}`}</option>)}</select></label><label className="span-2">Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{c.category}<select value={category} onChange={e=>setCategory(e.target.value)}><option>Groceries</option><option>Household</option><option>Dining</option><option>Utilities</option><option>Other</option></select></label><label>{c.date}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="span-2">{c.receipt}<select value={receiptId} onChange={e=>setReceiptId(e.target.value?Number(e.target.value):'')}><option value="">No linked receipt</option>{receipts.map(r=><option key={r.id} value={r.id}>{r.store_name||'Receipt'} · {r.receipt_date||r.created_at.slice(0,10)} {r.total_amount!=null?`· ${money(r.total_amount)}`:''}</option>)}</select></label></div><div className="expense-split-box"><div className="panel-title-row"><h3>{c.split}</h3><div className="segmented"><button type="button" className={splitMode==='equal'?'active':''} onClick={()=>setSplitMode('equal')}>{c.equal}</button><button type="button" className={splitMode==='custom'?'active':''} onClick={()=>setSplitMode('custom')}>{c.custom}</button></div></div>{members.map(m=>{const on=participants.includes(m.user_id);return <div className="expense-member-split" key={m.user_id}><label className="inline-check"><input type="checkbox" checked={on} onChange={e=>setParticipants(curr=>e.target.checked?[...curr,m.user_id]:curr.filter(x=>x!==m.user_id))}/><span>{m.full_name||`Member ${m.user_id}`}</span></label>{on&&(splitMode==='equal'?<strong>{money(equalShares[m.user_id]||0)}</strong>:<input type="number" min="0" step="0.01" value={shares[m.user_id]||''} onChange={e=>setShares(v=>({...v,[m.user_id]:e.target.value}))}/>)}</div>})}</div><label>{c.notes}<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><footer className="focus-dialog-actions"><button className="secondary" onClick={()=>setOpen(false)}>{c.cancel}</button><button disabled={busy} onClick={save}>{c.save}</button></footer></section></div></OverlayPortal>}
 {settleOpen&&<OverlayPortal><div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSettleOpen(false)}}><section className="modal focus-dialog compact-dialog" role="dialog" aria-modal="true" aria-label={c.settle}><header className="focus-dialog-titlebar"><h2>{c.settle}</h2><button data-dialog-close="true" className="icon-btn" onClick={()=>setSettleOpen(false)}>×</button></header><div className="focus-dialog-scroll form-grid"><label>{c.from}<select value={fromUser} onChange={e=>setFromUser(Number(e.target.value))}><option value="">—</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name}</option>)}</select></label><label>{c.to}<select value={toUser} onChange={e=>setToUser(Number(e.target.value))}><option value="">—</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name}</option>)}</select></label><label>{c.amount}<input type="number" min="0.01" step="0.01" value={settleAmount} onChange={e=>setSettleAmount(e.target.value)}/></label></div><footer className="focus-dialog-actions"><button className="secondary" onClick={()=>setSettleOpen(false)}>{c.cancel}</button><button disabled={busy} onClick={saveSettlement}>{c.settle}</button></footer></section></div></OverlayPortal>}</main>
}
