import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../api';
import type { Product, ShoppingList } from '../types';
import { ingredientNames, recipes, type Diet, type MealKind, type Recipe, type RecipeIngredient } from '../recipes';
import { useLanguage } from '../i18n';

type Row=RecipeIngredient & {required:number; owned:number; shortage:number; matched?:Product; selected:boolean};
const copy={
 en:{title:'Meals & Recipes',sub:'Choose a dish, see what your house already has, and add only what is truly needed.',search:'Search dishes',proper:'Proper meal',light:'Light munching',breakfast:'Breakfast',dessert:'Dessert',drink:'Drinks',all:'All',servings:'Servings',ingredients:'Ingredients',inventory:'Inventory',required:'Required',shortage:'Need',enough:'Enough',addShort:'Add shortages',addAll:'Add full recipe',manual:'Add selected',custom:'Add your own dish',dish:'Dish name',addIngredient:'Add ingredient',saveCard:'Create dish card',canMake:'Can make now',almost:'Almost ready',missing:'Missing',browse:'Cook from what you own',noMatch:'No dishes match these filters.',added:'Added to grocery list',diet:'Diet',full:'Full recipe',short:'Shortage',remove:'Remove'},
 gu:{title:'ભોજન અને રેસીપી',sub:'વાનગી પસંદ કરો, ઘરમાં શું છે તે જુઓ અને ખરેખર જેટલું જોઈએ એટલું જ ખરીદીમાં ઉમેરો.',search:'વાનગી શોધો',proper:'પૂરું ભોજન',light:'હળવો નાસ્તો',breakfast:'નાસ્તો',dessert:'મીઠાઈ',drink:'પીણાં',all:'બધું',servings:'વ્યક્તિઓ',ingredients:'સામગ્રી',inventory:'ઇન્વેન્ટરી',required:'જરૂરી',shortage:'જોઈએ',enough:'પૂરતું છે',addShort:'ઓછી સામગ્રી ઉમેરો',addAll:'બધી સામગ્રી ઉમેરો',manual:'પસંદ કરેલ ઉમેરો',custom:'તમારી વાનગી ઉમેરો',dish:'વાનગીનું નામ',addIngredient:'સામગ્રી ઉમેરો',saveCard:'વાનગી કાર્ડ બનાવો',canMake:'હમણાં બનાવી શકો',almost:'લગભગ તૈયાર',missing:'ઓછું છે',browse:'ઘરમાંથી શું બનાવી શકો',noMatch:'આ ફિલ્ટરમાં કોઈ વાનગી મળી નથી.',added:'ખરીદી યાદીમાં ઉમેરાયું',diet:'પ્રકાર',full:'સંપૂર્ણ માત્રા',short:'ઓછી માત્રા',remove:'કાઢો'},
 hi:{title:'भोजन और रेसिपी',sub:'व्यंजन चुनें, घर में उपलब्ध मात्रा देखें और केवल जरूरत की कमी को खरीदारी सूची में जोड़ें।',search:'व्यंजन खोजें',proper:'पूरा भोजन',light:'हल्का नाश्ता',breakfast:'नाश्ता',dessert:'मिठाई',drink:'पेय',all:'सभी',servings:'लोग',ingredients:'सामग्री',inventory:'इन्वेंटरी',required:'आवश्यक',shortage:'चाहिए',enough:'पर्याप्त',addShort:'कमी जोड़ें',addAll:'पूरी रेसिपी जोड़ें',manual:'चुनी हुई जोड़ें',custom:'अपना व्यंजन जोड़ें',dish:'व्यंजन का नाम',addIngredient:'सामग्री जोड़ें',saveCard:'डिश कार्ड बनाएं',canMake:'अभी बना सकते हैं',almost:'लगभग तैयार',missing:'कमी',browse:'घर की सामग्री से बनाएं',noMatch:'कोई व्यंजन नहीं मिला।',added:'खरीदारी सूची में जोड़ा गया',diet:'प्रकार',full:'पूरी मात्रा',short:'कमी',remove:'हटाएं'},
 fr:{title:'Repas et recettes',sub:'Choisissez un plat, voyez le stock de la maison et ajoutez uniquement ce qui manque.',search:'Rechercher un plat',proper:'Repas complet',light:'Collation légère',breakfast:'Petit-déjeuner',dessert:'Dessert',drink:'Boissons',all:'Tous',servings:'Portions',ingredients:'Ingrédients',inventory:'Inventaire',required:'Requis',shortage:'Manque',enough:'Suffisant',addShort:'Ajouter les manques',addAll:'Ajouter toute la recette',manual:'Ajouter la sélection',custom:'Ajouter votre plat',dish:'Nom du plat',addIngredient:'Ajouter un ingrédient',saveCard:'Créer la fiche',canMake:'Prêt à cuisiner',almost:'Presque prêt',missing:'Manque',browse:'Cuisiner avec votre stock',noMatch:'Aucun plat ne correspond.',added:'Ajouté à la liste de courses',diet:'Régime',full:'Recette complète',short:'Manque',remove:'Retirer'}
};
const unitFactor=(u:string)=>(({kg:1000,g:1,l:1000,ml:1,pcs:1} as Record<string,number>)[u.toLowerCase()]||1);
function compatible(a:string,b:string){const A=a.toLowerCase(),B=b.toLowerCase(); return (['kg','g'].includes(A)&&['kg','g'].includes(B))||(['l','ml'].includes(A)&&['l','ml'].includes(B))||A===B;}
function normalizeQty(q:number,from:string,to:string){return compatible(from,to)?q*unitFactor(from)/unitFactor(to):0;}
function fmt(n:number){return Number.isInteger(n)?String(n):String(Math.round(n*100)/100);}
function slug(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
const aliases:Record<string,string[]>={
 'all purpose flour':['all purpose flour','plain flour','maida','મેંદો','मैदा'], 'whole wheat flour':['whole wheat flour','wheat flour','atta','ઘઉંનો લોટ','गेहूं का आटा'],
 'yogurt':['yogurt','yoghurt','curd','dahi','દહીં','दही'], 'potato':['potato','potatoes','bateta','બટાકા','आलू'], 'tomato':['tomato','tomatoes','tameta','ટમેટા','टमाटर'],
 'eggplant':['eggplant','aubergine','brinjal','ringan','રીંગણ','बैंगन'], 'besan':['besan','gram flour','chickpea flour','ચણાનો લોટ','बेसन']
};
function matchProduct(name:string, products:Product[]){const key=slug(name); const set=new Set([key,...(aliases[key]||[]).map(slug)]); return products.find(p=>{const pk=slug(p.name); return set.has(pk)||[...set].some(a=>pk.includes(a)||a.includes(pk));});}

export default function MealsPage(){
 const {houseId}=useParams(); const id=Number(houseId); const {language}=useLanguage(); const c=copy[language];
 const [products,setProducts]=useState<Product[]>([]); const [activeList,setActiveList]=useState<ShoppingList|null>(null); const [selected,setSelected]=useState<Recipe>(recipes[0]); const [servings,setServings]=useState(4); const [kind,setKind]=useState<'all'|MealKind>('all'); const [diet,setDiet]=useState<'all'|Diet>('all'); const [q,setQ]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false); const [manual,setManual]=useState<Record<string,boolean>>({}); const [qtyOverrides,setQtyOverrides]=useState<Record<string,number>>({});
 const [customName,setCustomName]=useState(''); const [customIngredients,setCustomIngredients]=useState<RecipeIngredient[]>([{name:'',qty:1,unit:'g'}]);
 const [customRecipes,setCustomRecipes]=useState<Recipe[]>(()=>{try{return JSON.parse(localStorage.getItem('ghm_custom_recipes')||'[]')}catch{return []}});
 const allRecipes=useMemo(()=>[...customRecipes,...recipes],[customRecipes]);
 useEffect(()=>{ if(!id)return; Promise.all([api.get<Product[]>(`/houses/${id}/products`,{params:{limit:500}}),api.get<ShoppingList|null>(`/houses/${id}/shopping-lists/active`)]).then(([p,l])=>{setProducts(p.data);setActiveList(l.data)}).catch(()=>{});},[id]);
 useEffect(()=>{setServings(selected.baseServings);setManual({});setQtyOverrides({});},[selected.id]);
 const rows=useMemo<Row[]>(()=>selected.ingredients.map(ing=>{const scaled=ing.qty*servings/selected.baseServings; const required=qtyOverrides[ing.name] ?? scaled; const matched=matchProduct(ing.name,products); const owned=matched&&compatible(matched.unit,ing.unit)?normalizeQty(matched.quantity,matched.unit,ing.unit):0; return {...ing,required,owned,shortage:Math.max(required-owned,0),matched,selected:false};}),[selected,servings,products,qtyOverrides]);
 const filtered=useMemo(()=>allRecipes.filter(r=>(kind==='all'||r.kind===kind)&&(diet==='all'||r.diets.includes(diet))&&(!q||Object.values(r.names).some(n=>n.toLowerCase().includes(q.toLowerCase())))),[kind,diet,q,allRecipes]);
 const availability=(r:Recipe)=>{const x=r.ingredients.filter(i=>!i.optional).map(i=>{const p=matchProduct(i.name,products); return !!p&&compatible(p.unit,i.unit)&&normalizeQty(p.quantity,p.unit,i.unit)>=i.qty;}); return x.length?x.filter(Boolean).length/x.length:0};
 async function add(mode:'shortage'|'full'|'manual'){
   const payload=rows.filter((r,i)=>mode==='full'||(mode==='shortage'&&r.shortage>0)||(mode==='manual'&&manual[String(i)])).map(r=>{
     const recipeQty=mode==='shortage'?r.shortage:r.required;
     const targetUnit=r.matched?.unit||r.unit;
     const targetQty=r.matched&&compatible(r.unit,targetUnit)?normalizeQty(recipeQty,r.unit,targetUnit):recipeQty;
     return {name:r.matched?.name||r.name,quantity:targetQty,unit:targetUnit,tag:`Recipe ${mode==='shortage'?'shortage':'requirement'} · ${selected.names.en} · ${fmt(recipeQty)} ${r.unit}`};
   }).filter(x=>x.quantity>0);
   if(!payload.length){setNotice(c.enough);return;} setBusy(true); setNotice('');
   try{const {data}=await api.post(`/insights/houses/${id}/recipes/add-shopping`,{ingredients:payload,list_id:activeList?.id||null,recipe_name:selected.names.en}); setNotice(`${c.added}: ${data.list_title}`); const l=await api.get<ShoppingList|null>(`/houses/${id}/shopping-lists/active`);setActiveList(l.data);}catch(e:any){setNotice(e?.response?.data?.detail||'Could not add ingredients.');}finally{setBusy(false)}
 }
 function createCustom(){if(!customName.trim())return; const cleaned=customIngredients.filter(x=>x.name.trim()&&x.qty>0); if(!cleaned.length)return; const custom:Recipe={id:`custom-${Date.now()}`,names:{en:customName,gu:customName,hi:customName,fr:customName},baseServings:4,kind:'proper',diets:['veg'],ingredients:cleaned,steps:{en:['Follow your preferred cooking method.'],gu:['તમારી પસંદની રીત પ્રમાણે બનાવો.'],hi:['अपनी पसंद की विधि से बनाएं।'],fr:['Suivez votre méthode de cuisson préférée.']}}; const next=[custom,...customRecipes]; setCustomRecipes(next); localStorage.setItem('ghm_custom_recipes',JSON.stringify(next)); setSelected(custom);setCustomName('');setNotice('');}
 const ingName=(n:string)=>ingredientNames[language]?.[n]||n;
 return <main className="page shell wide meals-page">
   <section className="meals-hero"><div><p className="eyebrow">SMART MEAL PLANNER</p><h1>{c.title}</h1><p>{c.sub}</p></div><div className="serving-box"><span>👥 {c.servings}</span><input type="number" min="1" max="100" value={servings} onChange={e=>setServings(Math.max(1,Number(e.target.value)||1))}/></div></section>
   <section className="panel meal-controls"><input placeholder={c.search} value={q} onChange={e=>setQ(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value as any)}><option value="all">{c.all}</option><option value="proper">{c.proper}</option><option value="light">{c.light}</option><option value="breakfast">{c.breakfast}</option><option value="dessert">{c.dessert}</option><option value="drink">{c.drink}</option></select><select value={diet} onChange={e=>setDiet(e.target.value as any)}><option value="all">{c.diet}: {c.all}</option><option value="jain">Jain</option><option value="swaminarayan">Swaminarayan (no onion/garlic)</option><option value="veg">Veg</option><option value="vegan">Vegan</option><option value="nonveg">Non-veg</option></select></section>
   <div className="meals-layout"><aside className="meal-library panel"><h2>{c.browse}</h2>{filtered.map(r=>{const a=availability(r);return <button className={`meal-tile ${selected.id===r.id?'active':''}`} key={r.id} onClick={()=>setSelected(r)}><span><strong>{r.names[language]}</strong><small>{r.kind} · {r.diets.join(' / ')}</small></span><em className={a===1?'ready':a>.5?'almost':'missing'}>{a===1?'✓ '+c.canMake:a>.5?'◐ '+c.almost:`${Math.round(a*100)}%`}</em></button>})}{!filtered.length&&<p>{c.noMatch}</p>}</aside>
   <section className="recipe-card panel"><div className="recipe-card-head"><div><p className="eyebrow">{selected.kind.toUpperCase()}</p><h2>{selected.names[language]}</h2><div className="diet-chips">{selected.diets.map(d=><span key={d}>{d==='swaminarayan'?'No onion / garlic':d}</span>)}</div></div><div className="recipe-ready-score"><strong>{Math.round(availability(selected)*100)}%</strong><small>{c.inventory}</small></div></div>
    <div className="ingredient-table"><div className="ingredient-row head"><span></span><span>{c.ingredients}</span><span>{c.required}</span><span>{c.inventory}</span><span>{c.shortage}</span></div>{rows.map((row,i)=><div className={`ingredient-row ${row.shortage<=0?'covered':'needed'}`} key={row.name}><span><input type="checkbox" checked={!!manual[String(i)]} onChange={e=>setManual(m=>({...m,[String(i)]:e.target.checked}))}/></span><span><b>{ingName(row.name)}</b>{row.optional&&<small>optional</small>}</span><span className="required-edit"><input type="number" min="0" step="0.01" value={row.required} onChange={e=>setQtyOverrides(o=>({...o,[row.name]:Math.max(0,Number(e.target.value)||0)}))}/><small>{row.unit}</small></span><span>{row.matched?`${fmt(row.owned)} ${row.unit}`:'0 '+row.unit}</span><span>{row.shortage>0?<mark>+ {fmt(row.shortage)} {row.unit}</mark>:<em>✓ {c.enough}</em>}</span></div>)}</div>
    <div className="recipe-actions"><button disabled={busy} onClick={()=>add('shortage')}>🛒 {c.addShort}</button><button className="secondary" disabled={busy} onClick={()=>add('manual')}>☑ {c.manual}</button><button className="ghost" disabled={busy} onClick={()=>add('full')}>＋ {c.addAll}</button></div>{notice&&<div className="meal-notice">{notice}</div>}
    <div className="recipe-steps"><h3>Recipe</h3>{selected.steps[language].map((s,i)=><p key={i}><b>{i+1}.</b> {s}</p>)}</div>
   </section></div>
   <section className="panel custom-dish"><div><p className="eyebrow">CUSTOM RECIPE</p><h2>{c.custom}</h2><p>Create a private dish card, set its base recipe for 4 people, then scale it to any serving count.</p></div><input placeholder={c.dish} value={customName} onChange={e=>setCustomName(e.target.value)}/>{customIngredients.map((x,i)=><div className="custom-ing-row" key={i}><input placeholder={c.ingredients} value={x.name} onChange={e=>setCustomIngredients(a=>a.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/><input type="number" min="0.01" step="0.01" value={x.qty} onChange={e=>setCustomIngredients(a=>a.map((v,j)=>j===i?{...v,qty:Number(e.target.value)}:v))}/><select value={x.unit} onChange={e=>setCustomIngredients(a=>a.map((v,j)=>j===i?{...v,unit:e.target.value}:v))}><option>g</option><option>kg</option><option>ml</option><option>l</option><option>pcs</option></select><button className="icon-btn" onClick={()=>setCustomIngredients(a=>a.filter((_,j)=>j!==i))}>×</button></div>)}<div className="custom-actions"><button className="secondary" onClick={()=>setCustomIngredients(a=>[...a,{name:'',qty:1,unit:'g'}])}>＋ {c.addIngredient}</button><button onClick={createCustom}>{c.saveCard}</button></div></section>
 </main>;
}
