export type SiteLanguage = 'en' | 'gu' | 'hi' | 'fr';

type L = { gu: string; hi: string; fr: string };

// Exact UI phrases used across the legacy pages. This lets v76 localize old screens without
// forcing every page to be rewritten at once, while keeping user-entered values untouched.
const exact: Record<string, L> = {
  'Home': {gu:'હોમ',hi:'होम',fr:'Accueil'},
  'Inventory': {gu:'ઇન્વેન્ટરી',hi:'इन्वेंटरी',fr:'Inventaire'},
  'Shopping': {gu:'ખરીદી',hi:'खरीदारी',fr:'Courses'},
  'Meals': {gu:'ભોજન',hi:'भोजन',fr:'Repas'},
  'Meals & Recipes': {gu:'ભોજન અને રેસીપી',hi:'भोजन और रेसिपी',fr:'Repas et recettes'},
  'Assistant': {gu:'સહાયક',hi:'सहायक',fr:'Assistant'},
  'Prices': {gu:'ભાવ',hi:'कीमतें',fr:'Prix'},
  'Reports': {gu:'રિપોર્ટ્સ',hi:'रिपोर्ट',fr:'Rapports'},
  'Plans': {gu:'પ્લાન્સ',hi:'प्लान',fr:'Forfaits'},
  'Profile': {gu:'પ્રોફાઇલ',hi:'प्रोफ़ाइल',fr:'Profil'},
  'Support': {gu:'મદદ',hi:'सहायता',fr:'Assistance'},
  'Admin': {gu:'એડમિન',hi:'एडमिन',fr:'Admin'},
  'More': {gu:'વધુ',hi:'अधिक',fr:'Plus'},
  'About': {gu:'વિશે',hi:'परिचय',fr:'À propos'},
  'Privacy': {gu:'ગોપનીયતા',hi:'गोपनीयता',fr:'Confidentialité'},
  'Terms': {gu:'શરતો',hi:'शर्तें',fr:'Conditions'},
  'Refunds': {gu:'રિફંડ',hi:'रिफंड',fr:'Remboursements'},
  'Language': {gu:'ભાષા',hi:'भाषा',fr:'Langue'},
  'English': {gu:'અંગ્રેજી',hi:'अंग्रेज़ी',fr:'Anglais'},
  'Gujarati': {gu:'ગુજરાતી',hi:'गुजराती',fr:'Gujarati'},
  'Hindi': {gu:'હિન્દી',hi:'हिन्दी',fr:'Hindi'},
  'French': {gu:'ફ્રેન્ચ',hi:'फ़्रेंच',fr:'Français'},
  'Create': {gu:'બનાવો',hi:'बनाएं',fr:'Créer'},
  'Add': {gu:'ઉમેરો',hi:'जोड़ें',fr:'Ajouter'},
  'Save': {gu:'સાચવો',hi:'सहेजें',fr:'Enregistrer'},
  'Cancel': {gu:'રદ કરો',hi:'रद्द करें',fr:'Annuler'},
  'Delete': {gu:'કાઢી નાખો',hi:'हटाएं',fr:'Supprimer'},
  'Remove': {gu:'કાઢો',hi:'हटाएं',fr:'Retirer'},
  'Edit': {gu:'ફેરફાર',hi:'संपादित करें',fr:'Modifier'},
  'Refresh': {gu:'રિફ્રેશ',hi:'रीफ़्रेश',fr:'Actualiser'},
  'Search': {gu:'શોધો',hi:'खोजें',fr:'Rechercher'},
  'Clear': {gu:'સાફ કરો',hi:'साफ़ करें',fr:'Effacer'},
  'Open': {gu:'ખોલો',hi:'खोलें',fr:'Ouvrir'},
  'View': {gu:'જુઓ',hi:'देखें',fr:'Voir'},
  'Close': {gu:'બંધ કરો',hi:'बंद करें',fr:'Fermer'},
  'Next': {gu:'આગળ',hi:'आगे',fr:'Suivant'},
  'Back': {gu:'પાછળ',hi:'वापस',fr:'Retour'},
  'Continue': {gu:'ચાલુ રાખો',hi:'जारी रखें',fr:'Continuer'},
  'Loading…': {gu:'લોડ થઈ રહ્યું છે…',hi:'लोड हो रहा है…',fr:'Chargement…'},
  'Loading...': {gu:'લોડ થઈ રહ્યું છે...',hi:'लोड हो रहा है...',fr:'Chargement...'},
  'Name': {gu:'નામ',hi:'नाम',fr:'Nom'},
  'Email': {gu:'ઇમેઇલ',hi:'ईमेल',fr:'E-mail'},
  'Password': {gu:'પાસવર્ડ',hi:'पासवर्ड',fr:'Mot de passe'},
  'City': {gu:'શહેર',hi:'शहर',fr:'Ville'},
  'Country': {gu:'દેશ',hi:'देश',fr:'Pays'},
  'Address': {gu:'સરનામું',hi:'पता',fr:'Adresse'},
  'Status': {gu:'સ્થિતિ',hi:'स्थिति',fr:'Statut'},
  'Plan': {gu:'પ્લાન',hi:'प्लान',fr:'Forfait'},
  'Current plan': {gu:'હાલનો પ્લાન',hi:'वर्तमान प्लान',fr:'Forfait actuel'},
  'Quantity': {gu:'માત્રા',hi:'मात्रा',fr:'Quantité'},
  'Unit': {gu:'એકમ',hi:'इकाई',fr:'Unité'},
  'Price': {gu:'ભાવ',hi:'कीमत',fr:'Prix'},
  'Unit price': {gu:'એકમ ભાવ',hi:'इकाई कीमत',fr:'Prix unitaire'},
  'Store': {gu:'સ્ટોર',hi:'स्टोर',fr:'Magasin'},
  'Store name': {gu:'સ્ટોરનું નામ',hi:'स्टोर का नाम',fr:'Nom du magasin'},
  'Product': {gu:'પ્રોડક્ટ',hi:'उत्पाद',fr:'Produit'},
  'Products': {gu:'પ્રોડક્ટ્સ',hi:'उत्पाद',fr:'Produits'},
  'Product name': {gu:'પ્રોડક્ટનું નામ',hi:'उत्पाद का नाम',fr:'Nom du produit'},
  'Brand': {gu:'બ્રાન્ડ',hi:'ब्रांड',fr:'Marque'},
  'Category': {gu:'કેટેગરી',hi:'श्रेणी',fr:'Catégorie'},
  'Notes': {gu:'નોંધ',hi:'नोट्स',fr:'Notes'},
  'Date': {gu:'તારીખ',hi:'तारीख',fr:'Date'},
  'Subtotal': {gu:'ઉપકુલ',hi:'उप-योग',fr:'Sous-total'},
  'Tax': {gu:'ટેક્સ',hi:'कर',fr:'Taxe'},
  'Total': {gu:'કુલ',hi:'कुल',fr:'Total'},
  'Discount': {gu:'ડિસ્કાઉન્ટ',hi:'छूट',fr:'Remise'},
  'Payment': {gu:'ચુકવણી',hi:'भुगतान',fr:'Paiement'},
  'Members': {gu:'સભ્યો',hi:'सदस्य',fr:'Membres'},
  'Owner': {gu:'માલિક',hi:'मालिक',fr:'Propriétaire'},
  'House': {gu:'ઘર',hi:'घर',fr:'Maison'},
  'Your Home': {gu:'તમારું ઘર',hi:'आपका घर',fr:'Votre maison'},
  'Your Grocery Home': {gu:'તમારું ગ્રોસરી ઘર',hi:'आपका ग्रोसरी होम',fr:'Votre maison d’épicerie'},
  'Switch Grocery Home': {gu:'ગ્રોસરી ઘર બદલો',hi:'ग्रोसरी होम बदलें',fr:'Changer de maison'},
  'Manage Homes': {gu:'ઘરો મેનેજ કરો',hi:'होम प्रबंधित करें',fr:'Gérer les maisons'},
  'Create a House': {gu:'ઘર બનાવો',hi:'घर बनाएं',fr:'Créer une maison'},
  'Create a Grocery Home': {gu:'ગ્રોસરી ઘર બનાવો',hi:'ग्रोसरी होम बनाएं',fr:'Créer une maison d’épicerie'},
  'Create your first Grocery Home': {gu:'તમારું પહેલું ગ્રોસરી ઘર બનાવો',hi:'अपना पहला ग्रोसरी होम बनाएं',fr:'Créez votre première maison d’épicerie'},
  'Delete house': {gu:'ઘર કાઢી નાખો',hi:'घर हटाएं',fr:'Supprimer la maison'},
  'Leave house': {gu:'ઘર છોડો',hi:'घर छोड़ें',fr:'Quitter la maison'},
  'House members': {gu:'ઘરના સભ્યો',hi:'घर के सदस्य',fr:'Membres de la maison'},
  'House activity': {gu:'ઘરની પ્રવૃત્તિ',hi:'घर की गतिविधि',fr:'Activité de la maison'},
  'Recent activity': {gu:'તાજેતરની પ્રવૃત્તિ',hi:'हाल की गतिविधि',fr:'Activité récente'},
  'All recent updates': {gu:'બધા તાજેતરના અપડેટ',hi:'सभी हालिया अपडेट',fr:'Toutes les mises à jour récentes'},
  'Copy invite link': {gu:'આમંત્રણ લિંક કૉપી કરો',hi:'आमंत्रण लिंक कॉपी करें',fr:'Copier le lien d’invitation'},
  'Inventory sections': {gu:'ઇન્વેન્ટરી વિભાગો',hi:'इन्वेंटरी सेक्शन',fr:'Sections d’inventaire'},
  'All sections': {gu:'બધા વિભાગો',hi:'सभी सेक्शन',fr:'Toutes les sections'},
  'Add section': {gu:'વિભાગ ઉમેરો',hi:'सेक्शन जोड़ें',fr:'Ajouter une section'},
  'Add product': {gu:'પ્રોડક્ટ ઉમેરો',hi:'उत्पाद जोड़ें',fr:'Ajouter un produit'},
  '+ Add product': {gu:'+ પ્રોડક્ટ ઉમેરો',hi:'+ उत्पाद जोड़ें',fr:'+ Ajouter un produit'},
  'Add first grocery': {gu:'પહેલી ગ્રોસરી ઉમેરો',hi:'पहला किराना जोड़ें',fr:'Ajouter le premier article'},
  'Add your first grocery': {gu:'તમારી પહેલી ગ્રોસરી ઉમેરો',hi:'अपना पहला किराना जोड़ें',fr:'Ajoutez votre premier article'},
  'Your grocery inventory': {gu:'તમારી ગ્રોસરી ઇન્વેન્ટરી',hi:'आपकी ग्रोसरी इन्वेंटरी',fr:'Votre inventaire d’épicerie'},
  'What’s at home': {gu:'ઘરમાં શું છે',hi:'घर में क्या है',fr:'Ce qu’il y a à la maison'},
  'Low stock': {gu:'ઓછો સ્ટોક',hi:'कम स्टॉक',fr:'Stock faible'},
  'Out of stock': {gu:'સ્ટોક ખતમ',hi:'स्टॉक समाप्त',fr:'Rupture de stock'},
  'Expired': {gu:'સમાપ્ત',hi:'समाप्त',fr:'Expiré'},
  'Expiring soon': {gu:'જલ્દી સમાપ્ત થશે',hi:'जल्द समाप्त',fr:'Expire bientôt'},
  'Expiry date': {gu:'સમાપ્તિ તારીખ',hi:'समाप्ति तिथि',fr:'Date d’expiration'},
  'Visible products': {gu:'દેખાતા પ્રોડક્ટ્સ',hi:'दिखाई देने वाले उत्पाद',fr:'Produits visibles'},
  'Quick start': {gu:'ઝડપી શરૂઆત',hi:'त्वरित शुरुआत',fr:'Démarrage rapide'},
  'Start with what you already have': {gu:'ઘરમાં જે છે ત્યાંથી શરૂ કરો',hi:'जो पहले से घर में है उससे शुरू करें',fr:'Commencez avec ce que vous avez déjà'},
  'Grocery list': {gu:'ગ્રોસરી યાદી',hi:'ग्रोसरी सूची',fr:'Liste de courses'},
  'Grocery lists': {gu:'ગ્રોસરી યાદીઓ',hi:'ग्रोसरी सूचियाँ',fr:'Listes de courses'},
  'Active shopping lists': {gu:'સક્રિય ખરીદી યાદીઓ',hi:'सक्रिय खरीदारी सूचियाँ',fr:'Listes de courses actives'},
  'New grocery list': {gu:'નવી ગ્રોસરી યાદી',hi:'नई ग्रोसरी सूची',fr:'Nouvelle liste de courses'},
  'Create grocery list': {gu:'ગ્રોસરી યાદી બનાવો',hi:'ग्रोसरी सूची बनाएं',fr:'Créer une liste de courses'},
  'Add selected products': {gu:'પસંદ કરેલા પ્રોડક્ટ્સ ઉમેરો',hi:'चुने हुए उत्पाद जोड़ें',fr:'Ajouter les produits sélectionnés'},
  'Add more products': {gu:'વધુ પ્રોડક્ટ્સ ઉમેરો',hi:'और उत्पाद जोड़ें',fr:'Ajouter d’autres produits'},
  'Added in cart': {gu:'કાર્ટમાં ઉમેર્યું',hi:'कार्ट में जोड़ा',fr:'Ajouté au panier'},
  'In cart': {gu:'કાર્ટમાં',hi:'कार्ट में',fr:'Dans le panier'},
  'Bought': {gu:'ખરીદ્યું',hi:'खरीदा',fr:'Acheté'},
  'Need': {gu:'જરૂર',hi:'चाहिए',fr:'Besoin'},
  'Shopping done': {gu:'ખરીદી પૂર્ણ',hi:'खरीदारी पूरी',fr:'Courses terminées'},
  'Shopping complete': {gu:'ખરીદી પૂર્ણ',hi:'खरीदारी पूरी',fr:'Courses terminées'},
  'Shopping flow': {gu:'ખરીદી પ્રક્રિયા',hi:'खरीदारी प्रक्रिया',fr:'Parcours d’achat'},
  'Cancel list': {gu:'યાદી રદ કરો',hi:'सूची रद्द करें',fr:'Annuler la liste'},
  'Scan receipt': {gu:'રસીદ સ્કેન કરો',hi:'रसीद स्कैन करें',fr:'Scanner un reçu'},
  'Receipt history': {gu:'રસીદ ઇતિહાસ',hi:'रसीद इतिहास',fr:'Historique des reçus'},
  'Saved receipts': {gu:'સાચવેલી રસીદો',hi:'सहेजी गई रसीदें',fr:'Reçus enregistrés'},
  'Saved receipt': {gu:'સાચવેલી રસીદ',hi:'सहेजी गई रसीद',fr:'Reçu enregistré'},
  'Smart Receipt Studio': {gu:'સ્માર્ટ રસીદ સ્ટુડિયો',hi:'स्मार्ट रसीद स्टूडियो',fr:'Studio de reçus intelligent'},
  'Smart receipt studio': {gu:'સ્માર્ટ રસીદ સ્ટુડિયો',hi:'स्मार्ट रसीद स्टूडियो',fr:'Studio de reçus intelligent'},
  'Review before saving': {gu:'સાચવતા પહેલાં તપાસો',hi:'सहेजने से पहले जाँचें',fr:'Vérifier avant d’enregistrer'},
  'Review required': {gu:'તપાસ જરૂરી',hi:'समीक्षा आवश्यक',fr:'Vérification requise'},
  'Upload receipt': {gu:'રસીદ અપલોડ કરો',hi:'रसीद अपलोड करें',fr:'Téléverser le reçu'},
  'Attach receipt photo (JPG or PNG only)': {gu:'રસીદનો ફોટો જોડો (ફક્ત JPG અથવા PNG)',hi:'रसीद की फोटो जोड़ें (केवल JPG या PNG)',fr:'Joindre la photo du reçu (JPG ou PNG uniquement)'},
  'Save trusted prices': {gu:'વિશ્વસનીય ભાવ સાચવો',hi:'विश्वसनीय कीमतें सहेजें',fr:'Enregistrer les prix vérifiés'},
  'Manual price entry': {gu:'ભાવ હાથેથી દાખલ કરો',hi:'कीमत मैन्युअल दर्ज करें',fr:'Saisie manuelle du prix'},
  'Weekly flyers near your Grocery Home': {gu:'તમારા ગ્રોસરી ઘર નજીકના સાપ્તાહિક ફ્લાયર્સ',hi:'आपके ग्रोसरी होम के पास साप्ताहिक फ्लायर',fr:'Circulaires hebdomadaires près de votre maison'},
  'Weekly flyers': {gu:'સાપ્તાહિક ફ્લાયર્સ',hi:'साप्ताहिक फ्लायर',fr:'Circulaires hebdomadaires'},
  'Find an item in this week’s flyers': {gu:'આ અઠવાડિયાના ફ્લાયરમાં વસ્તુ શોધો',hi:'इस सप्ताह के फ्लायर में वस्तु खोजें',fr:'Rechercher un article dans les circulaires de la semaine'},
  'Find weekly deals': {gu:'સાપ્તાહિક ડીલ શોધો',hi:'साप्ताहिक ऑफ़र खोजें',fr:'Trouver les offres de la semaine'},
  'Refresh flyer data': {gu:'ફ્લાયર ડેટા રિફ્રેશ કરો',hi:'फ्लायर डेटा रीफ़्रेश करें',fr:'Actualiser les circulaires'},
  'Cached local flyers': {gu:'કૅશ કરેલા સ્થાનિક ફ્લાયર્સ',hi:'कैश किए गए स्थानीय फ्लायर',fr:'Circulaires locales en cache'},
  'Fresh local flyers': {gu:'નવા સ્થાનિક ફ્લાયર્સ',hi:'ताज़ा स्थानीय फ्लायर',fr:'Circulaires locales récentes'},
  'Bundle offer': {gu:'બંડલ ઓફર',hi:'बंडल ऑफ़र',fr:'Offre groupée'},
  'Price drop': {gu:'ભાવ ઘટાડો',hi:'कीमत घटी',fr:'Baisse de prix'},
  'Current flyer': {gu:'હાલનો ફ્લાયર',hi:'वर्तमान फ्लायर',fr:'Circulaire actuelle'},
  'Full flyer': {gu:'સંપૂર્ણ ફ્લાયર',hi:'पूरा फ्लायर',fr:'Circulaire complète'},
  'All flyer deals': {gu:'બધી ફ્લાયર ડીલ',hi:'सभी फ्लायर ऑफ़र',fr:'Toutes les offres des circulaires'},
  'Show all deals': {gu:'બધી ડીલ બતાવો',hi:'सभी ऑफ़र दिखाएं',fr:'Afficher toutes les offres'},
  'Show fewer': {gu:'ઓછું બતાવો',hi:'कम दिखाएं',fr:'Afficher moins'},
  'Flyer deal for your list': {gu:'તમારી યાદી માટે ફ્લાયર ડીલ',hi:'आपकी सूची के लिए फ्लायर ऑफ़र',fr:'Offre de circulaire pour votre liste'},
  'Valid until': {gu:'આ તારીખ સુધી માન્ય',hi:'इस तारीख तक मान्य',fr:'Valide jusqu’au'},
  'Valid': {gu:'માન્ય',hi:'मान्य',fr:'Valide'},
  'Updated': {gu:'અપડેટ',hi:'अपडेट',fr:'Mis à jour'},
  'Source': {gu:'સ્ત્રોત',hi:'स्रोत',fr:'Source'},
  'Find products and compare grocery prices': {gu:'પ્રોડક્ટ શોધો અને ગ્રોસરી ભાવ સરખાવો',hi:'उत्पाद खोजें और ग्रोसरी कीमतें तुलना करें',fr:'Trouver des produits et comparer les prix'},
  'Canadian price comparison': {gu:'કેનેડિયન ભાવ સરખામણી',hi:'कनाडाई कीमत तुलना',fr:'Comparaison des prix canadiens'},
  'Product lookup': {gu:'પ્રોડક્ટ શોધ',hi:'उत्पाद खोज',fr:'Recherche de produit'},
  'Product lookup + add to inventory': {gu:'પ્રોડક્ટ શોધ + ઇન્વેન્ટરીમાં ઉમેરો',hi:'उत्पाद खोज + इन्वेंटरी में जोड़ें',fr:'Recherche produit + ajout à l’inventaire'},
  'Add to inventory': {gu:'ઇન્વેન્ટરીમાં ઉમેરો',hi:'इन्वेंटरी में जोड़ें',fr:'Ajouter à l’inventaire'},
  'Open store': {gu:'સ્ટોર ખોલો',hi:'स्टोर खोलें',fr:'Ouvrir le magasin'},
  'Canadian postal code': {gu:'કેનેડિયન પોસ્ટલ કોડ',hi:'कनाडाई पोस्टल कोड',fr:'Code postal canadien'},
  'Postal code': {gu:'પોસ્ટલ કોડ',hi:'पोस्टल कोड',fr:'Code postal'},
  'Store name optional': {gu:'સ્ટોરનું નામ વૈકલ્પિક',hi:'स्टोर का नाम वैकल्पिक',fr:'Nom du magasin facultatif'},
  'Items, one per line': {gu:'વસ્તુઓ, દરેક લાઇનમાં એક',hi:'वस्तुएँ, हर पंक्ति में एक',fr:'Articles, un par ligne'},
  'Confidence': {gu:'વિશ્વાસ સ્તર',hi:'विश्वसनीयता',fr:'Confiance'},
  'Matched product': {gu:'મેચ થયેલ પ્રોડક્ટ',hi:'मिला हुआ उत्पाद',fr:'Produit correspondant'},
  'Best store': {gu:'શ્રેષ્ઠ સ્ટોર',hi:'सबसे अच्छा स्टोर',fr:'Meilleur magasin'},
  'Best price': {gu:'શ્રેષ્ઠ ભાવ',hi:'सबसे अच्छी कीमत',fr:'Meilleur prix'},
  'Best known store': {gu:'જાણીતો શ્રેષ્ઠ સ્ટોર',hi:'ज्ञात सबसे अच्छा स्टोर',fr:'Meilleur magasin connu'},
  'Best known prices by product': {gu:'પ્રોડક્ટ મુજબ શ્રેષ્ઠ જાણીતા ભાવ',hi:'उत्पाद के अनुसार ज्ञात सर्वोत्तम कीमतें',fr:'Meilleurs prix connus par produit'},
  'Family Plus': {gu:'ફેમિલી પ્લસ',hi:'फैमिली प्लस',fr:'Family Plus'},
  'Household Pro': {gu:'હાઉસહોલ્ડ પ્રો',hi:'हाउसहोल्ड प्रो',fr:'Household Pro'},
  'Basic Home': {gu:'બેસિક હોમ',hi:'बेसिक होम',fr:'Basic Home'},
  'Free Starter': {gu:'ફ્રી સ્ટાર્ટર',hi:'फ्री स्टार्टर',fr:'Free Starter'},
  'Subscription plans': {gu:'સબ્સ્ક્રિપ્શન પ્લાન્સ',hi:'सब्सक्रिप्शन प्लान',fr:'Forfaits d’abonnement'},
  'Monthly': {gu:'માસિક',hi:'मासिक',fr:'Mensuel'},
  'Annual': {gu:'વાર્ષિક',hi:'वार्षिक',fr:'Annuel'},
  'Manage billing': {gu:'બિલિંગ મેનેજ કરો',hi:'बिलिंग प्रबंधित करें',fr:'Gérer la facturation'},
  'Apply coupon code': {gu:'કૂપન કોડ લાગુ કરો',hi:'कूपन कोड लागू करें',fr:'Appliquer le code promo'},
  'Feature access': {gu:'ફીચર ઍક્સેસ',hi:'फ़ीचर एक्सेस',fr:'Accès aux fonctionnalités'},
  'Unlocked and locked tools by plan': {gu:'પ્લાન મુજબ ખુલેલા અને લોક સાધનો',hi:'प्लान के अनुसार उपलब्ध और लॉक टूल',fr:'Outils inclus et verrouillés selon le forfait'},
  'Buy extra scans anytime': {gu:'વધારાના સ્કેન ક્યારે પણ ખરીદો',hi:'अतिरिक्त स्कैन कभी भी खरीदें',fr:'Acheter des scans supplémentaires à tout moment'},
  'Extra receipt scans': {gu:'વધારાના રસીદ સ્કેન',hi:'अतिरिक्त रसीद स्कैन',fr:'Scans de reçus supplémentaires'},
  'Never expires until used': {gu:'ઉપયોગ થાય ત્યાં સુધી સમાપ્ત નહીં થાય',hi:'उपयोग होने तक समाप्त नहीं होता',fr:'N’expire pas avant utilisation'},
  'Account': {gu:'એકાઉન્ટ',hi:'खाता',fr:'Compte'},
  'Account created': {gu:'એકાઉન્ટ બનાવ્યું',hi:'खाता बनाया गया',fr:'Compte créé'},
  'Access type': {gu:'ઍક્સેસ પ્રકાર',hi:'एक्सेस प्रकार',fr:'Type d’accès'},
  'Login method': {gu:'લૉગિન રીત',hi:'लॉगिन तरीका',fr:'Méthode de connexion'},
  'Security': {gu:'સુરક્ષા',hi:'सुरक्षा',fr:'Sécurité'},
  'Change password': {gu:'પાસવર્ડ બદલો',hi:'पासवर्ड बदलें',fr:'Changer le mot de passe'},
  'Logout': {gu:'લૉગઆઉટ',hi:'लॉग आउट',fr:'Déconnexion'},
  'Delete account': {gu:'એકાઉન્ટ કાઢી નાખો',hi:'खाता हटाएं',fr:'Supprimer le compte'},
  'Danger zone': {gu:'જોખમી વિભાગ',hi:'खतरे का क्षेत्र',fr:'Zone sensible'},
  'Your personal insights': {gu:'તમારી વ્યક્તિગત માહિતી',hi:'आपकी व्यक्तिगत जानकारी',fr:'Vos statistiques personnelles'},
  'Receipts uploaded': {gu:'અપલોડ કરેલી રસીદો',hi:'अपलोड की गई रसीदें',fr:'Reçus téléversés'},
  'Prices recorded': {gu:'સાચવેલા ભાવ',hi:'दर्ज की गई कीमतें',fr:'Prix enregistrés'},
  'Stores tracked': {gu:'ટ્રૅક કરેલા સ્ટોર્સ',hi:'ट्रैक किए गए स्टोर',fr:'Magasins suivis'},
  'Tracked spend': {gu:'ટ્રૅક કરેલો ખર્ચ',hi:'ट्रैक किया गया खर्च',fr:'Dépenses suivies'},
  'Reports & store comparison': {gu:'રિપોર્ટ્સ અને સ્ટોર સરખામણી',hi:'रिपोर्ट और स्टोर तुलना',fr:'Rapports et comparaison des magasins'},
  'Monthly household view': {gu:'માસિક ઘરનો દૃશ્ય',hi:'मासिक घरेलू दृश्य',fr:'Vue mensuelle du foyer'},
  'Estimated savings this month': {gu:'આ મહિને અંદાજિત બચત',hi:'इस महीने अनुमानित बचत',fr:'Économies estimées ce mois-ci'},
  'Export price CSV': {gu:'ભાવ CSV એક્સપોર્ટ કરો',hi:'कीमत CSV निर्यात करें',fr:'Exporter les prix en CSV'},
  'Export receipt insights': {gu:'રસીદ માહિતી એક્સપોર્ટ કરો',hi:'रसीद विश्लेषण निर्यात करें',fr:'Exporter les données des reçus'},
  'Smart Weekly Grocery Assistant': {gu:'સ્માર્ટ સાપ્તાહિક ગ્રોસરી સહાયક',hi:'स्मार्ट साप्ताहिक ग्रोसरी सहायक',fr:'Assistant hebdomadaire intelligent'},
  'What needs attention': {gu:'શું ધ્યાન માંગે છે',hi:'किस पर ध्यान चाहिए',fr:'À surveiller'},
  'Your next grocery trip': {gu:'તમારી આગામી ગ્રોસરી ખરીદી',hi:'आपकी अगली ग्रोसरी यात्रा',fr:'Votre prochaine course'},
  'Cook from what you own': {gu:'ઘરમાં જે છે તેમાંથી બનાવો',hi:'घर में जो है उससे बनाएं',fr:'Cuisiner avec ce que vous avez'},
  'Automatic matching': {gu:'આપમેળે મેચિંગ',hi:'स्वचालित मिलान',fr:'Correspondance automatique'},
  'Use soon': {gu:'જલ્દી વાપરો',hi:'जल्द उपयोग करें',fr:'À utiliser bientôt'},
  'Waste prevention': {gu:'બગાડ અટકાવો',hi:'बर्बादी रोकें',fr:'Prévention du gaspillage'},
  'Money saved': {gu:'બચાવેલા પૈસા',hi:'बचाया पैसा',fr:'Argent économisé'},
  'Nearby store options': {gu:'નજીકના સ્ટોર વિકલ્પો',hi:'नज़दीकी स्टोर विकल्प',fr:'Magasins à proximité'},
  'Stores around your trip': {gu:'તમારી ખરીદી આસપાસના સ્ટોર્સ',hi:'आपकी खरीदारी के आसपास स्टोर',fr:'Magasins autour de votre trajet'},
  'Use my location': {gu:'મારું સ્થાન વાપરો',hi:'मेरी लोकेशन उपयोग करें',fr:'Utiliser ma position'},
  'No prices found yet': {gu:'હજુ ભાવ મળ્યા નથી',hi:'अभी कीमतें नहीं मिलीं',fr:'Aucun prix trouvé pour le moment'},
  'Automatic whole-list comparison unlocks here.': {gu:'આપમેળે સંપૂર્ણ યાદી સરખામણી અહીં અનલૉક થાય છે.',hi:'पूरी सूची की स्वचालित तुलना यहाँ अनलॉक होती है।',fr:'La comparaison automatique de toute la liste se débloque ici.'},
  'Only prices we actually found are totaled. Missing prices are never filled with guesses.': {gu:'ફક્ત ખરેખર મળેલા ભાવનો કુલ થાય છે. ગુમ ભાવ અંદાજથી ભરાતા નથી.',hi:'केवल वास्तव में मिली कीमतों का कुल किया जाता है। गायब कीमतें अनुमान से नहीं भरी जातीं।',fr:'Seuls les prix réellement trouvés sont totalisés. Les prix manquants ne sont jamais devinés.'},
  'Use this as your in-store checklist. Add what you need, check items into the cart, then finish shopping to update your Home automatically.': {gu:'આને સ્ટોરની ચેકલિસ્ટ તરીકે વાપરો. જરૂરી વસ્તુ ઉમેરો, કાર્ટમાં ચેક કરો અને ખરીદી પૂર્ણ કરો જેથી ઘર આપમેળે અપડેટ થાય.',hi:'इसे स्टोर की चेकलिस्ट की तरह उपयोग करें। जो चाहिए जोड़ें, कार्ट में चेक करें और खरीदारी पूरी करके घर की इन्वेंटरी अपने आप अपडेट करें।',fr:'Utilisez ceci comme liste en magasin. Ajoutez ce qu’il faut, cochez les articles dans le panier puis terminez les courses pour mettre la maison à jour automatiquement.'},
  'Add what you need, move items into the cart as you shop, then tap Shopping done. Your inventory updates automatically.': {gu:'જેટલું જોઈએ એટલું ઉમેરો, ખરીદી વખતે કાર્ટમાં મૂકો અને પછી ખરીદી પૂર્ણ દબાવો. ઇન્વેન્ટરી આપમેળે અપડેટ થશે.',hi:'जो चाहिए जोड़ें, खरीदते समय वस्तुओं को कार्ट में डालें, फिर खरीदारी पूरी दबाएँ। इन्वेंटरी अपने आप अपडेट होगी।',fr:'Ajoutez ce qu’il faut, déplacez les articles dans le panier puis appuyez sur Courses terminées. L’inventaire se met à jour automatiquement.'},
  'Keep a simple picture of what you already have. Add everyday groceries first; low-stock, expiry, meal, and shopping suggestions will build automatically.': {gu:'ઘરમાં શું છે તેનું સરળ ચિત્ર રાખો. રોજની વસ્તુઓ પહેલાં ઉમેરો; ઓછો સ્ટોક, સમાપ્તિ, ભોજન અને ખરીદી સૂચનો આપમેળે બનશે.',hi:'घर में क्या है उसकी सरल तस्वीर रखें। रोज़मर्रा की चीज़ें पहले जोड़ें; कम स्टॉक, एक्सपायरी, भोजन और खरीदारी सुझाव अपने आप बनेंगे।',fr:'Gardez une vue simple de ce que vous avez. Ajoutez d’abord les produits courants; les alertes de stock, d’expiration, de repas et de courses se construiront automatiquement.'},
  'Start with Inventory, Shopping, or Scan Receipt. Receipt history, prices, and reports stay available when you need the extra detail.': {gu:'ઇન્વેન્ટરી, ખરીદી અથવા રસીદ સ્કેનથી શરૂ કરો. વધુ વિગત માટે રસીદ ઇતિહાસ, ભાવ અને રિપોર્ટ્સ ઉપલબ્ધ રહેશે.',hi:'इन्वेंटरी, खरीदारी या रसीद स्कैन से शुरू करें। ज़रूरत पड़ने पर रसीद इतिहास, कीमतें और रिपोर्ट उपलब्ध रहेंगी।',fr:'Commencez par Inventaire, Courses ou Scanner un reçu. L’historique, les prix et les rapports restent disponibles quand vous avez besoin de détails.'},
  'Pull structured sale prices for your postal code, cache them for your area, and reuse them in whole-list shopping comparisons.': {gu:'તમારા પોસ્ટલ કોડ માટે ગોઠવેલા સેલ ભાવ મેળવો, વિસ્તાર માટે કૅશ કરો અને સંપૂર્ણ ખરીદી યાદી સરખામણીમાં ફરી વાપરો.',hi:'अपने पोस्टल कोड के लिए संरचित सेल कीमतें लें, क्षेत्र के लिए कैश करें और पूरी खरीदारी सूची की तुलना में फिर उपयोग करें।',fr:'Récupérez les prix promotionnels structurés pour votre code postal, mettez-les en cache et réutilisez-les pour comparer toute la liste.'},
  'Shown as an offer only; excluded from exact basket pricing.': {gu:'ફક્ત ઓફર તરીકે બતાવ્યું છે; ચોક્કસ બાસ્કેટ ગણતરીમાં સામેલ નથી.',hi:'केवल ऑफ़र के रूप में दिखाया गया; सटीक बास्केट गणना में शामिल नहीं है।',fr:'Affiché uniquement comme offre; exclu du calcul exact du panier.'},
  'Confirm details on the store page first.': {gu:'પહેલા સ્ટોર પેજ પર વિગતો ખાતરી કરો.',hi:'पहले स्टोर पेज पर विवरण की पुष्टि करें।',fr:'Confirmez d’abord les détails sur la page du magasin.'},
  'Use a Canadian postal code for best results. If left blank, the app asks for location access. If denied, it uses your saved profile city.': {gu:'શ્રેષ્ઠ પરિણામ માટે કેનેડિયન પોસ્ટલ કોડ વાપરો. ખાલી રાખશો તો એપ સ્થાનની પરવાનગી માગશે; ના કહેશો તો પ્રોફાઇલમાં સાચવેલું શહેર વાપરશે.',hi:'बेहतर परिणाम के लिए कनाडाई पोस्टल कोड उपयोग करें। खाली छोड़ने पर ऐप लोकेशन अनुमति माँगेगा; मना करने पर प्रोफ़ाइल में सहेजा शहर उपयोग होगा।',fr:'Utilisez un code postal canadien pour de meilleurs résultats. S’il est vide, l’application demande la position; en cas de refus, elle utilise la ville enregistrée.'},
  'About Grocery House Manager': {gu:'Grocery House Manager વિશે',hi:'Grocery House Manager के बारे में',fr:'À propos de Grocery House Manager'},
  'How to use': {gu:'કેવી રીતે વાપરવું',hi:'कैसे उपयोग करें',fr:'Comment l’utiliser'},
  'Main features': {gu:'મુખ્ય ફીચર્સ',hi:'मुख्य सुविधाएँ',fr:'Fonctionnalités principales'},
  'Best practices': {gu:'શ્રેષ્ઠ રીતો',hi:'सर्वोत्तम अभ्यास',fr:'Bonnes pratiques'},
  'Privacy Policy': {gu:'ગોપનીયતા નીતિ',hi:'गोपनीयता नीति',fr:'Politique de confidentialité'},
  'Terms of Service': {gu:'સેવાની શરતો',hi:'सेवा की शर्तें',fr:'Conditions d’utilisation'},
  'Refund and Cancellation Policy': {gu:'રિફંડ અને રદ કરવાની નીતિ',hi:'रिफंड और रद्दीकरण नीति',fr:'Politique de remboursement et d’annulation'},
  'How can we help?': {gu:'અમે કેવી રીતે મદદ કરી શકીએ?',hi:'हम कैसे मदद कर सकते हैं?',fr:'Comment pouvons-nous aider ?'},
  'Need help with Grocery House Manager?': {gu:'Grocery House Manager માટે મદદ જોઈએ?',hi:'Grocery House Manager में मदद चाहिए?',fr:'Besoin d’aide avec Grocery House Manager ?'},
  'Before contacting support': {gu:'મદદનો સંપર્ક કરતાં પહેલાં',hi:'सहायता से संपर्क करने से पहले',fr:'Avant de contacter l’assistance'},
  'Account recovery': {gu:'એકાઉન્ટ પુનઃપ્રાપ્તિ',hi:'खाता पुनर्प्राप्ति',fr:'Récupération du compte'},
  'Forgot password?': {gu:'પાસવર્ડ ભૂલી ગયા?',hi:'पासवर्ड भूल गए?',fr:'Mot de passe oublié ?'},
  'Back to login': {gu:'લૉગિન પર પાછા',hi:'लॉगिन पर वापस',fr:'Retour à la connexion'},
  'Check your email to finish registration.': {gu:'રજિસ્ટ્રેશન પૂર્ણ કરવા ઇમેઇલ તપાસો.',hi:'पंजीकरण पूरा करने के लिए ईमेल देखें।',fr:'Consultez votre e-mail pour terminer l’inscription.'},
  'Shared grocery inventory, shopping lists, members, and activity updates for your household.': {gu:'તમારા ઘર માટે શેર કરેલી ગ્રોસરી ઇન્વેન્ટરી, ખરીદી યાદીઓ, સભ્યો અને પ્રવૃત્તિ અપડેટ્સ.',hi:'आपके घर के लिए साझा ग्रोसरी इन्वेंटरी, खरीदारी सूचियाँ, सदस्य और गतिविधि अपडेट।',fr:'Inventaire partagé, listes de courses, membres et activité de votre foyer.'},
  'Grocery House Manager': {gu:'Grocery House Manager',hi:'Grocery House Manager',fr:'Grocery House Manager'},
  'A SupremDas Group product': {gu:'SupremDas Group નું ઉત્પાદન',hi:'SupremDas Group का उत्पाद',fr:'Un produit SupremDas Group'},
  'Made for families, couples, and roommates': {gu:'પરિવારો, કપલ્સ અને રૂમમેટ્સ માટે બનાવેલું',hi:'परिवारों, कपल्स और रूममेट्स के लिए बनाया गया',fr:'Conçu pour les familles, couples et colocataires'},
  'Smart grocery management for organized homes.': {gu:'વ્યવસ્થિત ઘરો માટે સ્માર્ટ ગ્રોસરી મેનેજમેન્ટ.',hi:'संगठित घरों के लिए स्मार्ट ग्रोसरी प्रबंधन।',fr:'Gestion intelligente des courses pour les foyers organisés.'},
  'Clean grocery management for organized homes': {gu:'વ્યવસ્થિત ઘરો માટે સરળ ગ્રોસરી મેનેજમેન્ટ',hi:'संगठित घरों के लिए सरल ग्रोसरी प्रबंधन',fr:'Gestion claire des courses pour les foyers organisés'},
  'Inventory • shopping • smart receipts • savings': {gu:'ઇન્વેન્ટરી • ખરીદી • સ્માર્ટ રસીદો • બચત',hi:'इन्वेंटरी • खरीदारी • स्मार्ट रसीदें • बचत',fr:'Inventaire • courses • reçus intelligents • économies'},
  'Built for real grocery habits': {gu:'વાસ્તવિક ગ્રોસરી આદતો માટે બનાવેલું',hi:'वास्तविक ग्रोसरी आदतों के लिए बनाया गया',fr:'Conçu pour de vraies habitudes de courses'},
  'Made for real households': {gu:'વાસ્તવિક ઘરો માટે બનાવેલું',hi:'वास्तविक घरों के लिए बनाया गया',fr:'Conçu pour de vrais foyers'},
  'Stop buying groceries you already have.': {gu:'ઘરમાં પહેલેથી હોય તેવી ગ્રોસરી ફરી ખરીદવાનું બંધ કરો.',hi:'जो किराना घर में पहले से है उसे दोबारा खरीदना बंद करें।',fr:'Arrêtez de racheter ce que vous avez déjà.'},
  'Know what is home': {gu:'ઘરમાં શું છે તે જાણો',hi:'जानें घर में क्या है',fr:'Sachez ce que vous avez à la maison'},
  'Add what is actually needed': {gu:'ખરેખર જે જોઈએ તે જ ઉમેરો',hi:'वही जोड़ें जिसकी वास्तव में ज़रूरत है',fr:'Ajoutez seulement ce qui est réellement nécessaire'},
  'Auto-check the whole trip': {gu:'સંપૂર્ણ ખરીદી આપમેળે તપાસો',hi:'पूरी खरीदारी अपने आप जाँचें',fr:'Vérifier automatiquement tout le panier'},
  'Inventory, receipts, and lists in one place': {gu:'ઇન્વેન્ટરી, રસીદો અને યાદીઓ એક જ જગ્યાએ',hi:'इन्वेंटरी, रसीदें और सूचियाँ एक ही जगह',fr:'Inventaire, reçus et listes au même endroit'},
  'Everything is placed where everyday users expect it.': {gu:'દરરોજના વપરાશકર્તાઓને જ્યાં અપેક્ષા હોય ત્યાં બધું ગોઠવેલું છે.',hi:'हर चीज़ वहीं रखी गई है जहाँ रोज़मर्रा के उपयोगकर्ता उसे ढूँढते हैं।',fr:'Tout est placé là où les utilisateurs s’attendent à le trouver.'},
  'Designed so every household member can understand it quickly.': {gu:'ઘરના દરેક સભ્યને ઝડપથી સમજાય તે રીતે ડિઝાઇન કરેલું.',hi:'ऐसा डिज़ाइन कि घर का हर सदस्य इसे जल्दी समझ सके।',fr:'Conçu pour être compris rapidement par chaque membre du foyer.'},
  'The reason to come back every week': {gu:'દર અઠવાડિયે પાછા આવવાનું કારણ',hi:'हर सप्ताह वापस आने का कारण',fr:'La raison de revenir chaque semaine'},
  'Review details before saving trusted prices': {gu:'વિશ્વસનીય ભાવ સાચવતા પહેલાં વિગતો તપાસો',hi:'विश्वसनीय कीमतें सहेजने से पहले विवरण जाँचें',fr:'Vérifiez les détails avant d’enregistrer les prix'},
  'No invented savings': {gu:'કલ્પિત બચત નહીં',hi:'काल्पनिक बचत नहीं',fr:'Aucune économie inventée'},
  'Latest prices remembered': {gu:'તાજેતરના ભાવ યાદ રાખેલા',hi:'नवीनतम कीमतें याद रखी गईं',fr:'Derniers prix mémorisés'},
  'Shared grocery house': {gu:'શેર કરેલું ગ્રોસરી ઘર',hi:'साझा ग्रोसरी घर',fr:'Maison d’épicerie partagée'},
  'Simple workflow': {gu:'સરળ પ્રક્રિયા',hi:'सरल प्रक्रिया',fr:'Flux simple'},
  'Trust before flash': {gu:'ચમક પહેલાં વિશ્વાસ',hi:'दिखावे से पहले भरोसा',fr:'La confiance avant le spectacle'},
  'Track what you saved': {gu:'તમે કેટલી બચત કરી તે ટ્રૅક કરો',hi:'आपने कितना बचाया, उसे ट्रैक करें',fr:'Suivez vos économies'},
  'Start free. Upgrade when your household is ready.': {gu:'મફતમાં શરૂ કરો. ઘર તૈયાર થાય ત્યારે અપગ્રેડ કરો.',hi:'मुफ़्त शुरू करें। घर तैयार होने पर अपग्रेड करें।',fr:'Commencez gratuitement. Passez au niveau supérieur quand votre foyer est prêt.'},
  'Create your first free house': {gu:'તમારું પહેલું મફત ઘર બનાવો',hi:'अपना पहला मुफ़्त घर बनाएं',fr:'Créez votre première maison gratuite'},
  'Loading your houses...': {gu:'તમારા ઘરો લોડ થઈ રહ્યા છે...',hi:'आपके घर लोड हो रहे हैं...',fr:'Chargement de vos maisons...'},
  'Community snapshot': {gu:'સમુદાયની ઝલક',hi:'समुदाय की झलक',fr:'Aperçu de la communauté'},
  'Limited new-user offer': {gu:'નવા વપરાશકર્તા માટે મર્યાદિત ઓફર',hi:'नए उपयोगकर्ता के लिए सीमित ऑफ़र',fr:'Offre limitée pour nouveaux utilisateurs'},
  'Claim offer': {gu:'ઓફર મેળવો',hi:'ऑफ़र लें',fr:'Profiter de l’offre'},
  'Offer ended': {gu:'ઓફર સમાપ્ત',hi:'ऑफ़र समाप्त',fr:'Offre terminée'},
  'Buy extra receipt scans anytime': {gu:'વધારાના રસીદ સ્કેન ક્યારે પણ ખરીદો',hi:'अतिरिक्त रसीद स्कैन कभी भी खरीदें',fr:'Achetez des scans supplémentaires à tout moment'},
  'No lock-in': {gu:'કોઈ બંધન નહીં',hi:'कोई लॉक-इन नहीं',fr:'Sans engagement'},
  'User reviews': {gu:'વપરાશકર્તા સમીક્ષાઓ',hi:'उपयोगकर्ता समीक्षाएँ',fr:'Avis des utilisateurs'},
  'No reviews yet': {gu:'હજુ સમીક્ષા નથી',hi:'अभी कोई समीक्षा नहीं',fr:'Pas encore d’avis'},
  'Be the first person to share your experience.': {gu:'તમારો અનુભવ શેર કરનાર પ્રથમ બનો.',hi:'अपना अनुभव साझा करने वाले पहले व्यक्ति बनें।',fr:'Soyez la première personne à partager votre expérience.'},
  'Share your Grocery House Manager experience': {gu:'Grocery House Manager નો તમારો અનુભવ શેર કરો',hi:'Grocery House Manager का अपना अनुभव साझा करें',fr:'Partagez votre expérience Grocery House Manager'},
  'Reviews help new users trust the app and help us improve what matters most.': {gu:'સમીક્ષાઓ નવા વપરાશકર્તાઓને એપ પર વિશ્વાસ કરવામાં અને અમને મહત્વની બાબતો સુધારવામાં મદદ કરે છે.',hi:'समीक्षाएँ नए उपयोगकर्ताओं को ऐप पर भरोसा करने और हमें महत्वपूर्ण चीज़ें सुधारने में मदद करती हैं।',fr:'Les avis aident les nouveaux utilisateurs à faire confiance à l’application et nous aident à l’améliorer.'},
  'Loading inventory...': {gu:'ઇન્વેન્ટરી લોડ થઈ રહી છે...',hi:'इन्वेंटरी लोड हो रही है...',fr:'Chargement de l’inventaire...'},
  'Use sections to keep grocery items easy to find.': {gu:'ગ્રોસરી વસ્તુઓ સરળતાથી મળે તે માટે વિભાગો વાપરો.',hi:'ग्रोसरी वस्तुओं को आसानी से ढूँढने के लिए सेक्शन उपयोग करें।',fr:'Utilisez des sections pour retrouver facilement les produits.'},
  'Sort products by name, price, store name, quantity, expiry date, or newest.': {gu:'પ્રોડક્ટ્સને નામ, ભાવ, સ્ટોર, માત્રા, સમાપ્તિ તારીખ અથવા નવા ક્રમમાં ગોઠવો.',hi:'उत्पादों को नाम, कीमत, स्टोर, मात्रा, एक्सपायरी या नवीनतम के अनुसार क्रमबद्ध करें।',fr:'Triez les produits par nom, prix, magasin, quantité, expiration ou nouveauté.'},
  'Loading grocery lists...': {gu:'ગ્રોસરી યાદીઓ લોડ થઈ રહી છે...',hi:'ग्रोसरी सूचियाँ लोड हो रही हैं...',fr:'Chargement des listes de courses...'},
  'Select products below': {gu:'નીચે પ્રોડક્ટ્સ પસંદ કરો',hi:'नीचे उत्पाद चुनें',fr:'Sélectionnez les produits ci-dessous'},
  'Product not in inventory?': {gu:'પ્રોડક્ટ ઇન્વેન્ટરીમાં નથી?',hi:'उत्पाद इन्वेंटरी में नहीं है?',fr:'Produit absent de l’inventaire ?'},
  'Create it here and add it to this grocery list right away. We check existing inventory first to prevent duplicates.': {gu:'અહીં બનાવો અને તરત આ ગ્રોસરી યાદીમાં ઉમેરો. ડુપ્લિકેટ અટકાવવા પહેલા હાલની ઇન્વેન્ટરી તપાસીએ છીએ.',hi:'इसे यहाँ बनाएं और तुरंत इस ग्रोसरी सूची में जोड़ें। डुप्लिकेट रोकने के लिए पहले मौजूदा इन्वेंटरी जाँची जाती है।',fr:'Créez-le ici et ajoutez-le immédiatement à cette liste. L’inventaire existant est vérifié pour éviter les doublons.'},
  'Search by product, brand, store, or barcode. You can also create a product here if it is not in inventory yet.': {gu:'પ્રોડક્ટ, બ્રાન્ડ, સ્ટોર અથવા બારકોડથી શોધો. ઇન્વેન્ટરીમાં ન હોય તો અહીં નવું પ્રોડક્ટ બનાવી શકો.',hi:'उत्पाद, ब्रांड, स्टोर या बारकोड से खोजें। इन्वेंटरी में न हो तो यहाँ नया उत्पाद बना सकते हैं।',fr:'Recherchez par produit, marque, magasin ou code-barres. Vous pouvez aussi créer un produit s’il n’existe pas encore.'},
  'Only items under “Added in cart” update real inventory.': {gu:'ફક્ત “કાર્ટમાં ઉમેર્યું” હેઠળની વસ્તુઓ વાસ્તવિક ઇન્વેન્ટરી અપડેટ કરે છે.',hi:'केवल “कार्ट में जोड़ा” वाली वस्तुएँ वास्तविक इन्वेंटरी अपडेट करती हैं।',fr:'Seuls les articles « Ajoutés au panier » mettent l’inventaire réel à jour.'},
  'If you have the receipt, scan it now and Grocery House Manager can save the real prices and spending history automatically.': {gu:'રસીદ હોય તો હમણાં સ્કેન કરો; Grocery House Manager વાસ્તવિક ભાવ અને ખર્ચ ઇતિહાસ આપમેળે સાચવી શકે છે.',hi:'यदि रसीद है तो अभी स्कैन करें; Grocery House Manager वास्तविक कीमतें और खर्च इतिहास अपने आप सहेज सकता है।',fr:'Si vous avez le reçu, scannez-le maintenant pour enregistrer automatiquement les prix réels et l’historique des dépenses.'},
  'Family Plus • automatic trip check': {gu:'ફેમિલી પ્લસ • આપમેળે ટ્રિપ ચેક',hi:'फैमिली प्लस • स्वचालित ट्रिप जाँच',fr:'Family Plus • vérification automatique du trajet'},
  'Household Pro • nearby convenience': {gu:'હાઉસહોલ્ડ પ્રો • નજીકની સુવિધા',hi:'हाउसहोल्ड प्रो • नज़दीकी सुविधा',fr:'Household Pro • proximité pratique'},
  'Where should I buy': {gu:'મારે ક્યાંથી ખરીદવું',hi:'मुझे कहाँ से खरीदना चाहिए',fr:'Où acheter'},
  'Ready': {gu:'તૈયાર',hi:'तैयार',fr:'Prêt'},
  'Checking prices…': {gu:'ભાવ તપાસી રહ્યા છીએ…',hi:'कीमतें जाँची जा रही हैं…',fr:'Vérification des prix…'},
  'Checked automatically': {gu:'આપમેળે તપાસ્યું',hi:'अपने आप जाँचा गया',fr:'Vérifié automatiquement'},
  'Refresh prices': {gu:'ભાવ રિફ્રેશ કરો',hi:'कीमतें रीफ़्रेश करें',fr:'Actualiser les prix'},
  'View store details': {gu:'સ્ટોર વિગતો જુઓ',hi:'स्टोर विवरण देखें',fr:'Voir les détails des magasins'},
  'Collapse details': {gu:'વિગતો બંધ કરો',hi:'विवरण समेटें',fr:'Réduire les détails'},
  'Postal code (optional) for nearby prices': {gu:'નજીકના ભાવ માટે પોસ્ટલ કોડ (વૈકલ્પિક)',hi:'नज़दीकी कीमतों के लिए पोस्टल कोड (वैकल्पिक)',fr:'Code postal (facultatif) pour les prix locaux'},
  'Use & refresh': {gu:'વાપરો અને રિફ્રેશ કરો',hi:'उपयोग करें और रीफ़्रेश करें',fr:'Utiliser et actualiser'},
  'Weekly deals matching this grocery list': {gu:'આ ગ્રોસરી યાદીને મેળ ખાતી સાપ્તાહિક ડીલ',hi:'इस ग्रोसरी सूची से मेल खाते साप्ताहिक ऑफ़र',fr:'Offres hebdomadaires correspondant à cette liste'},
  'Open full flyers': {gu:'સંપૂર્ણ ફ્લાયર્સ ખોલો',hi:'पूरे फ्लायर खोलें',fr:'Ouvrir les circulaires complètes'},
  'These are current advertised offers for items already on this list. Package sizes and in-store availability should still be confirmed.': {gu:'આ યાદીમાં રહેલી વસ્તુઓ માટેની હાલની જાહેરાતી ઓફરો છે. પેકેજ સાઇઝ અને સ્ટોર ઉપલબ્ધતા ખાતરી કરો.',hi:'ये इस सूची की वस्तुओं के वर्तमान विज्ञापित ऑफ़र हैं। पैकेज आकार और स्टोर उपलब्धता की पुष्टि करें।',fr:'Voici les offres actuelles pour les articles de cette liste. Vérifiez encore le format et la disponibilité en magasin.'},
  'Confirm advertised package size before buying.': {gu:'ખરીદતા પહેલાં જાહેરાતમાં આપેલી પેકેજ સાઇઝ ખાતરી કરો.',hi:'खरीदने से पहले विज्ञापित पैकेज आकार की पुष्टि करें।',fr:'Vérifiez le format annoncé avant l’achat.'},
  'Nearby grocery stores': {gu:'નજીકના ગ્રોસરી સ્ટોર્સ',hi:'नज़दीकी ग्रोसरी स्टोर',fr:'Épiceries à proximité'},
  'Open in maps': {gu:'મેપમાં ખોલો',hi:'मैप में खोलें',fr:'Ouvrir dans Maps'},
  'Finding useful nearby options automatically…': {gu:'ઉપયોગી નજીકના વિકલ્પો આપમેળે શોધી રહ્યા છીએ…',hi:'उपयोगी नज़दीकी विकल्प अपने आप खोजे जा रहे हैं…',fr:'Recherche automatique des options utiles à proximité…'},
  'No nearby store results were returned for this area.': {gu:'આ વિસ્તારમાં નજીકના સ્ટોર પરિણામ મળ્યા નથી.',hi:'इस क्षेत्र के लिए नज़दीकी स्टोर परिणाम नहीं मिले।',fr:'Aucun magasin à proximité n’a été trouvé pour cette zone.'},
  'Loading receipt history...': {gu:'રસીદ ઇતિહાસ લોડ થઈ રહ્યો છે...',hi:'रसीद इतिहास लोड हो रहा है...',fr:'Chargement de l’historique des reçus...'},
  'No saved receipts yet': {gu:'હજુ કોઈ રસીદ સાચવેલી નથી',hi:'अभी कोई रसीद सहेजी नहीं गई',fr:'Aucun reçu enregistré pour le moment'},
  'Scan my first receipt': {gu:'મારી પહેલી રસીદ સ્કેન કરો',hi:'मेरी पहली रसीद स्कैन करें',fr:'Scanner mon premier reçu'},
  'Scan your first receipt': {gu:'તમારી પહેલી રસીદ સ્કેન કરો',hi:'अपनी पहली रसीद स्कैन करें',fr:'Scannez votre premier reçu'},
  'Extracted product rows': {gu:'કાઢેલી પ્રોડક્ટ લાઇનો',hi:'निकाली गई उत्पाद पंक्तियाँ',fr:'Lignes de produits extraites'},
  'Product rows saved': {gu:'સાચવેલી પ્રોડક્ટ લાઇનો',hi:'सहेजी गई उत्पाद पंक्तियाँ',fr:'Lignes de produits enregistrées'},
  'Search by store, date, product, or payment.': {gu:'સ્ટોર, તારીખ, પ્રોડક્ટ અથવા ચુકવણીથી શોધો.',hi:'स्टोर, तारीख, उत्पाद या भुगतान से खोजें।',fr:'Recherchez par magasin, date, produit ou paiement.'},
  'Total receipt spend': {gu:'કુલ રસીદ ખર્ચ',hi:'कुल रसीद खर्च',fr:'Dépenses totales des reçus'},
  'Scan, review, and save receipt prices': {gu:'રસીદ સ્કેન કરો, તપાસો અને ભાવ સાચવો',hi:'रसीद स्कैन करें, जाँचें और कीमतें सहेजें',fr:'Scanner, vérifier et enregistrer les prix du reçu'},
  'Professional scan': {gu:'પ્રોફેશનલ સ્કેન',hi:'प्रोफ़ेशनल स्कैन',fr:'Scan professionnel'},
  'Smart scan with your final approval': {gu:'તમારી અંતિમ મંજૂરી સાથે સ્માર્ટ સ્કેન',hi:'आपकी अंतिम मंज़ूरी के साथ स्मार्ट स्कैन',fr:'Scan intelligent avec votre validation finale'},
  'Review extracted rows': {gu:'કાઢેલી લાઇનો તપાસો',hi:'निकाली गई पंक्तियाँ जाँचें',fr:'Vérifier les lignes extraites'},
  'Available extra scans': {gu:'ઉપલબ્ધ વધારાના સ્કેન',hi:'उपलब्ध अतिरिक्त स्कैन',fr:'Scans supplémentaires disponibles'},
  'View extra scan packs': {gu:'વધારાના સ્કેન પેક જુઓ',hi:'अतिरिक्त स्कैन पैक देखें',fr:'Voir les packs de scans'},
  'Update inventory': {gu:'ઇન્વેન્ટરી અપડેટ કરો',hi:'इन्वेंटरी अपडेट करें',fr:'Mettre l’inventaire à jour'},
  'Reports appear automatically after you add groceries and save reviewed receipts. There is nothing to configure here.': {gu:'ગ્રોસરી ઉમેર્યા અને તપાસેલી રસીદ સાચવ્યા પછી રિપોર્ટ્સ આપમેળે દેખાશે. અહીં કંઈ સેટ કરવાની જરૂર નથી.',hi:'ग्रोसरी जोड़ने और जाँची हुई रसीदें सहेजने के बाद रिपोर्ट अपने आप दिखाई देंगी। यहाँ कुछ सेट करने की ज़रूरत नहीं है।',fr:'Les rapports apparaissent automatiquement après l’ajout de produits et de reçus vérifiés. Rien n’est à configurer ici.'},
  'Your reports will build automatically': {gu:'તમારા રિપોર્ટ્સ આપમેળે બનશે',hi:'आपकी रिपोर्ट अपने आप बनेंगी',fr:'Vos rapports se construiront automatiquement'},
  'Store activity': {gu:'સ્ટોર પ્રવૃત્તિ',hi:'स्टोर गतिविधि',fr:'Activité par magasin'},
  'Prices remembered': {gu:'યાદ રાખેલા ભાવ',hi:'याद रखी गई कीमतें',fr:'Prix mémorisés'},
  'Need attention': {gu:'ધ્યાન જરૂરી',hi:'ध्यान चाहिए',fr:'À surveiller'},
  'Did the subscription pay for itself?': {gu:'સબ્સ્ક્રિપ્શનનો ખર્ચ વસૂલ થયો?',hi:'क्या सब्सक्रिप्शन ने अपनी लागत निकाल ली?',fr:'L’abonnement s’est-il rentabilisé ?'},
  'Loading your household summary…': {gu:'તમારા ઘરનો સાર લોડ થઈ રહ્યો છે…',hi:'आपके घर का सारांश लोड हो रहा है…',fr:'Chargement du résumé du foyer…'},
  'Know what you have, what you need, and where your money is going.': {gu:'તમારી પાસે શું છે, શું જોઈએ અને પૈસા ક્યાં જાય છે તે જાણો.',hi:'जानें आपके पास क्या है, क्या चाहिए और पैसा कहाँ जा रहा है।',fr:'Sachez ce que vous avez, ce qu’il vous faut et où va votre argent.'},
  'Inventory pulse': {gu:'ઇન્વેન્ટરી સ્થિતિ',hi:'इन्वेंटरी स्थिति',fr:'État de l’inventaire'},
  'Next trip': {gu:'આગામી ખરીદી',hi:'अगली खरीदारी',fr:'Prochaine course'},
  'Meal ideas from groceries already at home': {gu:'ઘરમાં રહેલી ગ્રોસરીમાંથી ભોજન વિચારો',hi:'घर की ग्रोसरी से भोजन के सुझाव',fr:'Idées de repas avec ce que vous avez déjà'},
  'No strong meal match yet': {gu:'હજુ મજબૂત ભોજન મેળ નથી',hi:'अभी कोई अच्छा भोजन मेल नहीं मिला',fr:'Pas encore de bonne correspondance de repas'},
  'Nothing new needs to be added right now.': {gu:'હમણાં કંઈ નવું ઉમેરવાની જરૂર નથી.',hi:'अभी कुछ नया जोड़ने की ज़रूरत नहीं है।',fr:'Rien de nouveau à ajouter pour le moment.'},
  'Create shopping list': {gu:'ખરીદી યાદી બનાવો',hi:'खरीदारी सूची बनाएं',fr:'Créer une liste de courses'},
  'Open shopping list': {gu:'ખરીદી યાદી ખોલો',hi:'खरीदारी सूची खोलें',fr:'Ouvrir la liste de courses'},
  'Review inventory': {gu:'ઇન્વેન્ટરી તપાસો',hi:'इन्वेंटरी जाँचें',fr:'Vérifier l’inventaire'},
  'Review dates': {gu:'તારીખો તપાસો',hi:'तारीखें जाँचें',fr:'Vérifier les dates'},
  'Open savings report': {gu:'બચત રિપોર્ટ ખોલો',hi:'बचत रिपोर्ट खोलें',fr:'Ouvrir le rapport d’économies'},
  'Plan access': {gu:'પ્લાન ઍક્સેસ',hi:'प्लान एक्सेस',fr:'Accès du forfait'},
  'Choose your Grocery Home': {gu:'તમારું ગ્રોસરી ઘર પસંદ કરો',hi:'अपना ग्रोसरी होम चुनें',fr:'Choisissez votre maison d’épicerie'},
  'Choose a house': {gu:'ઘર પસંદ કરો',hi:'घर चुनें',fr:'Choisir une maison'},
  'Create or join a Grocery Home first': {gu:'પહેલા ગ્રોસરી ઘર બનાવો અથવા જોડાઓ',hi:'पहले ग्रोसरी होम बनाएं या जुड़ें',fr:'Créez ou rejoignez d’abord une maison'},
  'Find & compare': {gu:'શોધો અને સરખાવો',hi:'खोजें और तुलना करें',fr:'Rechercher et comparer'},
  'Live prices': {gu:'લાઇવ ભાવ',hi:'लाइव कीमतें',fr:'Prix en direct'},
  'Connected': {gu:'જોડાયેલ',hi:'कनेक्टेड',fr:'Connecté'},
  'Not connected': {gu:'જોડાયેલ નથી',hi:'कनेक्ट नहीं',fr:'Non connecté'},
  'Loading flyers…': {gu:'ફ્લાયર્સ લોડ થઈ રહ્યા છે…',hi:'फ्लायर लोड हो रहे हैं…',fr:'Chargement des circulaires…'},
  'Browse full weekly flyers by store': {gu:'સ્ટોર મુજબ સંપૂર્ણ સાપ્તાહિક ફ્લાયર્સ જુઓ',hi:'स्टोर के अनुसार पूरे साप्ताहिक फ्लायर देखें',fr:'Parcourir les circulaires complètes par magasin'},
  'Open any store to see every deal returned for its current flyer. Search above when you only want one grocery item.': {gu:'કોઈ પણ સ્ટોર ખોલીને તેના હાલના ફ્લાયરની બધી ડીલ જુઓ. એક વસ્તુ માટે ઉપર શોધો.',hi:'किसी भी स्टोर को खोलकर उसके वर्तमान फ्लायर के सभी ऑफ़र देखें। केवल एक वस्तु चाहिए तो ऊपर खोजें।',fr:'Ouvrez un magasin pour voir toutes les offres de sa circulaire actuelle. Utilisez la recherche ci-dessus pour un seul article.'},
  'Cache valid until': {gu:'કૅશ આ તારીખ સુધી માન્ય',hi:'कैश इस समय तक मान्य',fr:'Cache valide jusqu’au'},
  'Search product': {gu:'પ્રોડક્ટ શોધો',hi:'उत्पाद खोजें',fr:'Rechercher le produit'},
  'Review details before saving': {gu:'સાચવતા પહેલાં વિગતો તપાસો',hi:'सहेजने से पहले विवरण जाँचें',fr:'Vérifier les détails avant d’enregistrer'},
  'Category can be edited later': {gu:'કેટેગરી પછી બદલી શકો',hi:'श्रेणी बाद में बदली जा सकती है',fr:'La catégorie peut être modifiée plus tard'},
  'Found price': {gu:'મળેલો ભાવ',hi:'मिली कीमत',fr:'Prix trouvé'},
  'Open product': {gu:'પ્રોડક્ટ ખોલો',hi:'उत्पाद खोलें',fr:'Ouvrir le produit'},
  'Open store search': {gu:'સ્ટોર શોધ ખોલો',hi:'स्टोर खोज खोलें',fr:'Ouvrir la recherche du magasin'},
  'Loading your account...': {gu:'તમારું એકાઉન્ટ લોડ થઈ રહ્યું છે...',hi:'आपका खाता लोड हो रहा है...',fr:'Chargement de votre compte...'},
  'Manage your account details, subscription, logout, and account deletion from here.': {gu:'અહીંથી એકાઉન્ટ વિગતો, સબ્સ્ક્રિપ્શન, લૉગઆઉટ અને એકાઉન્ટ ડિલીટ મેનેજ કરો.',hi:'यहाँ से खाते का विवरण, सब्सक्रिप्शन, लॉगआउट और खाता हटाना प्रबंधित करें।',fr:'Gérez ici vos informations, votre abonnement, la déconnexion et la suppression du compte.'},
  'Personal premium tools': {gu:'વ્યક્તિગત પ્રીમિયમ સાધનો',hi:'व्यक्तिगत प्रीमियम टूल',fr:'Outils premium personnels'},
  'No payment': {gu:'ચુકવણી નથી',hi:'कोई भुगतान नहीं',fr:'Aucun paiement'},
  'No automatic deduction scheduled': {gu:'આપમેળે કપાત નક્કી નથી',hi:'कोई स्वचालित कटौती निर्धारित नहीं',fr:'Aucun prélèvement automatique prévu'},
  'This is the end of the current billing period; the plan renews automatically.': {gu:'આ હાલના બિલિંગ પિરિયડનો અંત છે; પ્લાન આપમેળે રિન્યૂ થશે.',hi:'यह वर्तमान बिलिंग अवधि का अंत है; प्लान अपने आप नवीनीकृत होगा।',fr:'C’est la fin de la période de facturation actuelle; le forfait se renouvelle automatiquement.'},
  'For security, your new password cannot match any of your last 5 passwords.': {gu:'સુરક્ષા માટે નવો પાસવર્ડ છેલ્લા 5 પાસવર્ડમાંથી કોઈપણ જેવો ન હોઈ શકે.',hi:'सुरक्षा के लिए नया पासवर्ड आपके पिछले 5 पासवर्ड में से किसी जैसा नहीं हो सकता।',fr:'Pour votre sécurité, le nouveau mot de passe ne peut pas être l’un des 5 derniers.'},
  'Choose billing': {gu:'બિલિંગ પસંદ કરો',hi:'बिलिंग चुनें',fr:'Choisir la facturation'},
  'Most popular': {gu:'સૌથી લોકપ્રિય',hi:'सबसे लोकप्रिय',fr:'Le plus populaire'},
  'Have a coupon?': {gu:'કૂપન છે?',hi:'कूपन है?',fr:'Vous avez un coupon ?'},
  'Coupon applied': {gu:'કૂપન લાગુ થયો',hi:'कूपन लागू हुआ',fr:'Coupon appliqué'},
  'Need help choosing?': {gu:'પસંદગીમાં મદદ જોઈએ?',hi:'चुनने में मदद चाहिए?',fr:'Besoin d’aide pour choisir ?'},
  'Loading plans...': {gu:'પ્લાન્સ લોડ થઈ રહ્યા છે...',hi:'प्लान लोड हो रहे हैं...',fr:'Chargement des forfaits...'},
  'Login to subscribe': {gu:'સબ્સ્ક્રાઇબ કરવા લૉગિન કરો',hi:'सब्सक्राइब करने के लिए लॉगिन करें',fr:'Connectez-vous pour vous abonner'},
  'Viewing plans as a guest.': {gu:'મહેમાન તરીકે પ્લાન્સ જોઈ રહ્યા છો.',hi:'अतिथि के रूप में प्लान देख रहे हैं।',fr:'Vous consultez les forfaits en tant qu’invité.'},
  'Find quick guidance for accounts, houses, billing, plans, market tools, receipts, and subscriptions.': {gu:'એકાઉન્ટ, ઘર, બિલિંગ, પ્લાન, માર્કેટ ટૂલ્સ, રસીદો અને સબ્સ્ક્રિપ્શન માટે ઝડપી માર્ગદર્શન મેળવો.',hi:'खाते, घर, बिलिंग, प्लान, मार्केट टूल, रसीद और सब्सक्रिप्शन के लिए त्वरित मार्गदर्शन पाएँ।',fr:'Trouvez rapidement de l’aide pour les comptes, maisons, facturation, forfaits, prix, reçus et abonnements.'},
  'Never send full card numbers, passwords, or sensitive payment details.': {gu:'પૂર્ણ કાર્ડ નંબર, પાસવર્ડ અથવા સંવેદનશીલ ચુકવણી વિગતો ક્યારેય મોકલશો નહીં.',hi:'पूरा कार्ड नंबर, पासवर्ड या संवेदनशील भुगतान जानकारी कभी न भेजें।',fr:'N’envoyez jamais de numéro de carte complet, mot de passe ou données de paiement sensibles.'},
  'Information we collect': {gu:'અમે એકત્રિત કરતી માહિતી',hi:'हम जो जानकारी एकत्र करते हैं',fr:'Informations collectées'},
  'How we use information': {gu:'માહિતી કેવી રીતે વાપરીએ છીએ',hi:'हम जानकारी का उपयोग कैसे करते हैं',fr:'Utilisation des informations'},
  'Data retention and deletion': {gu:'ડેટા જાળવણી અને ડિલીટ',hi:'डेटा संरक्षण और हटाना',fr:'Conservation et suppression des données'},
  'Sharing inside a house': {gu:'ઘરમાં માહિતી શેરિંગ',hi:'घर के भीतर साझा करना',fr:'Partage au sein d’une maison'},
  'Payment processing': {gu:'ચુકવણી પ્રક્રિયા',hi:'भुगतान प्रसंस्करण',fr:'Traitement des paiements'},
  'Google sign-in': {gu:'Google સાઇન-ઇન',hi:'Google साइन-इन',fr:'Connexion Google'},
  'Accounts and security': {gu:'એકાઉન્ટ અને સુરક્ષા',hi:'खाते और सुरक्षा',fr:'Comptes et sécurité'},
  'Acceptable use': {gu:'સ્વીકાર્ય ઉપયોગ',hi:'स्वीकार्य उपयोग',fr:'Utilisation acceptable'},
  'Subscriptions and plan limits': {gu:'સબ્સ્ક્રિપ્શન અને પ્લાન મર્યાદા',hi:'सब्सक्रिप्शन और प्लान सीमाएँ',fr:'Abonnements et limites des forfaits'},
  'Cancellation': {gu:'રદ કરવું',hi:'रद्दीकरण',fr:'Annulation'},
  'Contact': {gu:'સંપર્ક',hi:'संपर्क',fr:'Contact'},
  'Availability': {gu:'ઉપલબ્ધતા',hi:'उपलब्धता',fr:'Disponibilité'},
  'Billing issues': {gu:'બિલિંગ સમસ્યાઓ',hi:'बिलिंग समस्याएँ',fr:'Problèmes de facturation'},
  'Promotions and coupons': {gu:'પ્રમોશન અને કૂપન',hi:'प्रमोशन और कूपन',fr:'Promotions et coupons'},
  'Monthly subscriptions': {gu:'માસિક સબ્સ્ક્રિપ્શન',hi:'मासिक सब्सक्रिप्शन',fr:'Abonnements mensuels'},
  'Jain': {gu:'જૈન',hi:'जैन',fr:'Jaïn'},
  'Swaminarayan': {gu:'સ્વામિનારાયણ',hi:'स्वामीनारायण',fr:'Swaminarayan'},
  'Swaminarayan (no onion/garlic)': {gu:'સ્વામિનારાયણ (ડુંગળી/લસણ વગર)',hi:'स्वामीनारायण (बिना प्याज़/लहसुन)',fr:'Swaminarayan (sans oignon/ail)'},
  'Vegetarian': {gu:'શાકાહારી',hi:'शाकाहारी',fr:'Végétarien'},
  'Veg': {gu:'શાકાહારી',hi:'शाकाहारी',fr:'Végétarien'},
  'Vegan': {gu:'વીગન',hi:'वीगन',fr:'Végane'},
  'Non-vegetarian': {gu:'માંસાહારી',hi:'मांसाहारी',fr:'Non végétarien'},
  'Non-veg': {gu:'માંસાહારી',hi:'मांसाहारी',fr:'Non végétarien'},
  'Weekly flyer': {gu:'સાપ્તાહિક ફ્લાયર',hi:'साप्ताहिक फ्लायर',fr:'Circulaire hebdomadaire'},
  'Current weekly flyers': {gu:'હાલના સાપ્તાહિક ફ્લાયર્સ',hi:'वर्तमान साप्ताहिक फ्लायर',fr:'Circulaires hebdomadaires actuelles'},
  'Requested quantity': {gu:'જરૂરી માત્રા',hi:'आवश्यक मात्रा',fr:'Quantité demandée'},

  "← Home": {gu:"← હોમ",hi:"← होम",fr:"← Accueil"},
  "Last updated: July 2026": {gu:"છેલ્લું અપડેટ: જુલાઈ 2026",hi:"अंतिम अपडेट: जुलाई 2026",fr:"Dernière mise à jour : juillet 2026"},
  "Coupons and offers": {gu:"કૂપન અને ઓફરો",hi:"कूपन और ऑफ़र",fr:"Coupons et offres"},
  "Receipt scanning and product data": {gu:"રસીદ સ્કેનિંગ અને પ્રોડક્ટ ડેટા",hi:"रसीद स्कैनिंग और उत्पाद डेटा",fr:"Numérisation des reçus et données produit"},
  "Smart Receipt Scan": {gu:"સ્માર્ટ રસીદ સ્કેન",hi:"स्मार्ट रसीद स्कैन",fr:"Scan intelligent des reçus"},
  "Grocery House Manager is a household grocery management product from SupremDas Group. This Privacy Policy explains what information the service may collect, how it is used, and how users can manage their information.": {gu:"Grocery House Manager એ SupremDas Group નું ઘરેલુ ગ્રોસરી મેનેજમેન્ટ પ્રોડક્ટ છે. આ ગોપનીયતા નીતિ સમજાવે છે કે સેવા કઈ માહિતી એકત્રિત કરી શકે છે, તેનો ઉપયોગ કેવી રીતે થાય છે અને વપરાશકર્તાઓ પોતાની માહિતી કેવી રીતે મેનેજ કરી શકે છે.",hi:"Grocery House Manager, SupremDas Group का घरेलू ग्रोसरी प्रबंधन उत्पाद है। यह गोपनीयता नीति बताती है कि सेवा कौन-सी जानकारी एकत्र कर सकती है, उसका उपयोग कैसे होता है और उपयोगकर्ता अपनी जानकारी कैसे प्रबंधित कर सकते हैं।",fr:"Grocery House Manager est un produit de gestion des courses du foyer de SupremDas Group. Cette politique explique quelles informations le service peut recueillir, comment elles sont utilisées et comment les utilisateurs peuvent les gérer."},
  "Account information, such as name, email address, login method, and profile image.": {gu:"એકાઉન્ટ માહિતી, જેમ કે નામ, ઇમેઇલ સરનામું, લૉગિન પદ્ધતિ અને પ્રોફાઇલ છબી.",hi:"खाते की जानकारी, जैसे नाम, ईमेल पता, लॉगिन तरीका और प्रोफ़ाइल चित्र।",fr:"Informations du compte, comme le nom, l’adresse e-mail, la méthode de connexion et l’image de profil."},
  "Household workspace information, such as house names, members, grocery sections, products, store names, prices, quantities, shopping lists, messages, and activity records.": {gu:"ઘરેલુ વર્કસ્પેસ માહિતી, જેમ કે ઘરના નામ, સભ્યો, ગ્રોસરી વિભાગો, પ્રોડક્ટ્સ, સ્ટોરનાં નામ, ભાવ, માત્રા, ખરીદી યાદીઓ, સંદેશા અને પ્રવૃત્તિ રેકોર્ડ.",hi:"घरेलू कार्यक्षेत्र की जानकारी, जैसे घर के नाम, सदस्य, ग्रोसरी सेक्शन, उत्पाद, स्टोर नाम, कीमतें, मात्राएँ, खरीदारी सूचियाँ, संदेश और गतिविधि रिकॉर्ड।",fr:"Informations de l’espace du foyer, comme les noms de maison, membres, sections, produits, magasins, prix, quantités, listes, messages et activités."},
  "Receipt information uploaded by users, including receipt JPG/PNG images, extracted text, store names, item rows, discounts, taxes, totals, prices, and dates.": {gu:"વપરાશકર્તાઓ દ્વારા અપલોડ કરેલી રસીદ માહિતી, જેમાં JPG/PNG છબીઓ, કાઢેલ લખાણ, સ્ટોર નામ, વસ્તુની લાઇનો, ડિસ્કાઉન્ટ, ટેક્સ, કુલ, ભાવ અને તારીખો સામેલ છે.",hi:"उपयोगकर्ताओं द्वारा अपलोड की गई रसीद जानकारी, जिसमें JPG/PNG चित्र, निकाला गया टेक्स्ट, स्टोर नाम, आइटम पंक्तियाँ, छूट, कर, कुल, कीमतें और तारीखें शामिल हैं।",fr:"Informations de reçus téléversées, notamment images JPG/PNG, texte extrait, magasins, lignes d’articles, remises, taxes, totaux, prix et dates."},
  "Subscription and billing status from Stripe. Card numbers and full payment details are handled by Stripe and are not stored by Grocery House Manager.": {gu:"Stripe તરફથી સબ્સ્ક્રિપ્શન અને બિલિંગ સ્થિતિ. કાર્ડ નંબર અને સંપૂર્ણ ચુકવણી વિગતો Stripe સંભાળે છે અને Grocery House Manager તેને સંગ્રહતું નથી.",hi:"Stripe से सदस्यता और बिलिंग स्थिति। कार्ड नंबर और पूर्ण भुगतान विवरण Stripe संभालता है और Grocery House Manager उन्हें संग्रहीत नहीं करता।",fr:"État de l’abonnement et de la facturation fourni par Stripe. Les numéros de carte et données de paiement complètes sont gérés par Stripe et ne sont pas stockés par Grocery House Manager."},
  "Basic technical information required to keep the app secure and working, such as authentication tokens, request metadata, and local browser storage.": {gu:"એપને સુરક્ષિત અને કાર્યરત રાખવા માટે જરૂરી મૂળભૂત ટેકનિકલ માહિતી, જેમ કે ઓથેન્ટિકેશન ટોકન, રિક્વેસ્ટ મેટાડેટા અને લોકલ બ્રાઉઝર સ્ટોરેજ.",hi:"ऐप को सुरक्षित और कार्यरत रखने के लिए आवश्यक बुनियादी तकनीकी जानकारी, जैसे प्रमाणीकरण टोकन, अनुरोध मेटाडेटा और स्थानीय ब्राउज़र स्टोरेज।",fr:"Informations techniques de base nécessaires à la sécurité et au fonctionnement, comme les jetons d’authentification, métadonnées de requête et stockage local du navigateur."},
  "To provide shared grocery inventory, shopping lists, receipt tracking, and real-time household collaboration.": {gu:"શેર કરેલી ગ્રોસરી ઇન્વેન્ટરી, ખરીદી યાદીઓ, રસીદ ટ્રેકિંગ અને રિયલ-ટાઇમ ઘરેલુ સહકાર આપવા માટે.",hi:"साझा ग्रोसरी इन्वेंटरी, खरीदारी सूचियाँ, रसीद ट्रैकिंग और रीयल-टाइम घरेलू सहयोग देने के लिए।",fr:"Pour fournir l’inventaire partagé, les listes de courses, le suivi des reçus et la collaboration du foyer en temps réel."},
  "To show who performed actions inside a house, such as adding products or completing shopping lists.": {gu:"ઘરમાં કોણે શું કર્યું તે બતાવવા, જેમ કે પ્રોડક્ટ ઉમેરવું અથવા ખરીદી યાદી પૂર્ણ કરવી.",hi:"घर में किसने कौन-सी कार्रवाई की, जैसे उत्पाद जोड़ना या खरीदारी सूची पूरी करना, यह दिखाने के लिए।",fr:"Pour indiquer qui a effectué des actions dans une maison, comme ajouter des produits ou terminer une liste."},
  "To process subscriptions, validate coupon codes, manage plan limits, and keep account access accurate.": {gu:"સબ્સ્ક્રિપ્શન પ્રોસેસ કરવા, કૂપન કોડ ચકાસવા, પ્લાન મર્યાદાઓ મેનેજ કરવા અને એકાઉન્ટ ઍક્સેસ સાચું રાખવા માટે.",hi:"सदस्यता संसाधित करने, कूपन कोड सत्यापित करने, प्लान सीमाएँ प्रबंधित करने और खाते की पहुँच सही रखने के लिए।",fr:"Pour traiter les abonnements, valider les coupons, gérer les limites des forfaits et maintenir un accès correct au compte."},
  "To improve reliability, security, product quality, and user experience.": {gu:"વિશ્વસનીયતા, સુરક્ષા, પ્રોડક્ટ ગુણવત્તા અને વપરાશકર્તા અનુભવ સુધારવા માટે.",hi:"विश्वसनीयता, सुरक्षा, उत्पाद गुणवत्ता और उपयोगकर्ता अनुभव सुधारने के लिए।",fr:"Pour améliorer la fiabilité, la sécurité, la qualité du produit et l’expérience utilisateur."},
  "To respond to support, billing, cancellation, and account requests.": {gu:"મદદ, બિલિંગ, રદ અને એકાઉન્ટ સંબંધિત વિનંતીઓનો જવાબ આપવા માટે.",hi:"सहायता, बिलिंग, रद्दीकरण और खाते से जुड़ी अनुरोधों का उत्तर देने के लिए।",fr:"Pour répondre aux demandes d’assistance, de facturation, d’annulation et de compte."},
  "Payments and subscriptions are processed through Stripe. Stripe may collect payment details, billing information, tax information, and fraud-prevention information according to Stripe’s own privacy and security practices. Grocery House Manager stores only the subscription identifiers and status needed to provide paid features.": {gu:"ચુકવણી અને સબ્સ્ક્રિપ્શન Stripe દ્વારા પ્રોસેસ થાય છે. Stripe પોતાની ગોપનીયતા અને સુરક્ષા પદ્ધતિઓ મુજબ ચુકવણી, બિલિંગ, ટેક્સ અને છેતરપિંડી નિવારણ માહિતી એકત્રિત કરી શકે છે. Grocery House Manager ફક્ત ચૂકવેલ ફીચર્સ આપવા જરૂરી સબ્સ્ક્રિપ્શન ઓળખ અને સ્થિતિ સંગ્રહે છે.",hi:"भुगतान और सदस्यताएँ Stripe के माध्यम से संसाधित होती हैं। Stripe अपनी गोपनीयता और सुरक्षा नीतियों के अनुसार भुगतान, बिलिंग, कर और धोखाधड़ी-रोकथाम जानकारी एकत्र कर सकता है। Grocery House Manager केवल भुगतान सुविधाएँ देने के लिए आवश्यक सदस्यता पहचान और स्थिति रखता है।",fr:"Les paiements et abonnements sont traités par Stripe. Stripe peut recueillir des données de paiement, facturation, fiscalité et prévention de fraude selon ses propres pratiques. Grocery House Manager ne conserve que les identifiants et statuts nécessaires aux fonctions payantes."},
  "If you sign in with Google, the app uses the information Google provides for authentication, such as your email, name, and profile image. The app does not request access to your Gmail, Google Drive, or other Google data.": {gu:"જો તમે Google વડે સાઇન ઇન કરો, તો એપ ઓથેન્ટિકેશન માટે Google આપતી ઇમેઇલ, નામ અને પ્રોફાઇલ છબી જેવી માહિતી વાપરે છે. એપ તમારા Gmail, Google Drive અથવા અન્ય Google ડેટાની ઍક્સેસ માંગતી નથી.",hi:"यदि आप Google से साइन इन करते हैं, तो ऐप प्रमाणीकरण के लिए Google द्वारा दी गई ईमेल, नाम और प्रोफ़ाइल चित्र जैसी जानकारी उपयोग करता है। ऐप आपके Gmail, Google Drive या अन्य Google डेटा की पहुँच नहीं माँगता।",fr:"Si vous vous connectez avec Google, l’application utilise les informations fournies pour l’authentification, comme l’e-mail, le nom et l’image de profil. Elle ne demande pas l’accès à Gmail, Google Drive ou d’autres données Google."},
  "Receipt uploads may be processed to extract store names, receipt dates, product rows, quantities, prices, discounts, taxes, totals, payment-related labels, and raw extracted text. Scan results can be imperfect, so users should review details before saving them to inventory or price tracking.": {gu:"રસીદ અપલોડમાંથી સ્ટોર નામ, તારીખ, પ્રોડક્ટ લાઇનો, માત્રા, ભાવ, ડિસ્કાઉન્ટ, ટેક્સ, કુલ, ચુકવણી લેબલ અને કાચું કાઢેલ લખાણ મેળવવામાં આવી શકે છે. સ્કેન પરિણામોમાં ભૂલ હોઈ શકે છે, તેથી ઇન્વેન્ટરી અથવા ભાવ ટ્રેકિંગમાં સાચવતાં પહેલાં વિગતો તપાસો.",hi:"रसीद अपलोड से स्टोर नाम, तारीख, उत्पाद पंक्तियाँ, मात्रा, कीमत, छूट, कर, कुल, भुगतान लेबल और निकाला गया कच्चा टेक्स्ट प्राप्त किया जा सकता है। स्कैन परिणाम अपूर्ण हो सकते हैं, इसलिए इन्वेंटरी या कीमत ट्रैकिंग में सहेजने से पहले विवरण जाँचें।",fr:"Les reçus peuvent être traités pour extraire magasin, date, lignes produit, quantités, prix, remises, taxes, totaux, libellés de paiement et texte brut. Les résultats peuvent être imparfaits; vérifiez-les avant de les enregistrer."},
  "House members can see shared house data, including products, shopping lists, activity, and receipt-related information connected to that house. Only join houses with people you trust.": {gu:"ઘરના સભ્યો શેર કરેલો ડેટા જોઈ શકે છે, જેમાં પ્રોડક્ટ્સ, ખરીદી યાદીઓ, પ્રવૃત્તિ અને રસીદ સંબંધિત માહિતી સામેલ છે. ફક્ત વિશ્વાસપાત્ર લોકો સાથેના ઘરમાં જોડાઓ.",hi:"घर के सदस्य साझा डेटा देख सकते हैं, जिसमें उत्पाद, खरीदारी सूचियाँ, गतिविधि और उस घर से जुड़ी रसीद जानकारी शामिल है। केवल भरोसेमंद लोगों के घर से जुड़ें।",fr:"Les membres peuvent voir les données partagées de la maison, notamment produits, listes, activité et informations liées aux reçus. Ne rejoignez que des maisons de personnes de confiance."},
  "Account data is kept while the account is active and as needed to provide the service. Users can request deletion through the Profile page. Deletion may be blocked temporarily when the user owns shared houses with other members, so shared household data is not removed unexpectedly for others.": {gu:"એકાઉન્ટ સક્રિય હોય ત્યાં સુધી અને સેવા આપવા જરૂરી સમય સુધી ડેટા રાખવામાં આવે છે. વપરાશકર્તા પ્રોફાઇલ પેજથી ડિલીટ કરવાની વિનંતી કરી શકે છે. અન્ય સભ્યો સાથે શેર કરેલા ઘરના માલિક માટે ડિલીટ થોડીવાર રોકાઈ શકે છે જેથી બીજાનો શેર કરેલો ડેટા અચાનક દૂર ન થાય.",hi:"खाता सक्रिय रहने तक और सेवा देने के लिए आवश्यक समय तक डेटा रखा जाता है। उपयोगकर्ता प्रोफ़ाइल पेज से हटाने का अनुरोध कर सकते हैं। यदि उपयोगकर्ता अन्य सदस्यों वाले साझा घर का मालिक है तो हटाना अस्थायी रूप से रोका जा सकता है, ताकि दूसरों का साझा डेटा अचानक न मिटे।",fr:"Les données sont conservées tant que le compte est actif et selon les besoins du service. La suppression peut être demandée depuis Profil. Elle peut être temporairement bloquée si l’utilisateur possède une maison partagée, afin de ne pas supprimer les données des autres."},
  "For privacy or account questions, contact SupremDas Group support at": {gu:"ગોપનીયતા અથવા એકાઉન્ટ પ્રશ્નો માટે SupremDas Group સપોર્ટનો સંપર્ક કરો:",hi:"गोपनीयता या खाते के प्रश्नों के लिए SupremDas Group सहायता से संपर्क करें:",fr:"Pour toute question de confidentialité ou de compte, contactez l’assistance SupremDas Group à"},
  "These Terms apply to Grocery House Manager, a household grocery management SaaS product from SupremDas Group. By creating an account, joining a house, or using paid features, you agree to use the service responsibly and according to these Terms.": {gu:"આ શરતો SupremDas Group ના ઘરેલુ ગ્રોસરી મેનેજમેન્ટ SaaS પ્રોડક્ટ Grocery House Manager પર લાગુ પડે છે. એકાઉન્ટ બનાવી, ઘરમાં જોડાઈ અથવા ચૂકવેલ ફીચર્સ વાપરી તમે સેવા જવાબદારીપૂર્વક અને આ શરતો મુજબ વાપરવા સંમત થાઓ છો.",hi:"ये शर्तें SupremDas Group के घरेलू ग्रोसरी प्रबंधन SaaS उत्पाद Grocery House Manager पर लागू होती हैं। खाता बनाकर, घर से जुड़कर या भुगतान सुविधाएँ उपयोग करके आप सेवा का जिम्मेदारी से और इन शर्तों के अनुसार उपयोग करने पर सहमत होते हैं।",fr:"Ces conditions s’appliquent à Grocery House Manager, le SaaS de gestion des courses de SupremDas Group. En créant un compte, rejoignant une maison ou utilisant des fonctions payantes, vous acceptez d’utiliser le service de manière responsable selon ces conditions."},
  "Service purpose": {gu:"સેવાનો હેતુ",hi:"सेवा का उद्देश्य",fr:"Objet du service"},
  "Grocery House Manager helps households manage grocery inventory, shopping lists, receipts, store prices, members, and activity. It is intended for personal and household productivity use.": {gu:"Grocery House Manager ઘરોને ગ્રોસરી ઇન્વેન્ટરી, ખરીદી યાદીઓ, રસીદો, સ્ટોર ભાવ, સભ્યો અને પ્રવૃત્તિ મેનેજ કરવામાં મદદ કરે છે. તે વ્યક્તિગત અને ઘરેલુ ઉપયોગ માટે છે.",hi:"Grocery House Manager घरों को ग्रोसरी इन्वेंटरी, खरीदारी सूचियाँ, रसीदें, स्टोर कीमतें, सदस्य और गतिविधि प्रबंधित करने में मदद करता है। यह व्यक्तिगत और घरेलू उपयोग के लिए है।",fr:"Grocery House Manager aide les foyers à gérer inventaire, listes, reçus, prix magasins, membres et activité. Il est destiné à un usage personnel et domestique."},
  "You are responsible for keeping your account secure.": {gu:"તમારું એકાઉન્ટ સુરક્ષિત રાખવાની જવાબદારી તમારી છે.",hi:"अपने खाते को सुरक्षित रखने की जिम्मेदारी आपकी है।",fr:"Vous êtes responsable de la sécurité de votre compte."},
  "Use accurate account information and do not impersonate another person.": {gu:"એકાઉન્ટમાં સાચી માહિતી આપો અને અન્ય વ્યક્તિ બનીને વર્તશો નહીં.",hi:"खाते में सही जानकारी दें और किसी अन्य व्यक्ति का रूप न लें।",fr:"Utilisez des informations exactes et ne vous faites pas passer pour une autre personne."},
  "Only invite people you trust into a house because house members can view shared house data.": {gu:"ઘરમાં ફક્ત વિશ્વાસપાત્ર લોકોને આમંત્રિત કરો કારણ કે સભ્યો શેર કરેલો ડેટા જોઈ શકે છે.",hi:"घर में केवल भरोसेमंद लोगों को आमंत्रित करें क्योंकि सदस्य साझा घरेलू डेटा देख सकते हैं।",fr:"N’invitez que des personnes de confiance, car les membres peuvent voir les données partagées."},
  "Paid plans are billed through Stripe. House features are based on the house owner’s plan. A member’s own plan controls their own account benefits, owned-house capacity, and personal premium tools. Plan limits, features, and prices may change in the future, but active users will be informed when material changes affect them.": {gu:"ચૂકવેલ પ્લાન્સ Stripe દ્વારા બિલ થાય છે. ઘરના ફીચર્સ માલિકના પ્લાન પર આધારિત છે. સભ્યનો પોતાનો પ્લાન તેના એકાઉન્ટ લાભો, પોતાની માલિકીના ઘરની ક્ષમતા અને વ્યક્તિગત પ્રીમિયમ ટૂલ્સ નક્કી કરે છે. પ્લાન મર્યાદા, ફીચર્સ અને ભાવ ભવિષ્યમાં બદલાઈ શકે છે; મહત્વપૂર્ણ ફેરફાર થાય તો સક્રિય વપરાશકર્તાઓને જાણ કરવામાં આવશે.",hi:"भुगतान प्लान Stripe से बिल होते हैं। घर की सुविधाएँ घर के मालिक के प्लान पर आधारित हैं। सदस्य का अपना प्लान उसके खाते के लाभ, अपने घरों की क्षमता और व्यक्तिगत प्रीमियम टूल नियंत्रित करता है। प्लान सीमाएँ, सुविधाएँ और कीमतें भविष्य में बदल सकती हैं; महत्वपूर्ण बदलाव होने पर सक्रिय उपयोगकर्ताओं को बताया जाएगा।",fr:"Les forfaits payants sont facturés via Stripe. Les fonctions d’une maison dépendent du forfait de son propriétaire. Le forfait personnel d’un membre contrôle ses avantages, sa capacité de maisons possédées et ses outils premium. Les limites, fonctions et prix peuvent évoluer; les utilisateurs actifs seront informés des changements importants."},
  "Coupons, new-user offers, and promotional discounts are not stackable unless explicitly stated. A coupon must be active, valid, and eligible at the time of checkout. SupremDas Group may limit, expire, or revoke promotions if misuse or technical errors occur.": {gu:"સ્પષ્ટ રીતે જણાવવામાં ન આવે ત્યાં સુધી કૂપન, નવા વપરાશકર્તાની ઓફર અને પ્રમોશનલ ડિસ્કાઉન્ટ એકસાથે લાગુ કરી શકાતા નથી. ચેકઆઉટ સમયે કૂપન સક્રિય, માન્ય અને પાત્ર હોવો જોઈએ. ગેરવપરાશ અથવા ટેકનિકલ ભૂલ થાય તો SupremDas Group પ્રમોશન મર્યાદિત, સમાપ્ત અથવા રદ કરી શકે છે.",hi:"स्पष्ट रूप से न कहा गया हो तो कूपन, नए उपयोगकर्ता ऑफ़र और प्रचार छूट एक साथ लागू नहीं की जा सकतीं। चेकआउट के समय कूपन सक्रिय, मान्य और पात्र होना चाहिए। दुरुपयोग या तकनीकी त्रुटि होने पर SupremDas Group प्रचार सीमित, समाप्त या रद्द कर सकता है।",fr:"Sauf indication contraire, coupons, offres nouveaux utilisateurs et remises promotionnelles ne sont pas cumulables. Le coupon doit être actif, valide et admissible au paiement. SupremDas Group peut limiter, expirer ou révoquer une promotion en cas d’abus ou d’erreur technique."},
  "Smart Receipt Scan accepts supported receipt image formats such as JPG and PNG. Receipt scanning, price matching, product suggestions, and extracted receipt fields are provided for convenience. Results may be incomplete or inaccurate. Users must review store names, product quantities, discounts, taxes, totals, and inventory updates before relying on them.": {gu:"સ્માર્ટ રસીદ સ્કેન JPG અને PNG જેવી સપોર્ટેડ છબી ફોર્મેટ સ્વીકારે છે. સ્કેનિંગ, ભાવ મેચિંગ, પ્રોડક્ટ સૂચનો અને કાઢેલી રસીદ વિગતો સુવિધા માટે આપવામાં આવે છે. પરિણામ અધૂરું અથવા ખોટું હોઈ શકે છે. તેના પર આધાર રાખતાં પહેલાં સ્ટોર નામ, માત્રા, ડિસ્કાઉન્ટ, ટેક્સ, કુલ અને ઇન્વેન્ટરી અપડેટ તપાસો.",hi:"स्मार्ट रसीद स्कैन JPG और PNG जैसे समर्थित चित्र प्रारूप स्वीकार करता है। स्कैनिंग, कीमत मिलान, उत्पाद सुझाव और निकाले गए फ़ील्ड सुविधा के लिए हैं। परिणाम अधूरे या गलत हो सकते हैं। उन पर भरोसा करने से पहले स्टोर नाम, मात्रा, छूट, कर, कुल और इन्वेंटरी अपडेट जाँचें।",fr:"Le Scan intelligent accepte les formats pris en charge comme JPG et PNG. Le scan, la correspondance des prix, les suggestions produit et les champs extraits sont fournis à titre pratique. Les résultats peuvent être incomplets ou inexacts; vérifiez magasin, quantités, remises, taxes, totaux et mises à jour avant de vous y fier."},
  "Do not upload illegal, harmful, abusive, or unrelated content.": {gu:"ગેરકાયદેસર, હાનિકારક, અપમાનજનક અથવા અસંબંધિત સામગ્રી અપલોડ કરશો નહીં.",hi:"गैरकानूनी, हानिकारक, अपमानजनक या असंबंधित सामग्री अपलोड न करें।",fr:"Ne téléversez pas de contenu illégal, nuisible, abusif ou sans rapport."},
  "Do not attempt to break, reverse engineer, overload, or misuse the service.": {gu:"સેવાને તોડવાનો, રિવર્સ એન્જિનિયર કરવાનો, ઓવરલોડ કરવાનો અથવા ગેરવપરાશ કરવાનો પ્રયાસ કરશો નહીં.",hi:"सेवा को तोड़ने, रिवर्स इंजीनियर करने, ओवरलोड करने या दुरुपयोग करने का प्रयास न करें।",fr:"N’essayez pas de casser, rétroconcevoir, surcharger ou détourner le service."},
  "Do not use the service to violate privacy, payment, or intellectual-property rights.": {gu:"ગોપનીયતા, ચુકવણી અથવા બૌદ્ધિક સંપત્તિના અધિકારોનો ભંગ કરવા સેવા વાપરશો નહીં.",hi:"गोपनीयता, भुगतान या बौद्धिक संपदा अधिकारों का उल्लंघन करने के लिए सेवा का उपयोग न करें।",fr:"N’utilisez pas le service pour violer des droits de confidentialité, paiement ou propriété intellectuelle."},
  "SupremDas Group aims to provide a reliable service, but the app may sometimes be unavailable due to maintenance, hosting issues, third-party outages, or unexpected technical problems.": {gu:"SupremDas Group વિશ્વસનીય સેવા આપવા પ્રયત્ન કરે છે, પરંતુ જાળવણી, હોસ્ટિંગ સમસ્યા, તૃતીય-પક્ષ આઉટેજ અથવા અણધારી ટેકનિકલ સમસ્યાને કારણે એપ ક્યારેક ઉપલબ્ધ ન હોઈ શકે.",hi:"SupremDas Group विश्वसनीय सेवा देने का प्रयास करता है, लेकिन रखरखाव, होस्टिंग समस्या, तृतीय-पक्ष आउटेज या अप्रत्याशित तकनीकी समस्या के कारण ऐप कभी-कभी उपलब्ध नहीं हो सकता।",fr:"SupremDas Group vise un service fiable, mais l’application peut parfois être indisponible pour maintenance, problème d’hébergement, panne d’un tiers ou incident technique imprévu."},
  "Users can manage or cancel subscriptions from the Profile page. Cancellation normally takes effect at the end of the current billing period, and paid access may continue until that period ends.": {gu:"વપરાશકર્તાઓ પ્રોફાઇલ પેજથી સબ્સ્ક્રિપ્શન મેનેજ અથવા રદ કરી શકે છે. રદ સામાન્ય રીતે હાલના બિલિંગ પિરિયડના અંતે અમલમાં આવે છે અને ત્યાં સુધી ચૂકવેલ ઍક્સેસ ચાલુ રહી શકે છે.",hi:"उपयोगकर्ता प्रोफ़ाइल पेज से सदस्यता प्रबंधित या रद्द कर सकते हैं। रद्दीकरण सामान्यतः वर्तमान बिलिंग अवधि के अंत में प्रभावी होता है और तब तक भुगतान पहुँच जारी रह सकती है।",fr:"Les utilisateurs peuvent gérer ou annuler l’abonnement depuis Profil. L’annulation prend normalement effet à la fin de la période de facturation et l’accès payant peut continuer jusque-là."},
  "For support or billing questions, contact": {gu:"સપોર્ટ અથવા બિલિંગ પ્રશ્નો માટે સંપર્ક કરો:",hi:"सहायता या बिलिंग प्रश्नों के लिए संपर्क करें:",fr:"Pour les questions d’assistance ou de facturation, contactez"},
  "Grocery House Manager subscriptions are billed monthly through Stripe. Users can manage billing or cancel from the Profile page.": {gu:"Grocery House Manager સબ્સ્ક્રિપ્શન Stripe દ્વારા માસિક બિલ થાય છે. વપરાશકર્તા પ્રોફાઇલ પેજથી બિલિંગ મેનેજ અથવા રદ કરી શકે છે.",hi:"Grocery House Manager सदस्यताएँ Stripe के माध्यम से मासिक बिल होती हैं। उपयोगकर्ता प्रोफ़ाइल पेज से बिलिंग प्रबंधित या रद्द कर सकते हैं।",fr:"Les abonnements Grocery House Manager sont facturés mensuellement via Stripe. Les utilisateurs peuvent gérer la facturation ou annuler depuis Profil."},
  "When a subscription is cancelled, cancellation is normally scheduled for the end of the current billing period. You may continue using paid features until that billing period ends. After the period ends, your account returns to the appropriate free access level.": {gu:"સબ્સ્ક્રિપ્શન રદ થાય ત્યારે તે સામાન્ય રીતે હાલના બિલિંગ પિરિયડના અંત માટે નક્કી થાય છે. પિરિયડ પૂરો થાય ત્યાં સુધી ચૂકવેલ ફીચર્સ વાપરી શકો છો. પછી એકાઉન્ટ યોગ્ય મફત ઍક્સેસ સ્તરે પાછું જાય છે.",hi:"सदस्यता रद्द होने पर रद्दीकरण सामान्यतः वर्तमान बिलिंग अवधि के अंत के लिए तय होता है। अवधि समाप्त होने तक भुगतान सुविधाएँ उपयोग कर सकते हैं। उसके बाद खाता उचित मुफ़्त पहुँच स्तर पर लौटता है।",fr:"Lorsqu’un abonnement est annulé, l’annulation est normalement prévue à la fin de la période en cours. Les fonctions payantes restent accessibles jusque-là, puis le compte revient au niveau gratuit approprié."},
  "Because plans are monthly and low-cost, payments are generally non-refundable after a billing period begins, except where required by law or where SupremDas Group determines that a billing or technical issue justifies a refund.": {gu:"પ્લાન્સ માસિક અને ઓછા ખર્ચના હોવાથી, બિલિંગ પિરિયડ શરૂ થયા પછી ચુકવણી સામાન્ય રીતે પરતપાત્ર નથી, સિવાય કે કાયદો જરૂરી કરે અથવા SupremDas Group બિલિંગ/ટેકનિકલ સમસ્યાને કારણે રિફંડ યોગ્ય માને.",hi:"प्लान मासिक और कम लागत वाले हैं, इसलिए बिलिंग अवधि शुरू होने के बाद भुगतान सामान्यतः वापस नहीं होता, सिवाय जहाँ कानून आवश्यक करे या SupremDas Group किसी बिलिंग/तकनीकी समस्या के कारण रिफंड उचित माने।",fr:"Les forfaits étant mensuels et peu coûteux, les paiements sont généralement non remboursables après le début d’une période, sauf obligation légale ou problème de facturation/technique justifiant un remboursement selon SupremDas Group."},
  "If you believe you were charged incorrectly, contact support within 7 days of the charge and include your account email, plan name, and a short explanation. Do not include full card numbers or sensitive payment details in support messages.": {gu:"જો તમને લાગે કે ખોટી રકમ વસૂલાઈ છે, તો ચાર્જ પછી 7 દિવસમાં સપોર્ટનો સંપર્ક કરો અને એકાઉન્ટ ઇમેઇલ, પ્લાન નામ અને ટૂંકું વર્ણન આપો. સંપૂર્ણ કાર્ડ નંબર અથવા સંવેદનશીલ ચુકવણી વિગતો ન મોકલો.",hi:"यदि आपको लगता है कि गलत शुल्क लिया गया है, तो शुल्क के 7 दिनों के भीतर सहायता से संपर्क करें और खाते की ईमेल, प्लान नाम तथा संक्षिप्त विवरण दें। पूरा कार्ड नंबर या संवेदनशील भुगतान जानकारी न भेजें।",fr:"Si vous pensez avoir été facturé à tort, contactez l’assistance dans les 7 jours avec l’e-mail du compte, le nom du forfait et une brève explication. N’envoyez jamais le numéro complet de carte ni des données sensibles."},
  "Discounts, coupons, and new-user offers apply only when they are valid at checkout. Promotions cannot be stacked unless clearly stated. If a discount expires, future renewals may charge the regular plan price.": {gu:"ડિસ્કાઉન્ટ, કૂપન અને નવા વપરાશકર્તાની ઓફર ચેકઆઉટ સમયે માન્ય હોય ત્યારે જ લાગુ પડે છે. સ્પષ્ટ જણાવવામાં ન આવે ત્યાં સુધી પ્રમોશન એકસાથે લાગુ નથી થતા. ડિસ્કાઉન્ટ સમાપ્ત થાય તો આગામી રિન્યૂઅલમાં નિયમિત પ્લાન ભાવ લાગી શકે છે.",hi:"छूट, कूपन और नए उपयोगकर्ता ऑफ़र केवल चेकआउट पर मान्य होने पर लागू होते हैं। स्पष्ट रूप से न कहा हो तो प्रचार एक साथ लागू नहीं किए जा सकते। छूट समाप्त होने पर भविष्य के नवीनीकरण में नियमित प्लान मूल्य लग सकता है।",fr:"Les remises, coupons et offres nouveaux utilisateurs ne s’appliquent que s’ils sont valides au paiement. Les promotions ne se cumulent pas sauf mention claire. Après expiration d’une remise, les renouvellements peuvent être facturés au prix normal."},
  "For billing help, contact": {gu:"બિલિંગ મદદ માટે સંપર્ક કરો:",hi:"बिलिंग सहायता के लिए संपर्क करें:",fr:"Pour l’aide à la facturation, contactez"},
  "SMART MEAL PLANNER": {gu:"સ્માર્ટ મીલ પ્લાનર",hi:"स्मार्ट मील प्लानर",fr:"PLANIFICATEUR DE REPAS INTELLIGENT"},
  "STEP BY STEP": {gu:"પગલું દર પગલું",hi:"चरण दर चरण",fr:"ÉTAPE PAR ÉTAPE"},
  "CUSTOM RECIPE": {gu:"કસ્ટમ રેસીપી",hi:"कस्टम रेसिपी",fr:"RECETTE PERSONNALISÉE"},
  "Create a private dish card, set its base recipe for 4 people, then scale it to any serving count.": {gu:"ખાનગી વાનગી કાર્ડ બનાવો, 4 લોકો માટે મૂળ રેસીપી નક્કી કરો અને પછી કોઈપણ સર્વિંગ સંખ્યા પ્રમાણે તેને સ્કેલ કરો.",hi:"एक निजी डिश कार्ड बनाएं, 4 लोगों के लिए मूल रेसिपी तय करें और फिर किसी भी सर्विंग संख्या के अनुसार उसे बदलें।",fr:"Créez une fiche privée, définissez la recette de base pour 4 personnes puis adaptez-la à n’importe quel nombre de portions."},
  "Could not add ingredients.": {gu:"સામગ્રી ઉમેરી શકાઈ નથી.",hi:"सामग्री नहीं जोड़ी जा सकी।",fr:"Impossible d’ajouter les ingrédients."},
  'Available flyer stores for this postal code': {gu:'આ પોસ્ટલ કોડ માટે ઉપલબ્ધ ફ્લાયર સ્ટોર્સ',hi:'इस पोस्टल कोड के लिए उपलब्ध फ्लायर स्टोर',fr:'Magasins avec circulaires disponibles pour ce code postal'},
  'Filters are loaded from the flyer provider for this postal code, so only valid local merchants are shown. Leave all unselected to use the provider’s local grocery set.': {gu:'આ પોસ્ટલ કોડ માટે ફિલ્ટર સીધા ફ્લાયર પ્રોવાઇડર પાસેથી આવે છે, તેથી ફક્ત માન્ય સ્થાનિક સ્ટોર્સ જ દેખાય છે. બધા અનપસંદ રાખો તો પ્રોવાઇડરના સ્થાનિક ગ્રોસરી સ્ટોર્સ વપરાશે.',hi:'इस पोस्टल कोड के लिए फ़िल्टर सीधे फ्लायर प्रदाता से लोड होते हैं, इसलिए केवल वैध स्थानीय स्टोर दिखते हैं। सभी को अनचुना छोड़ें तो प्रदाता का स्थानीय ग्रोसरी सेट उपयोग होगा।',fr:'Les filtres proviennent du fournisseur de circulaires pour ce code postal; seuls les commerces locaux valides sont affichés. Ne sélectionnez rien pour utiliser l’ensemble local du fournisseur.'},
  'Refresh local stores': {gu:'સ્થાનિક સ્ટોર્સ રિફ્રેશ કરો',hi:'स्थानीय स्टोर रीफ़्रेश करें',fr:'Actualiser les magasins locaux'},
  'Loading local stores…': {gu:'સ્થાનિક સ્ટોર્સ લોડ થઈ રહ્યા છે…',hi:'स्थानीय स्टोर लोड हो रहे हैं…',fr:'Chargement des magasins locaux…'},
  'All local stores': {gu:'બધા સ્થાનિક સ્ટોર્સ',hi:'सभी स्थानीय स्टोर',fr:'Tous les magasins locaux'},
  'Clear store filters': {gu:'સ્ટોર ફિલ્ટર સાફ કરો',hi:'स्टोर फ़िल्टर साफ़ करें',fr:'Effacer les filtres magasin'},
  'Select up to 12 flyer stores at a time to control provider usage. Clear a store before adding another.': {gu:'પ્રોવાઇડર વપરાશ નિયંત્રિત રાખવા એક સમયે વધુમાં વધુ 12 ફ્લાયર સ્ટોર પસંદ કરો. નવો ઉમેરતા પહેલાં એક સ્ટોર દૂર કરો.',hi:'प्रदाता उपयोग नियंत्रित रखने के लिए एक समय में अधिकतम 12 फ्लायर स्टोर चुनें। दूसरा जोड़ने से पहले एक स्टोर हटाएँ।',fr:'Sélectionnez jusqu’à 12 magasins de circulaires à la fois afin de maîtriser l’utilisation du fournisseur. Retirez un magasin avant d’en ajouter un autre.'},
  'Enter a complete postal code to load the stores that actually have flyers in your area.': {gu:'તમારા વિસ્તારમાં ખરેખર ફ્લાયર ધરાવતા સ્ટોર્સ લોડ કરવા સંપૂર્ણ પોસ્ટલ કોડ દાખલ કરો.',hi:'आपके क्षेत्र में वास्तव में फ्लायर वाले स्टोर लोड करने के लिए पूरा पोस्टल कोड दर्ज करें।',fr:'Entrez un code postal complet pour charger les magasins qui ont réellement des circulaires dans votre secteur.'},
  'Click any deal to open details, price, flyer area, and the nearest store location when available.': {gu:'વિગતો, ભાવ, ફ્લાયર વિસ્તાર અને ઉપલબ્ધ હોય ત્યારે નજીકનું સ્ટોર સ્થાન જોવા કોઈપણ ડીલ પર ક્લિક કરો.',hi:'विवरण, कीमत, फ्लायर क्षेत्र और उपलब्ध होने पर निकटतम स्टोर स्थान देखने के लिए किसी भी ऑफ़र पर क्लिक करें।',fr:'Cliquez sur une offre pour ouvrir les détails, le prix, la zone de circulaire et le magasin le plus proche lorsqu’il est disponible.'},
  'View deal →': {gu:'ડીલ જુઓ →',hi:'ऑफ़र देखें →',fr:'Voir l’offre →'},
  'Flyer deal details': {gu:'ફ્લાયર ડીલ વિગતો',hi:'फ्लायर ऑफ़र विवरण',fr:'Détails de l’offre de circulaire'},
  'Validity': {gu:'માન્યતા',hi:'वैधता',fr:'Validité'},
  'See flyer': {gu:'ફ્લાયર જુઓ',hi:'फ्लायर देखें',fr:'Voir la circulaire'},
  'Flyer area': {gu:'ફ્લાયર વિસ્તાર',hi:'फ्लायर क्षेत्र',fr:'Zone de circulaire'},
  'Requested quantity': {gu:'જરૂરી માત્રા',hi:'आवश्यक मात्रा',fr:'Quantité demandée'},
  'Nearest store location': {gu:'નજીકનું સ્ટોર સ્થાન',hi:'निकटतम स्टोर स्थान',fr:'Magasin le plus proche'},
  'Open in Maps': {gu:'Maps માં ખોલો',hi:'Maps में खोलें',fr:'Ouvrir dans Maps'},
  'Open source deal': {gu:'મૂળ ડીલ ખોલો',hi:'मूल ऑफ़र खोलें',fr:'Ouvrir l’offre source'},
  'Exact branch address is not supplied by the flyer provider. Use Maps to find the nearest location for this flyer area.': {gu:'ફ્લાયર પ્રોવાઇડર ચોક્કસ બ્રાન્ચનું સરનામું આપતું નથી. આ ફ્લાયર વિસ્તાર માટે નજીકનું સ્થાન શોધવા Maps વાપરો.',hi:'फ्लायर प्रदाता सटीक शाखा का पता नहीं देता। इस फ्लायर क्षेत्र के लिए निकटतम स्थान खोजने हेतु Maps का उपयोग करें।',fr:'Le fournisseur de circulaires ne donne pas l’adresse exacte de la succursale. Utilisez Maps pour trouver le magasin le plus proche dans cette zone.'},
  'Flyer availability is tied to the postal-code area. The nearest store shown above is a convenience lookup and may not be the branch that published the flyer.': {gu:'ફ્લાયરની ઉપલબ્ધતા પોસ્ટલ કોડ વિસ્તાર સાથે જોડાયેલી છે. ઉપર બતાવેલું નજીકનું સ્ટોર સુવિધા માટે શોધાયેલ છે અને ફ્લાયર પ્રકાશિત કરનાર ચોક્કસ બ્રાન્ચ ન પણ હોય.',hi:'फ्लायर उपलब्धता पोस्टल-कोड क्षेत्र से जुड़ी है। ऊपर दिखाया निकटतम स्टोर सुविधा के लिए खोजा गया है और यह फ्लायर प्रकाशित करने वाली सटीक शाखा नहीं भी हो सकती।',fr:'La disponibilité de la circulaire dépend de la zone du code postal. Le magasin le plus proche affiché est une recherche pratique et peut ne pas être la succursale ayant publié la circulaire.'},
};

// Dynamic messages from APIs and older components. These preserve variables such as a store,
// product, date, plan or count while translating the surrounding UI wording.
const dynamicRules: Array<[RegExp, (m: RegExpMatchArray, l: Exclude<SiteLanguage,'en'>) => string]> = [
  [/^Updated (.+)$/i, (m,l)=> l==='hi'?`अपडेट ${m[1]}`:l==='gu'?`અપડેટ ${m[1]}`:`Mis à jour ${m[1]}`],
  [/^Valid until (.+)$/i, (m,l)=> l==='hi'?`${m[1]} तक मान्य`:l==='gu'?`${m[1]} સુધી માન્ય`:`Valide jusqu’au ${m[1]}`],
  [/^Valid (.+) – (.+)$/i, (m,l)=> l==='hi'?`${m[1]} से ${m[2]} तक मान्य`:l==='gu'?`${m[1]} થી ${m[2]} સુધી માન્ય`:`Valide du ${m[1]} au ${m[2]}`],
  [/^Step (\d+)$/i, (m,l)=> l==='hi'?`चरण ${m[1]}`:l==='gu'?`પગલું ${m[1]}`:`Étape ${m[1]}`],
  [/^(\d+) items?$/i, (m,l)=> l==='hi'?`${m[1]} वस्तुएँ`:l==='gu'?`${m[1]} વસ્તુઓ`:`${m[1]} articles`],
  [/^(\d+) products?$/i, (m,l)=> l==='hi'?`${m[1]} उत्पाद`:l==='gu'?`${m[1]} પ્રોડક્ટ્સ`:`${m[1]} produits`],
  [/^Missing: (.+)$/i, (m,l)=> l==='hi'?`नहीं मिला: ${m[1]}`:l==='gu'?`ઓછું/ગુમ: ${m[1]}`:`Manquant : ${m[1]}`],
  [/^Near (.+)$/i, (m,l)=> l==='hi'?`${m[1]} के पास`:l==='gu'?`${m[1]} નજીક`:`Près de ${m[1]}`],
  [/^Cache valid until (.+)$/i, (m,l)=> l==='hi'?`कैश ${m[1]} तक मान्य`:l==='gu'?`કૅશ ${m[1]} સુધી માન્ય`:`Cache valide jusqu’au ${m[1]}`],
  [/^Show all deals \((\d+)\)$/i, (m,l)=> l==='hi'?`सभी ऑफ़र दिखाएं (${m[1]})`:l==='gu'?`બધી ડીલ બતાવો (${m[1]})`:`Afficher toutes les offres (${m[1]})`],
  [/^Show fewer$/i, (_m,l)=> l==='hi'?`कम दिखाएं`:l==='gu'?`ઓછું બતાવો`:`Afficher moins`],
  [/^(\d+) deals? • (\d+) flyers?$/i, (m,l)=> l==='hi'?`${m[1]} ऑफ़र • ${m[2]} फ्लायर`:l==='gu'?`${m[1]} ડીલ • ${m[2]} ફ્લાયર`:`${m[1]} offres • ${m[2]} circulaires`],
  [/^(\d+) deals?$/i, (m,l)=> l==='hi'?`${m[1]} ऑफ़र`:l==='gu'?`${m[1]} ડીલ`:`${m[1]} offres`],
  [/^(\d+) flyer stores are available for this postal code\. Select any stores below, or leave all unselected to use the provider's local grocery set\.$/i, (m,l)=> l==='hi'?`${m[1]} फ्लायर स्टोर इस पोस्टल कोड के लिए उपलब्ध हैं। नीचे कोई भी स्टोर चुनें, या प्रदाता के स्थानीय ग्रोसरी सेट के लिए सभी को अनचुना छोड़ें।`:l==='gu'?`${m[1]} ફ્લાયર સ્ટોર્સ આ પોસ્ટલ કોડ માટે ઉપલબ્ધ છે. નીચે કોઈપણ સ્ટોર પસંદ કરો અથવા પ્રોવાઇડરના સ્થાનિક ગ્રોસરી સેટ માટે બધા અનપસંદ રાખો.`:`${m[1]} magasins avec circulaires sont disponibles pour ce code postal. Sélectionnez les magasins souhaités ou ne sélectionnez rien pour utiliser l’ensemble local du fournisseur.`],
  [/^(\d+) stores selected$/i, (m,l)=> l==='hi'?`${m[1]} स्टोर चुने गए`:l==='gu'?`${m[1]} સ્ટોર્સ પસંદ`:`${m[1]} magasins sélectionnés`],
  [/^(\d+) stores selected • max 12$/i, (m,l)=> l==='hi'?`${m[1]} स्टोर चुने गए • अधिकतम 12`:l==='gu'?`${m[1]} સ્ટોર્સ પસંદ • મહત્તમ 12`:`${m[1]} magasins sélectionnés • max. 12`],
  [/^All local stores • select up to 12$/i, (_m,l)=> l==='hi'?`सभी स्थानीय स्टोर • अधिकतम 12 चुनें`:l==='gu'?`બધા સ્થાનિક સ્ટોર્સ • વધુમાં વધુ 12 પસંદ કરો`:`Tous les magasins locaux • jusqu’à 12`],
  [/^Flyer area:\s*(.+)$/i, (m,l)=> l==='hi'?`फ्लायर क्षेत्र: ${m[1]}`:l==='gu'?`ફ્લાયર વિસ્તાર: ${m[1]}`:`Zone de circulaire : ${m[1]}`],
  [/^Requested quantity:\s*(.+)$/i, (m,l)=> l==='hi'?`आवश्यक मात्रा: ${m[1]}`:l==='gu'?`જરૂરી માત્રા: ${m[1]}`:`Quantité demandée : ${m[1]}`],
  [/^was \$(.+)$/i, (m,l)=> l==='hi'?`पहले $${m[1]}`:l==='gu'?`પહેલાં $${m[1]}`:`avant $${m[1]}`],
  [/^Showing (\d+) active weekly flyer deals(?: for ‘(.+)’)? across (\d+) local merchants from (.+)\. Flyer prices are promotional prices valid only for the displayed dates\.$/i,
    (m,l)=> l==='hi'?`${m[1]} सक्रिय साप्ताहिक फ्लायर ऑफ़र${m[2]?` ‘${m[2]}’ के लिए`:''}, ${m[3]} स्थानीय स्टोर से दिखाए जा रहे हैं (${m[4]})। फ्लायर कीमतें केवल दिखाई गई तारीखों के लिए मान्य प्रचार कीमतें हैं।`:l==='gu'?`${m[1]} સક્રિય સાપ્તાહિક ફ્લાયર ડીલ${m[2]?` ‘${m[2]}’ માટે`:''}, ${m[3]} સ્થાનિક સ્ટોરમાંથી બતાવવામાં આવી રહી છે (${m[4]}). ફ્લાયર ભાવ ફક્ત બતાવેલી તારીખો માટે માન્ય પ્રમોશનલ ભાવ છે.`:`${m[1]} offres actives${m[2]?` pour « ${m[2]} »`:''} provenant de ${m[3]} commerçants locaux (${m[4]}). Les prix des circulaires sont promotionnels et valables uniquement aux dates indiquées.`],
];

const starterPhrases: Record<Exclude<SiteLanguage,'en'>, Array<[string,string]>> = {
  hi: [
    ['Loading ', 'लोड हो रहा है '], ['Create ', 'बनाएं '], ['Add ', 'जोड़ें '], ['Open ', 'खोलें '], ['View ', 'देखें '], ['Choose ', 'चुनें '], ['Find ', 'खोजें '], ['Search ', 'खोजें '], ['Refresh ', 'रीफ़्रेश '], ['Use ', 'उपयोग करें '], ['Your ', 'आपका '], ['No ', 'कोई नहीं: '], ['Current ', 'वर्तमान '], ['Best ', 'सर्वोत्तम '], ['Weekly ', 'साप्ताहिक '], ['Receipt ', 'रसीद '], ['Shopping ', 'खरीदारी '], ['Inventory ', 'इन्वेंटरी '], ['Plan ', 'प्लान '], ['House ', 'घर '],
  ],
  gu: [
    ['Loading ', 'લોડ થઈ રહ્યું છે '], ['Create ', 'બનાવો '], ['Add ', 'ઉમેરો '], ['Open ', 'ખોલો '], ['View ', 'જુઓ '], ['Choose ', 'પસંદ કરો '], ['Find ', 'શોધો '], ['Search ', 'શોધો '], ['Refresh ', 'રિફ્રેશ '], ['Use ', 'વાપરો '], ['Your ', 'તમારું '], ['No ', 'કોઈ નથી: '], ['Current ', 'હાલનું '], ['Best ', 'શ્રેષ્ઠ '], ['Weekly ', 'સાપ્તાહિક '], ['Receipt ', 'રસીદ '], ['Shopping ', 'ખરીદી '], ['Inventory ', 'ઇન્વેન્ટરી '], ['Plan ', 'પ્લાન '], ['House ', 'ઘર '],
  ],
  fr: [
    ['Loading ', 'Chargement '], ['Create ', 'Créer '], ['Add ', 'Ajouter '], ['Open ', 'Ouvrir '], ['View ', 'Voir '], ['Choose ', 'Choisir '], ['Find ', 'Trouver '], ['Search ', 'Rechercher '], ['Refresh ', 'Actualiser '], ['Use ', 'Utiliser '], ['Your ', 'Votre '], ['No ', 'Aucun '], ['Current ', 'Actuel '], ['Best ', 'Meilleur '], ['Weekly ', 'Hebdomadaire '], ['Receipt ', 'Reçu '], ['Shopping ', 'Courses '], ['Inventory ', 'Inventaire '], ['Plan ', 'Forfait '], ['House ', 'Maison '],
  ],
};

export function translateUiText(input: string, language: SiteLanguage): string {
  if (language === 'en' || !input) return input;
  const trimmed = input.trim();
  const mapped = exact[trimmed]?.[language];
  if (mapped) return input.replace(trimmed, mapped);
  for (const [rx, fn] of dynamicRules) {
    const match = trimmed.match(rx);
    if (match) return input.replace(trimmed, fn(match, language));
  }
  // Conservative fallback for legacy dynamic labels. Only translate strings that clearly start
  // like UI copy; this avoids changing house names, emails, custom notes and other user data.
  const rules = starterPhrases[language];
  for (const [from,to] of rules) {
    if (trimmed.startsWith(from) && trimmed.length > from.length + 1) {
      return input.replace(trimmed, trimmed.replace(from,to));
    }
  }
  return input;
}

export function languageDisplayName(value: SiteLanguage, current: SiteLanguage): string {
  const names: Record<SiteLanguage, Record<SiteLanguage,string>> = {
    en:{en:'English',gu:'Gujarati',hi:'Hindi',fr:'French'},
    gu:{en:'અંગ્રેજી',gu:'ગુજરાતી',hi:'હિન્દી',fr:'ફ્રેન્ચ'},
    hi:{en:'अंग्रेज़ी',gu:'गुजराती',hi:'हिन्दी',fr:'फ़्रेंच'},
    fr:{en:'Anglais',gu:'Gujarati',hi:'Hindi',fr:'Français'},
  };
  return names[current][value];
}
