import type { SiteLanguage } from './localizationCatalog';

type Triple = {gu:string; hi:string; fr:string};

// Culinary phrase replacements run before individual words. This keeps the detailed English
// recipe catalogue maintainable while producing fully localized instructions for every recipe.
const phrases: Record<string, Triple> = {
  'whole wheat flour':{gu:'ઘઉંનો લોટ',hi:'गेहूं का आटा',fr:'farine de blé complet'},
  'all purpose flour':{gu:'મેંદો',hi:'मैदा',fr:'farine tout usage'},
  'rice flour':{gu:'ચોખાનો લોટ',hi:'चावल का आटा',fr:'farine de riz'},
  'chana dal':{gu:'ચણાની દાળ',hi:'चना दाल',fr:'chana dal'},
  'tuvar dal':{gu:'તુવેર દાળ',hi:'तुअर दाल',fr:'toor dal'},
  'moong dal':{gu:'મગની દાળ',hi:'मूंग दाल',fr:'moong dal'},
  'bottle gourd':{gu:'દૂધી',hi:'लौकी',fr:'courge bouteille'},
  'green chilli':{gu:'લીલું મરચું',hi:'हरी मिर्च',fr:'piment vert'},
  'green chillies':{gu:'લીલા મરચાં',hi:'हरी मिर्चें',fr:'piments verts'},
  'medium-high heat':{gu:'મધ્યમથી ઊંચી આંચ',hi:'मध्यम-तेज़ आँच',fr:'feu moyen-vif'},
  'medium-low heat':{gu:'મધ્યમથી ધીમી આંચ',hi:'मध्यम-धीमी आँच',fr:'feu moyen-doux'},
  'medium heat':{gu:'મધ્યમ આંચ',hi:'मध्यम आँच',fr:'feu moyen'},
  'low heat':{gu:'ધીમી આંચ',hi:'धीमी आँच',fr:'feu doux'},
  'high heat':{gu:'ઊંચી આંચ',hi:'तेज़ आँच',fr:'feu vif'},
  'the heat':{gu:'આંચ',hi:'आँच',fr:'le feu'},
  'hot tawa':{gu:'ગરમ તવો',hi:'गरम तवा',fr:'tawa chaud'},
  'heavy-bottomed pan':{gu:'જાડા તળિયાવાળું પૅન',hi:'भारी तले वाला पैन',fr:'casserole à fond épais'},
  'pressure cooker':{gu:'પ્રેશર કુકર',hi:'प्रेशर कुकर',fr:'autocuiseur'},
  'pressure-cook':{gu:'પ્રેશર કુકરમાં રાંધો',hi:'प्रेशर कुकर में पकाएँ',fr:'cuire sous pression'},
  'pressure cook':{gu:'પ્રેશર કુકરમાં રાંધો',hi:'प्रेशर कुकर में पकाएँ',fr:'cuire sous pression'},
  'direct flame':{gu:'સીધી જ્યોત',hi:'सीधी आँच',fr:'flamme directe'},
  'golden-brown':{gu:'સોનેરી-ભૂરું',hi:'सुनहरा-भूरा',fr:'doré'},
  'light brown':{gu:'હળવો ભૂરો',hi:'हल्का भूरा',fr:'brun clair'},
  'raw taste':{gu:'કાચો સ્વાદ',hi:'कच्चा स्वाद',fr:'goût cru'},
  'raw flour':{gu:'કાચો લોટ',hi:'कच्चा आटा',fr:'farine crue'},
  'room temperature':{gu:'રૂમ તાપમાન',hi:'कमरे का तापमान',fr:'température ambiante'},
  'little by little':{gu:'થોડું થોડું કરીને',hi:'थोड़ा-थोड़ा करके',fr:'petit à petit'},
  'a little at a time':{gu:'થોડું થોડું કરીને',hi:'थोड़ा-थोड़ा करके',fr:'petit à petit'},
  'at a time':{gu:'એક વખતમાં',hi:'एक बार में',fr:'à la fois'},
  'if needed':{gu:'જરૂર હોય તો',hi:'यदि ज़रूरत हो',fr:'si nécessaire'},
  'if desired':{gu:'ઇચ્છા હોય તો',hi:'यदि चाहें',fr:'si désiré'},
  'if using':{gu:'વાપરતા હો તો',hi:'यदि उपयोग कर रहे हों',fr:'si utilisé'},
  'as needed':{gu:'જરૂર મુજબ',hi:'आवश्यकतानुसार',fr:'au besoin'},
  'according to taste':{gu:'સ્વાદ મુજબ',hi:'स्वादानुसार',fr:'selon le goût'},
  'until tender':{gu:'નરમ થાય ત્યાં સુધી',hi:'नरम होने तक',fr:'jusqu’à tendreté'},
  'until smooth':{gu:'મસૃણ થાય ત્યાં સુધી',hi:'चिकना होने तक',fr:'jusqu’à consistance lisse'},
  'until crisp':{gu:'કરકરું થાય ત્યાં સુધી',hi:'कुरकुरा होने तक',fr:'jusqu’à croustillant'},
  'until golden':{gu:'સોનેરી થાય ત્યાં સુધી',hi:'सुनहरा होने तक',fr:'jusqu’à coloration dorée'},
  'until fully cooked':{gu:'સંપૂર્ણ રંધાય ત્યાં સુધી',hi:'पूरी तरह पकने तक',fr:'jusqu’à cuisson complète'},
  'until cooked through':{gu:'અંદર સુધી રંધાય ત્યાં સુધી',hi:'अंदर तक पूरी तरह पकने तक',fr:'jusqu’à cuisson à cœur'},
  'until the mixture':{gu:'મિશ્રણ',hi:'मिश्रण',fr:'jusqu’à ce que le mélange'},
  'until the dough':{gu:'લોટ',hi:'आटा',fr:'jusqu’à ce que la pâte'},
  'until the batter':{gu:'ખીરું',hi:'घोल',fr:'jusqu’à ce que la pâte'},
  'bring to a boil':{gu:'ઉકળવા લાવો',hi:'उबाल आने दें',fr:'porter à ébullition'},
  'bring to the boil':{gu:'ઉકળવા લાવો',hi:'उबाल आने दें',fr:'porter à ébullition'},
  'bring together':{gu:'એકસાર કરો',hi:'एक साथ मिलाएँ',fr:'rassembler'},
  'stir continuously':{gu:'સતત હલાવતા રહો',hi:'लगातार चलाते रहें',fr:'remuer continuellement'},
  'stir frequently':{gu:'વારંવાર હલાવો',hi:'बार-बार चलाएँ',fr:'remuer fréquemment'},
  'mix well':{gu:'સારી રીતે મિક્સ કરો',hi:'अच्छी तरह मिलाएँ',fr:'bien mélanger'},
  'mix gently':{gu:'હળવેથી મિક્સ કરો',hi:'हल्के हाथ से मिलाएँ',fr:'mélanger délicatement'},
  'mix thoroughly':{gu:'ખૂબ સારી રીતે મિક્સ કરો',hi:'अच्छी तरह मिलाएँ',fr:'mélanger soigneusement'},
  'knead well':{gu:'સારી રીતે મસળો',hi:'अच्छी तरह गूंधें',fr:'bien pétrir'},
  'divide into equal':{gu:'સમાન ભાગોમાં વહેંચો',hi:'बराबर भागों में बाँटें',fr:'diviser en parts égales'},
  'keep covered':{gu:'ઢાંકીને રાખો',hi:'ढककर रखें',fr:'garder couvert'},
  'cover and rest':{gu:'ઢાંકી ને આરામ આપો',hi:'ढककर आराम दें',fr:'couvrir et laisser reposer'},
  'allow to cool':{gu:'ઠંડું થવા દો',hi:'ठंडा होने दें',fr:'laisser refroidir'},
  'let it cool':{gu:'તેને ઠંડું થવા દો',hi:'इसे ठंडा होने दें',fr:'laisser refroidir'},
  'let them cool':{gu:'તેમને ઠંડા થવા દો',hi:'उन्हें ठंडा होने दें',fr:'laisser refroidir'},
  'serve hot':{gu:'ગરમ પીરસો',hi:'गरम परोसें',fr:'servir chaud'},
  'serve warm':{gu:'હૂંફાળું પીરસો',hi:'गुनगुना परोसें',fr:'servir tiède'},
  'serve immediately':{gu:'તુરંત પીરસો',hi:'तुरंत परोसें',fr:'servir immédiatement'},
  'serve with':{gu:'સાથે પીરસો',hi:'के साथ परोसें',fr:'servir avec'},
  'set aside':{gu:'બાજુ પર રાખો',hi:'अलग रख दें',fr:'réserver'},
  'turn off the heat':{gu:'આંચ બંધ કરો',hi:'आँच बंद करें',fr:'couper le feu'},
  'remove from heat':{gu:'આંચ પરથી ઉતારો',hi:'आँच से उतारें',fr:'retirer du feu'},
  'from the heat':{gu:'આંચ પરથી',hi:'आँच से',fr:'du feu'},
  'over medium':{gu:'મધ્યમ આંચ પર',hi:'मध्यम आँच पर',fr:'à feu moyen'},
  'over low':{gu:'ધીમી આંચ પર',hi:'धीमी आँच पर',fr:'à feu doux'},
  'on low':{gu:'ધીમી આંચ પર',hi:'धीमी आँच पर',fr:'à feu doux'},
  'on medium':{gu:'મધ્યમ આંચ પર',hi:'मध्यम आँच पर',fr:'à feu moyen'},
  'for about':{gu:'લગભગ',hi:'लगभग',fr:'pendant environ'},
  'for several minutes':{gu:'થોડી મિનિટો સુધી',hi:'कुछ मिनट तक',fr:'pendant quelques minutes'},
  'for a few minutes':{gu:'થોડી મિનિટો સુધી',hi:'कुछ मिनट तक',fr:'pendant quelques minutes'},
  'for another minute':{gu:'વધુ એક મિનિટ',hi:'एक मिनट और',fr:'une minute de plus'},
  'several minutes':{gu:'થોડી મિનિટો',hi:'कुछ मिनट',fr:'quelques minutes'},
  'a few minutes':{gu:'થોડી મિનિટો',hi:'कुछ मिनट',fr:'quelques minutes'},
  'small amount':{gu:'થોડી માત્રા',hi:'थोड़ी मात्रा',fr:'petite quantité'},
  'small portions':{gu:'નાના ભાગો',hi:'छोटे भाग',fr:'petites portions'},
  'equal portions':{gu:'સમાન ભાગો',hi:'बराबर भाग',fr:'portions égales'},
  'clean cloth':{gu:'સ્વચ્છ કપડું',hi:'साफ़ कपड़ा',fr:'linge propre'},
  'airtight container':{gu:'હવાબંધ ડબ્બો',hi:'हवा बंद डिब्बा',fr:'boîte hermétique'},
  'covered container':{gu:'ઢાંકેલું ડબ્બું',hi:'ढका हुआ डिब्बा',fr:'récipient couvert'},
  'mixing bowl':{gu:'મિક્સિંગ બાઉલ',hi:'मिक्सिंग बाउल',fr:'saladier'},
  'wide bowl':{gu:'પહોળું વાસણ',hi:'चौड़ा बर्तन',fr:'grand bol'},
  'heavy pan':{gu:'જાડું પૅન',hi:'भारी पैन',fr:'casserole épaisse'},
  'small pan':{gu:'નાનું પૅન',hi:'छोटा पैन',fr:'petite casserole'},
  'hot oil':{gu:'ગરમ તેલ',hi:'गरम तेल',fr:'huile chaude'},
  'frying oil':{gu:'તળવાનું તેલ',hi:'तलने का तेल',fr:'huile de friture'},
  'cooking oil':{gu:'રસોઈનું તેલ',hi:'खाना पकाने का तेल',fr:'huile de cuisson'},
  'roasted cumin':{gu:'શેકેલું જીરું',hi:'भुना जीरा',fr:'cumin grillé'},
  'mustard seeds':{gu:'રાઈ',hi:'सरसों के दाने',fr:'graines de moutarde'},
  'curry leaves':{gu:'લીમડાના પાન',hi:'करी पत्ते',fr:'feuilles de curry'},
  'lemon juice':{gu:'લીંબુનો રસ',hi:'नींबू का रस',fr:'jus de citron'},
  'sweet-sour':{gu:'ખાટું-મીઠું',hi:'खट्टा-मीठा',fr:'aigre-doux'},
  'sweet and sour':{gu:'ખાટું-મીઠું',hi:'खट्टा-मीठा',fr:'aigre-doux'},
  'deep-fry':{gu:'ડીપ ફ્રાય કરો',hi:'गहरे तेल में तलें',fr:'frire'},
  'deep fry':{gu:'ડીપ ફ્રાય કરો',hi:'गहरे तेल में तलें',fr:'frire'},
  'shallow-fry':{gu:'ઓછા તેલમાં શેકો',hi:'कम तेल में तलें',fr:'poêler'},
  'shallow fry':{gu:'ઓછા તેલમાં શેકો',hi:'कम तेल में तलें',fr:'poêler'},
  'steam until':{gu:'વરાળમાં રાંધો જ્યાં સુધી',hi:'भाप में पकाएँ जब तक',fr:'cuire à la vapeur jusqu’à'},
  'steam for':{gu:'વરાળમાં રાંધો',hi:'भाप में पकाएँ',fr:'cuire à la vapeur pendant'},
  'steam the':{gu:'વરાળમાં રાંધો',hi:'भाप में पकाएँ',fr:'cuire à la vapeur'},
  'preheated oven':{gu:'પહેલેથી ગરમ કરેલું ઓવન',hi:'पहले से गरम ओवन',fr:'four préchauffé'},
  'baking tin':{gu:'બેકિંગ ટિન',hi:'बेकिंग टिन',fr:'moule à gâteau'},
  'baking powder':{gu:'બેકિંગ પાઉડર',hi:'बेकिंग पाउडर',fr:'levure chimique'},
  'tester comes out clean':{gu:'ટેસ્ટર સાફ બહાર આવે',hi:'टेस्टर साफ़ बाहर आए',fr:'la lame ressort propre'},
  'fully dissolved':{gu:'સંપૂર્ણ ઓગળી જાય',hi:'पूरी तरह घुल जाए',fr:'complètement dissous'},
  'fully cooked':{gu:'સંપૂર્ણ રંધાયેલું',hi:'पूरी तरह पका हुआ',fr:'complètement cuit'},
  'well coated':{gu:'સારી રીતે મસાલો ચઢેલો',hi:'अच्छी तरह लिपटा हुआ',fr:'bien enrobé'},
  'well combined':{gu:'સારી રીતે ભળેલું',hi:'अच्छी तरह मिला हुआ',fr:'bien mélangé'},
  'finely chopped':{gu:'બારીક સમારેલું',hi:'बारीक कटा हुआ',fr:'finement haché'},
  'finely chop':{gu:'બારીક સમારો',hi:'बारीक काटें',fr:'hacher finement'},
  'grate':{gu:'છીણો',hi:'कद्दूकस करें',fr:'râper'},
  'grated':{gu:'છીણેલું',hi:'कद्दूकस किया हुआ',fr:'râpé'},
  'finely':{gu:'બારીક',hi:'बारीक',fr:'finement'},
  'lightly':{gu:'હળવેથી',hi:'हल्के से',fr:'légèrement'},
  'gently':{gu:'હળવેથી',hi:'धीरे से',fr:'doucement'},
  'carefully':{gu:'સાવધાનીથી',hi:'सावधानी से',fr:'avec précaution'},
  'gradually':{gu:'ધીમે ધીમે',hi:'धीरे-धीरे',fr:'progressivement'},
  'immediately':{gu:'તુરંત',hi:'तुरंत',fr:'immédiatement'},
  'thoroughly':{gu:'સારી રીતે',hi:'अच्छी तरह',fr:'soigneusement'},
  'completely':{gu:'સંપૂર્ણ',hi:'पूरी तरह',fr:'complètement'},
};

const words: Record<string, Triple> = {
  'add':{gu:'ઉમેરો',hi:'डालें',fr:'ajoutez'}, 'mix':{gu:'મિક્સ કરો',hi:'मिलाएँ',fr:'mélangez'}, 'combine':{gu:'ભેળવો',hi:'मिलाएँ',fr:'combinez'},
  'stir':{gu:'હલાવો',hi:'चलाएँ',fr:'remuez'}, 'whisk':{gu:'ફેંટો',hi:'फेंटें',fr:'fouettez'}, 'knead':{gu:'મસળો',hi:'गूंधें',fr:'pétrissez'},
  'cook':{gu:'રાંધો',hi:'पकाएँ',fr:'cuisez'}, 'heat':{gu:'ગરમ કરો',hi:'गरम करें',fr:'chauffez'}, 'boil':{gu:'ઉકાળો',hi:'उबालें',fr:'faites bouillir'},
  'simmer':{gu:'ધીમે ઉકાળો',hi:'धीमी आँच पर पकाएँ',fr:'mijotez'}, 'roast':{gu:'શેકો',hi:'भूनें',fr:'faites griller'}, 'fry':{gu:'તળો',hi:'तलें',fr:'faites frire'},
  'steam':{gu:'વરાળમાં રાંધો',hi:'भाप में पकाएँ',fr:'cuisez à la vapeur'}, 'bake':{gu:'બેક કરો',hi:'बेक करें',fr:'faites cuire au four'},
  'serve':{gu:'પીરસો',hi:'परोसें',fr:'servez'}, 'garnish':{gu:'સજાવો',hi:'सजाएँ',fr:'garnissez'}, 'cover':{gu:'ઢાંકો',hi:'ढकें',fr:'couvrez'},
  'rest':{gu:'આરામ આપો',hi:'आराम दें',fr:'laissez reposer'}, 'cool':{gu:'ઠંડું કરો',hi:'ठंडा करें',fr:'refroidissez'}, 'drain':{gu:'પાણી નિતારો',hi:'पानी निकालें',fr:'égouttez'},
  'rinse':{gu:'ધોઈ લો',hi:'धो लें',fr:'rincez'}, 'wash':{gu:'ધોવો',hi:'धोएँ',fr:'lavez'}, 'soak':{gu:'પલાળો',hi:'भिगोएँ',fr:'faites tremper'},
  'chop':{gu:'સમારો',hi:'काटें',fr:'hachez'}, 'slice':{gu:'કાપો',hi:'स्लाइस करें',fr:'tranchez'}, 'cut':{gu:'કાપો',hi:'काटें',fr:'coupez'},
  'roll':{gu:'વણો',hi:'बेलें',fr:'étalez'}, 'shape':{gu:'આકાર આપો',hi:'आकार दें',fr:'façonnez'}, 'flatten':{gu:'ચપટું કરો',hi:'चपटा करें',fr:'aplatissez'},
  'press':{gu:'દબાવો',hi:'दबाएँ',fr:'pressez'}, 'flip':{gu:'પલટાવો',hi:'पलटें',fr:'retournez'}, 'turn':{gu:'ફેરવો',hi:'पलटें',fr:'tournez'},
  'pour':{gu:'રેડો',hi:'डालें',fr:'versez'}, 'sprinkle':{gu:'છાંટો',hi:'छिड़कें',fr:'saupoudrez'}, 'brush':{gu:'લગાવો',hi:'लगाएँ',fr:'badigeonnez'},
  'spread':{gu:'ફેલાવો',hi:'फैलाएँ',fr:'étalez'}, 'fold':{gu:'વાળો',hi:'मोड़ें',fr:'pliez'}, 'seal':{gu:'બંધ કરો',hi:'सील करें',fr:'scellez'},
  'remove':{gu:'કાઢો',hi:'निकालें',fr:'retirez'}, 'transfer':{gu:'બીજા વાસણમાં લો',hi:'दूसरे बर्तन में डालें',fr:'transférez'},
  'prepare':{gu:'તૈયાર કરો',hi:'तैयार करें',fr:'préparez'}, 'make':{gu:'બનાવો',hi:'बनाएँ',fr:'préparez'}, 'keep':{gu:'રાખો',hi:'रखें',fr:'gardez'},
  'let':{gu:'થવા દો',hi:'होने दें',fr:'laissez'}, 'allow':{gu:'થવા દો',hi:'होने दें',fr:'laissez'}, 'check':{gu:'ચકાસો',hi:'जाँचें',fr:'vérifiez'},
  'taste':{gu:'સ્વાદ ચકાસો',hi:'स्वाद देखें',fr:'goûtez'}, 'adjust':{gu:'જરૂર મુજબ બદલો',hi:'स्वादानुसार समायोजित करें',fr:'ajustez'},
  'divide':{gu:'વહેંચો',hi:'बाँटें',fr:'divisez'}, 'repeat':{gu:'ફરી કરો',hi:'दोहराएँ',fr:'répétez'}, 'continue':{gu:'ચાલુ રાખો',hi:'जारी रखें',fr:'continuez'},
  'water':{gu:'પાણી',hi:'पानी',fr:'eau'}, 'oil':{gu:'તેલ',hi:'तेल',fr:'huile'}, 'ghee':{gu:'ઘી',hi:'घी',fr:'ghee'}, 'salt':{gu:'મીઠું',hi:'नमक',fr:'sel'},
  'sugar':{gu:'ખાંડ',hi:'चीनी',fr:'sucre'}, 'jaggery':{gu:'ગોળ',hi:'गुड़',fr:'jaggery'}, 'milk':{gu:'દૂધ',hi:'दूध',fr:'lait'}, 'yogurt':{gu:'દહીં',hi:'दही',fr:'yaourt'},
  'flour':{gu:'લોટ',hi:'आटा',fr:'farine'}, 'dough':{gu:'લોટ',hi:'आटा',fr:'pâte'}, 'batter':{gu:'ખીરું',hi:'घोल',fr:'pâte'}, 'mixture':{gu:'મિશ્રણ',hi:'मिश्रण',fr:'mélange'},
  'rice':{gu:'ચોખા',hi:'चावल',fr:'riz'}, 'dal':{gu:'દાળ',hi:'दाल',fr:'dal'}, 'besan':{gu:'ચણાનો લોટ',hi:'बेसन',fr:'farine de pois chiches'},
  'potato':{gu:'બટાકું',hi:'आलू',fr:'pomme de terre'}, 'potatoes':{gu:'બટાકા',hi:'आलू',fr:'pommes de terre'}, 'tomato':{gu:'ટમેટું',hi:'टमाटर',fr:'tomate'},
  'tomatoes':{gu:'ટમેટાં',hi:'टमाटर',fr:'tomates'}, 'eggplant':{gu:'રીંગણ',hi:'बैंगन',fr:'aubergine'}, 'vegetables':{gu:'શાકભાજી',hi:'सब्ज़ियाँ',fr:'légumes'},
  'cumin':{gu:'જીરું',hi:'जीरा',fr:'cumin'}, 'mustard':{gu:'રાઈ',hi:'सरसों',fr:'moutarde'}, 'turmeric':{gu:'હળદર',hi:'हल्दी',fr:'curcuma'},
  'chilli':{gu:'મરચું',hi:'मिर्च',fr:'piment'}, 'ginger':{gu:'આદુ',hi:'अदरक',fr:'gingembre'}, 'coriander':{gu:'કોથમીર',hi:'धनिया',fr:'coriandre'},
  'cardamom':{gu:'એલચી',hi:'इलायची',fr:'cardamome'}, 'lemon':{gu:'લીંબુ',hi:'नींबू',fr:'citron'}, 'coconut':{gu:'નાળિયેર',hi:'नारियल',fr:'noix de coco'},
  'sesame':{gu:'તલ',hi:'तिल',fr:'sésame'}, 'spices':{gu:'મસાલા',hi:'मसाले',fr:'épices'}, 'seasoning':{gu:'મસાલો',hi:'मसाला',fr:'assaisonnement'},
  'seasonings':{gu:'મસાલા',hi:'मसाले',fr:'assaisonnements'}, 'tempering':{gu:'વઘાર',hi:'तड़का',fr:'tadka'}, 'masala':{gu:'મસાલો',hi:'मसाला',fr:'masala'},
  'pan':{gu:'પૅન',hi:'पैन',fr:'casserole'}, 'pot':{gu:'વાસણ',hi:'बर्तन',fr:'casserole'}, 'bowl':{gu:'વાસણ',hi:'कटोरा',fr:'bol'}, 'plate':{gu:'થાળી',hi:'प्लेट',fr:'assiette'},
  'tawa':{gu:'તવો',hi:'तवा',fr:'tawa'}, 'steamer':{gu:'સ્ટીમર',hi:'स्टीमर',fr:'cuiseur vapeur'}, 'oven':{gu:'ઓવન',hi:'ओवन',fr:'four'},
  'hot':{gu:'ગરમ',hi:'गरम',fr:'chaud'}, 'warm':{gu:'હૂંફાળું',hi:'गुनगुना',fr:'tiède'}, 'cold':{gu:'ઠંડું',hi:'ठंडा',fr:'froid'},
  'soft':{gu:'નરમ',hi:'नरम',fr:'souple'}, 'firm':{gu:'કઠણ',hi:'सख्त',fr:'ferme'}, 'smooth':{gu:'મસૃણ',hi:'चिकना',fr:'lisse'}, 'thick':{gu:'ઘાટું',hi:'गाढ़ा',fr:'épais'},
  'thin':{gu:'પાતળું',hi:'पतला',fr:'fin'}, 'crisp':{gu:'કરકરું',hi:'कुरकुरा',fr:'croustillant'}, 'tender':{gu:'નરમ',hi:'नरम',fr:'tendre'},
  'golden':{gu:'સોનેરી',hi:'सुनहरा',fr:'doré'}, 'brown':{gu:'ભૂરું',hi:'भूरा',fr:'brun'}, 'dry':{gu:'સૂકું',hi:'सूखा',fr:'sec'}, 'wet':{gu:'ભીનું',hi:'गीला',fr:'humide'},
  'fresh':{gu:'તાજું',hi:'ताज़ा',fr:'frais'}, 'raw':{gu:'કાચું',hi:'कच्चा',fr:'cru'}, 'cooked':{gu:'રંધાયેલું',hi:'पका हुआ',fr:'cuit'},
  'minutes':{gu:'મિનિટ',hi:'मिनट',fr:'minutes'}, 'minute':{gu:'મિનિટ',hi:'मिनट',fr:'minute'}, 'hours':{gu:'કલાક',hi:'घंटे',fr:'heures'},
  'side':{gu:'બાજુ',hi:'तरफ़',fr:'côté'}, 'sides':{gu:'બંને બાજુ',hi:'दोनों तरफ़',fr:'côtés'}, 'edges':{gu:'કિનારા',hi:'किनारे',fr:'bords'}, 'centre':{gu:'મધ્ય',hi:'बीच',fr:'centre'},
  'surface':{gu:'સપાટી',hi:'सतह',fr:'surface'}, 'bottom':{gu:'તળિયું',hi:'तला',fr:'fond'}, 'top':{gu:'ઉપર',hi:'ऊपर',fr:'dessus'},
  'pieces':{gu:'ટુકડા',hi:'टुकड़े',fr:'morceaux'}, 'piece':{gu:'ટુકડો',hi:'टुकड़ा',fr:'morceau'}, 'balls':{gu:'ગોળા',hi:'गोले',fr:'boules'}, 'ball':{gu:'ગોળો',hi:'गोला',fr:'boule'},
  'portion':{gu:'ભાગ',hi:'भाग',fr:'portion'}, 'portions':{gu:'ભાગો',hi:'भाग',fr:'portions'}, 'strips':{gu:'પટ્ટીઓ',hi:'पट्टियाँ',fr:'bandes'}, 'rounds':{gu:'ગોળ ટુકડા',hi:'गोल टुकड़े',fr:'rondelles'},
  'first':{gu:'પહેલું',hi:'पहला',fr:'premier'}, 'second':{gu:'બીજું',hi:'दूसरा',fr:'deuxième'}, 'remaining':{gu:'બાકીનું',hi:'बाकी',fr:'restant'},
  'listed':{gu:'આપેલા',hi:'दिए गए',fr:'indiqués'}, 'required':{gu:'જરૂરી',hi:'आवश्यक',fr:'requis'}, 'optional':{gu:'વૈકલ્પિક',hi:'वैकल्पिक',fr:'facultatif'},
  'desired':{gu:'ઇચ્છિત',hi:'मनचाहा',fr:'souhaité'}, 'preferred':{gu:'પસંદનું',hi:'पसंदीदा',fr:'préféré'},
  'before':{gu:'પહેલાં',hi:'पहले',fr:'avant'}, 'after':{gu:'પછી',hi:'बाद',fr:'après'}, 'then':{gu:'પછી',hi:'फिर',fr:'puis'}, 'while':{gu:'દરમિયાન',hi:'जबकि',fr:'pendant'},
  'when':{gu:'જ્યારે',hi:'जब',fr:'lorsque'}, 'until':{gu:'જ્યાં સુધી',hi:'जब तक',fr:'jusqu’à'}, 'because':{gu:'કારણ કે',hi:'क्योंकि',fr:'parce que'},
  'without':{gu:'વગર',hi:'बिना',fr:'sans'}, 'with':{gu:'સાથે',hi:'के साथ',fr:'avec'}, 'into':{gu:'માં',hi:'में',fr:'dans'}, 'in':{gu:'માં',hi:'में',fr:'dans'},
  'on':{gu:'પર',hi:'पर',fr:'sur'}, 'over':{gu:'પર',hi:'पर',fr:'sur'}, 'from':{gu:'માંથી',hi:'से',fr:'de'}, 'through':{gu:'આરપાર',hi:'के माध्यम से',fr:'à travers'},
  'to':{gu:'સુધી',hi:'तक',fr:'à'}, 'for':{gu:'માટે',hi:'के लिए',fr:'pour'}, 'of':{gu:'નું',hi:'का',fr:'de'}, 'by':{gu:'દ્વારા',hi:'द्वारा',fr:'par'},
  'and':{gu:'અને',hi:'और',fr:'et'}, 'or':{gu:'અથવા',hi:'या',fr:'ou'}, 'but':{gu:'પરંતુ',hi:'लेकिन',fr:'mais'}, 'so':{gu:'તેથી',hi:'इसलिए',fr:'donc'},
  'the':{gu:'',hi:'',fr:'le'}, 'a':{gu:'એક',hi:'एक',fr:'un'}, 'an':{gu:'એક',hi:'एक',fr:'un'}, 'your':{gu:'તમારું',hi:'अपना',fr:'votre'},
  'it':{gu:'તે',hi:'इसे',fr:'il'}, 'them':{gu:'તેમને',hi:'उन्हें',fr:'les'}, 'they':{gu:'તેઓ',hi:'वे',fr:'ils'}, 'you':{gu:'તમે',hi:'आप',fr:'vous'},
  'this':{gu:'આ',hi:'यह',fr:'ce'}, 'that':{gu:'તે',hi:'वह',fr:'cela'}, 'all':{gu:'બધું',hi:'सभी',fr:'tout'}, 'each':{gu:'દરેક',hi:'हर',fr:'chaque'},
  'one':{gu:'એક',hi:'एक',fr:'un'}, 'more':{gu:'વધુ',hi:'और',fr:'plus'}, 'only':{gu:'ફક્ત',hi:'केवल',fr:'seulement'}, 'very':{gu:'ખૂબ',hi:'बहुत',fr:'très'},
  'well':{gu:'સારી રીતે',hi:'अच्छी तरह',fr:'bien'}, 'enough':{gu:'પૂરતું',hi:'पर्याप्त',fr:'assez'}, 'about':{gu:'લગભગ',hi:'लगभग',fr:'environ'},
  'again':{gu:'ફરી',hi:'फिर',fr:'encore'}, 'together':{gu:'એકસાથે',hi:'एक साथ',fr:'ensemble'}, 'evenly':{gu:'સમાન રીતે',hi:'समान रूप से',fr:'uniformément'},
  'slightly':{gu:'થોડું',hi:'थोड़ा',fr:'légèrement'}, 'briefly':{gu:'થોડીવાર',hi:'थोड़ी देर',fr:'brièvement'}, 'quickly':{gu:'ઝડપથી',hi:'जल्दी',fr:'rapidement'},
  'slowly':{gu:'ધીમે',hi:'धीरे',fr:'lentement'}, 'constantly':{gu:'સતત',hi:'लगातार',fr:'constamment'}, 'frequently':{gu:'વારંવાર',hi:'बार-बार',fr:'fréquemment'},
  'is':{gu:'છે',hi:'है',fr:'est'}, 'are':{gu:'છે',hi:'हैं',fr:'sont'}, 'becomes':{gu:'થાય',hi:'हो जाए',fr:'devient'}, 'become':{gu:'થાય',hi:'हो जाए',fr:'deviennent'},
  'do':{gu:'કરો',hi:'करें',fr:'faites'}, 'not':{gu:'નહીં',hi:'नहीं',fr:'ne pas'}, 'can':{gu:'શકે',hi:'सकता है',fr:'peut'}, 'should':{gu:'જોઈએ',hi:'चाहिए',fr:'doit'},
};

function esc(value:string){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}

function cleanup(text:string, language:Exclude<SiteLanguage,'en'>){
  let out=text.replace(/\s+([,.;:!?])/g,'$1').replace(/\s{2,}/g,' ').trim();
  if(language==='fr') out=out.replace(/\ble\ ([aeiouyh])/gi,'l’$1');
  return out;
}

export function localizeCookingStep(step:string, language:SiteLanguage):string{
  if(language==='en') return step;
  let out=step;
  for(const key of Object.keys(phrases).sort((a,b)=>b.length-a.length)){
    const value=phrases[key][language];
    out=out.replace(new RegExp(`\\b${esc(key)}\\b`,'gi'),value);
  }
  out=out.replace(/[A-Za-z]+(?:-[A-Za-z]+)?/g,(token)=>{
    const mapped=words[token.toLowerCase()]?.[language];
    return mapped ?? token;
  });
  return cleanup(out,language);
}

export function localizedStepSet(steps:string[]){
  return {
    en:steps,
    gu:steps.map((step)=>localizeCookingStep(step,'gu')),
    hi:steps.map((step)=>localizeCookingStep(step,'hi')),
    fr:steps.map((step)=>localizeCookingStep(step,'fr')),
  };
}
