import type { AppLanguage } from './i18n';
import { detailedRecipeSteps } from './recipeDetails';
export type Diet='jain'|'swaminarayan'|'veg'|'vegan'|'nonveg';
export type MealKind='proper'|'light'|'breakfast'|'dessert'|'drink';
export type RecipeIngredient={name:string; qty:number; unit:string; optional?:boolean};
export type Recipe={id:string; names:Record<AppLanguage,string>; baseServings:number; kind:MealKind; diets:Diet[]; ingredients:RecipeIngredient[]; steps:Record<AppLanguage,string[]>};
const N=(en:string,gu:string,hi:string,fr:string):Record<AppLanguage,string>=>({en,gu,hi,fr});
const S=(en:string,gu?:string,hi?:string,fr?:string):Record<AppLanguage,string[]>=>({en:[en],gu:[gu||en],hi:[hi||en],fr:[fr||en]});
const r=(id:string,n:Record<AppLanguage,string>,kind:MealKind,diets:Diet[],ingredients:RecipeIngredient[],step:string):Recipe=>({id,names:n,baseServings:4,kind,diets,ingredients,steps:S(step)});
const baseRecipes:Recipe[]=[
r('rotli',N('Rotli / Phulka','રોટલી / ફુલકા','रोटी / फुल्का','Roti / Phulka'),'proper',['jain','swaminarayan','veg','vegan'],[{name:'Whole wheat flour',qty:240,unit:'g'},{name:'Water',qty:160,unit:'ml'},{name:'Oil',qty:5,unit:'ml',optional:true}], 'Knead a soft dough, rest, roll thin and cook on a hot tawa; puff briefly over flame if desired.'),
r('thepla',N('Thepla','થેપલા','थेपला','Thepla'),'breakfast',['swaminarayan','veg'],[{name:'Whole wheat flour',qty:250,unit:'g'},{name:'Yogurt',qty:80,unit:'g'},{name:'Oil',qty:30,unit:'ml'},{name:'Turmeric',qty:2,unit:'g'},{name:'Chilli powder',qty:4,unit:'g'}], 'Mix, knead, rest, roll and shallow-cook both sides until spotted and cooked.'),
r('methi-thepla',N('Methi Thepla','મેથીના થેપલા','मेथी थेपला','Thepla au fenugrec'),'breakfast',['swaminarayan','veg'],[{name:'Whole wheat flour',qty:250,unit:'g'},{name:'Fresh methi',qty:120,unit:'g'},{name:'Yogurt',qty:80,unit:'g'},{name:'Oil',qty:30,unit:'ml'},{name:'Turmeric',qty:2,unit:'g'}], 'Combine chopped methi with dough ingredients, rest, roll and shallow-cook.'),
r('bajri-rotla',N('Bajri Rotla','બાજરીનો રોટલો','बाजरे का रोटला','Rotla de millet'),'proper',['jain','swaminarayan','veg','vegan'],[{name:'Bajra flour',qty:300,unit:'g'},{name:'Warm water',qty:220,unit:'ml'}], 'Knead with warm water, pat into thick rotla and cook slowly on both sides.'),
r('bhakri',N('Bhakri','ભાખરી','भाखरी','Bhakri'),'proper',['jain','swaminarayan','veg'],[{name:'Whole wheat flour',qty:300,unit:'g'},{name:'Ghee',qty:35,unit:'g'},{name:'Water',qty:150,unit:'ml'}], 'Make a firm dough, roll thick and roast slowly until crisp.'),
r('puran-poli',N('Puran Poli','પૂરણ પોળી','पूरण पोली','Puran poli'),'dessert',['jain','swaminarayan','veg'],[{name:'Whole wheat flour',qty:250,unit:'g'},{name:'Chana dal',qty:220,unit:'g'},{name:'Jaggery',qty:220,unit:'g'},{name:'Ghee',qty:40,unit:'g'}], 'Cook dal, make jaggery puran, fill dough, roll gently and roast with ghee.'),
r('khichdi',N('Khichdi','ખીચડી','खिचड़ी','Khichdi'),'proper',['jain','swaminarayan','veg'],[{name:'Rice',qty:220,unit:'g'},{name:'Moong dal',qty:120,unit:'g'},{name:'Ghee',qty:20,unit:'g'},{name:'Turmeric',qty:2,unit:'g'}], 'Wash rice and dal, pressure-cook soft with water, turmeric and salt; finish with ghee.'),
r('vaghareli-khichdi',N('Vaghareli Khichdi','વઘારેલી ખીચડી','वघारेली खिचड़ी','Khichdi assaisonné'),'proper',['swaminarayan','veg'],[{name:'Rice',qty:220,unit:'g'},{name:'Moong dal',qty:120,unit:'g'},{name:'Mixed vegetables',qty:180,unit:'g'},{name:'Ghee',qty:25,unit:'g'}], 'Temper spices, sauté vegetables, add rice and dal and pressure-cook until tender.'),
r('kadhi',N('Gujarati Kadhi','ગુજરાતી કઢી','गुजराती कढ़ी','Kadhi gujarati'),'proper',['jain','swaminarayan','veg'],[{name:'Yogurt',qty:500,unit:'g'},{name:'Besan',qty:35,unit:'g'},{name:'Water',qty:900,unit:'ml'},{name:'Jaggery',qty:20,unit:'g'}], 'Whisk yogurt, besan and water; simmer, season sweet-sour and finish with tempering.'),
r('gujarati-dal',N('Gujarati Dal','ગુજરાતી દાળ','गुजराती दाल','Dal gujarati'),'proper',['jain','swaminarayan','veg'],[{name:'Tuvar dal',qty:220,unit:'g'},{name:'Tomato',qty:150,unit:'g'},{name:'Jaggery',qty:25,unit:'g'},{name:'Lemon',qty:1,unit:'pcs'}], 'Pressure-cook dal, whisk smooth, add sweet-sour seasoning and simmer with tempering.'),
r('dal-dhokli',N('Dal Dhokli','દાળ ઢોકળી','दाल ढोकली','Dal dhokli'),'proper',['swaminarayan','veg'],[{name:'Tuvar dal',qty:220,unit:'g'},{name:'Whole wheat flour',qty:220,unit:'g'},{name:'Tomato',qty:150,unit:'g'},{name:'Jaggery',qty:25,unit:'g'}], 'Prepare seasoned dal, roll spiced wheat dough, cut diamonds and simmer them in dal until cooked.'),
r('sev-tameta',N('Sev Tameta','સેવ ટમેટા','सेव टमाटर','Tomates au sev'),'proper',['jain','swaminarayan','veg'],[{name:'Tomato',qty:650,unit:'g'},{name:'Sev',qty:160,unit:'g'},{name:'Oil',qty:25,unit:'ml'}], 'Cook a spiced tomato gravy and add sev just before serving.'),
r('ringan-bateta',N('Ringan Bateta','રીંગણ બટેટા','बैंगन आलू','Aubergine-pomme de terre'),'proper',['jain','swaminarayan','veg','vegan'],[{name:'Eggplant',qty:450,unit:'g'},{name:'Potato',qty:350,unit:'g'},{name:'Oil',qty:30,unit:'ml'}], 'Temper spices, add cubed potato and eggplant, cover and cook until tender.'),
r('ringan-olo',N('Ringan no Olo','રીંગણનો ઓળો','बैंगन का भरता','Caviar d’aubergine gujarati'),'proper',['swaminarayan','veg'],[{name:'Eggplant',qty:900,unit:'g'},{name:'Tomato',qty:250,unit:'g'},{name:'Oil',qty:30,unit:'ml'}], 'Roast eggplant until smoky, mash and cook with tomato and spices.'),
r('undhiyu',N('Undhiyu','ઉંધિયું','उंधियू','Undhiyu'),'proper',['swaminarayan','veg'],[{name:'Surti papdi',qty:350,unit:'g'},{name:'Tuvar lilva',qty:200,unit:'g'},{name:'Baby potato',qty:300,unit:'g'},{name:'Purple yam',qty:250,unit:'g'},{name:'Raw banana',qty:250,unit:'g'},{name:'Methi muthiya',qty:250,unit:'g'}], 'Layer seasonal vegetables with masala and muthiya; cook slowly until tender and well coated.'),
r('tindora',N('Tindora nu Shaak','ટીંડોરાનું શાક','टिंडोरा की सब्ज़ी','Curry de tindora'),'proper',['jain','swaminarayan','veg','vegan'],[{name:'Tindora',qty:650,unit:'g'},{name:'Oil',qty:30,unit:'ml'}], 'Slice tindora and stir-cook with tempering and dry spices until tender.'),
r('bhinda',N('Bhinda nu Shaak','ભીંડાનું શાક','भिंडी की सब्ज़ी','Gombo sauté'),'proper',['jain','swaminarayan','veg','vegan'],[{name:'Okra',qty:650,unit:'g'},{name:'Oil',qty:35,unit:'ml'}], 'Dry and slice okra, sauté with spices until non-sticky and tender.'),
r('dudhi-chana',N('Dudhi Chana Dal','દૂધી ચણા દાળ','लौकी चना दाल','Courge et chana dal'),'proper',['jain','swaminarayan','veg'],[{name:'Bottle gourd',qty:500,unit:'g'},{name:'Chana dal',qty:180,unit:'g'},{name:'Tomato',qty:120,unit:'g'}], 'Pressure-cook soaked chana dal with bottle gourd; finish with seasoned tempering.'),
r('tuvar-lilva',N('Tuvar Lilva','તુવેર લીલવા','तुवर लिलवा','Pois de pigeon frais'),'proper',['jain','swaminarayan','veg','vegan'],[{name:'Tuvar lilva',qty:500,unit:'g'},{name:'Potato',qty:250,unit:'g'},{name:'Oil',qty:25,unit:'ml'}], 'Cook lilva and potato with Gujarati spices until tender.'),
r('bateta',N('Bateta nu Shaak','બટેટાનું શાક','आलू की सब्ज़ी','Curry de pommes de terre'),'proper',['jain','swaminarayan','veg','vegan'],[{name:'Potato',qty:700,unit:'g'},{name:'Tomato',qty:180,unit:'g'},{name:'Oil',qty:25,unit:'ml'}], 'Temper spices, add potatoes and tomato and cook to desired gravy consistency.'),
r('handvo',N('Handvo','હાંડવો','हांडवो','Handvo'),'breakfast',['swaminarayan','veg'],[{name:'Handvo flour',qty:350,unit:'g'},{name:'Yogurt',qty:250,unit:'g'},{name:'Bottle gourd',qty:300,unit:'g'},{name:'Oil',qty:40,unit:'ml'}], 'Ferment batter, mix grated bottle gourd, temper and bake or pan-cook until crisp outside.'),
r('dhokla',N('Dhokla','ઢોકળા','ढोकला','Dhokla'),'light',['jain','swaminarayan','veg'],[{name:'Rice',qty:220,unit:'g'},{name:'Chana dal',qty:110,unit:'g'},{name:'Yogurt',qty:180,unit:'g'}], 'Ferment ground batter, steam until set and finish with tempering.'),
r('khaman',N('Khaman','ખમણ','खमन','Khaman'),'light',['jain','swaminarayan','veg'],[{name:'Besan',qty:250,unit:'g'},{name:'Water',qty:300,unit:'ml'},{name:'Lemon',qty:1,unit:'pcs'},{name:'Oil',qty:25,unit:'ml'}], 'Make airy besan batter, steam, cut and pour tempering over it.'),
r('khandvi',N('Khandvi','ખાંડવી','खांडवी','Khandvi'),'light',['jain','swaminarayan','veg'],[{name:'Besan',qty:150,unit:'g'},{name:'Yogurt',qty:300,unit:'g'},{name:'Water',qty:450,unit:'ml'}], 'Cook smooth besan-yogurt batter until thick, spread thin, roll and temper.'),
r('patra',N('Patra','પાત્રા','पात्रा','Patra'),'light',['jain','swaminarayan','veg'],[{name:'Colocasia leaves',qty:8,unit:'pcs'},{name:'Besan',qty:220,unit:'g'},{name:'Jaggery',qty:25,unit:'g'}], 'Coat leaves with spiced besan paste, roll, steam, slice and temper.'),
r('muthiya',N('Muthiya','મુઠિયા','मुठिया','Muthiya'),'light',['swaminarayan','veg'],[{name:'Whole wheat flour',qty:180,unit:'g'},{name:'Besan',qty:100,unit:'g'},{name:'Bottle gourd',qty:350,unit:'g'},{name:'Yogurt',qty:80,unit:'g'}], 'Make a soft vegetable dough, steam logs, slice and temper.'),
r('fafda',N('Fafda','ફાફડા','फाफड़ा','Fafda'),'light',['jain','swaminarayan','veg'],[{name:'Besan',qty:300,unit:'g'},{name:'Oil',qty:50,unit:'ml'},{name:'Papad khar',qty:3,unit:'g'}], 'Knead a firm besan dough, stretch thin strips and deep-fry crisp.'),
r('ganthiya',N('Ganthiya','ગાંઠિયા','गांठिया','Ganthiya'),'light',['jain','swaminarayan','veg'],[{name:'Besan',qty:300,unit:'g'},{name:'Oil',qty:45,unit:'ml'},{name:'Papad khar',qty:3,unit:'g'}], 'Prepare soft besan dough, press through ganthiya mould into hot oil and fry.'),
r('khichu',N('Khichu','ખીચું','खिचू','Khichu'),'light',['jain','swaminarayan','veg','vegan'],[{name:'Rice flour',qty:250,unit:'g'},{name:'Water',qty:650,unit:'ml'},{name:'Cumin',qty:4,unit:'g'}], 'Boil seasoned water, stir in rice flour and steam until glossy and cooked.'),
r('locho',N('Surti Locho','સુરતી લોચો','सुरती लोचो','Locho de Surat'),'light',['jain','swaminarayan','veg'],[{name:'Chana dal',qty:260,unit:'g'},{name:'Poha',qty:60,unit:'g'},{name:'Yogurt',qty:120,unit:'g'}], 'Ferment ground batter, steam soft, mash lightly and serve with masala and sev.'),
r('sev-khamani',N('Sev Khamani','સેવ ખમણી','सेव खमणी','Sev khamani'),'light',['jain','swaminarayan','veg'],[{name:'Chana dal',qty:260,unit:'g'},{name:'Sev',qty:120,unit:'g'},{name:'Lemon',qty:1,unit:'pcs'}], 'Steam or cook dal mixture, crumble, season sweet-sour and garnish with sev.'),
r('sukhdi',N('Sukhdi','સુખડી','सुखड़ी','Sukhdi'),'dessert',['jain','swaminarayan','veg'],[{name:'Whole wheat flour',qty:250,unit:'g'},{name:'Ghee',qty:180,unit:'g'},{name:'Jaggery',qty:200,unit:'g'}], 'Roast flour in ghee, remove from heat, mix jaggery and set in a tray.'),
r('shrikhand',N('Shrikhand','શ્રીખંડ','श्रीखंड','Shrikhand'),'dessert',['jain','swaminarayan','veg'],[{name:'Hung yogurt',qty:700,unit:'g'},{name:'Sugar',qty:180,unit:'g'},{name:'Cardamom',qty:3,unit:'g'}], 'Whisk hung yogurt with sugar and aromatics until smooth; chill.'),
r('basundi',N('Basundi','બાસુંદી','बासुंदी','Basundi'),'dessert',['jain','swaminarayan','veg'],[{name:'Whole milk',qty:2000,unit:'ml'},{name:'Sugar',qty:180,unit:'g'},{name:'Cardamom',qty:3,unit:'g'}], 'Slowly reduce milk while stirring, sweeten, flavour and chill or serve warm.'),
r('mohanthal',N('Mohanthal','મોહનથાળ','मोहनथाल','Mohanthal'),'dessert',['jain','swaminarayan','veg'],[{name:'Besan',qty:350,unit:'g'},{name:'Ghee',qty:250,unit:'g'},{name:'Sugar',qty:300,unit:'g'},{name:'Milk',qty:60,unit:'ml'}], 'Texture besan with milk/ghee, roast deeply, combine with sugar syrup and set.'),
r('lapsi',N('Lapsi','લાપસી','लापसी','Lapsi'),'dessert',['jain','swaminarayan','veg'],[{name:'Broken wheat',qty:300,unit:'g'},{name:'Ghee',qty:100,unit:'g'},{name:'Jaggery',qty:260,unit:'g'}], 'Roast broken wheat in ghee, cook tender, then sweeten with jaggery.'),
r('ghughra',N('Ghughra','ઘૂઘરા','गुजिया / घुघरा','Ghughra'),'dessert',['jain','swaminarayan','veg'],[{name:'All purpose flour',qty:300,unit:'g'},{name:'Ghee',qty:70,unit:'g'},{name:'Desiccated coconut',qty:180,unit:'g'},{name:'Sugar',qty:160,unit:'g'}], 'Prepare pastry, fill with sweet coconut mixture, seal crescents and fry.'),
r('churma-ladoo',N('Churma Ladoo','ચુરમાના લાડુ','चूरमा लड्डू','Ladoo de churma'),'dessert',['jain','swaminarayan','veg'],[{name:'Whole wheat flour',qty:400,unit:'g'},{name:'Ghee',qty:220,unit:'g'},{name:'Jaggery',qty:260,unit:'g'}], 'Cook wheat muthias, crumble finely, mix with ghee and jaggery, then shape ladoos.'),
r('chaas',N('Chaas','છાશ','छाछ','Lassi salé / babeurre'),'drink',['jain','swaminarayan','veg'],[{name:'Yogurt',qty:300,unit:'g'},{name:'Water',qty:900,unit:'ml'},{name:'Salt',qty:4,unit:'g'}], 'Blend yogurt with chilled water and salt until frothy.'),
r('masala-chaas',N('Masala Chaas','મસાલા છાશ','मसाला छाछ','Babeurre masala'),'drink',['swaminarayan','veg'],[{name:'Yogurt',qty:300,unit:'g'},{name:'Water',qty:900,unit:'ml'},{name:'Cumin',qty:4,unit:'g'},{name:'Coriander',qty:15,unit:'g'}], 'Blend yogurt and water with roasted cumin, herbs and seasoning.'),
r('cake',N('Vanilla Cake','વનિલા કેક','वैनिला केक','Gâteau à la vanille'),'dessert',['veg'],[{name:'All purpose flour',qty:500,unit:'g'},{name:'Sugar',qty:350,unit:'g'},{name:'Milk',qty:450,unit:'ml'},{name:'Butter',qty:220,unit:'g'},{name:'Baking powder',qty:15,unit:'g'}], 'Mix dry and wet ingredients separately, combine gently and bake until a tester comes out clean.'),
r('chicken-curry',N('Chicken Curry','ચિકન કરી','चिकन करी','Curry de poulet'),'proper',['nonveg'],[{name:'Chicken',qty:900,unit:'g'},{name:'Tomato',qty:250,unit:'g'},{name:'Onion',qty:220,unit:'g'},{name:'Oil',qty:35,unit:'ml'}], 'Brown aromatics and spices, add chicken and tomato, then simmer until fully cooked.'),
r('egg-curry',N('Egg Curry','ઇંડા કરી','अंडा करी','Curry aux œufs'),'proper',['nonveg'],[{name:'Eggs',qty:8,unit:'pcs'},{name:'Tomato',qty:300,unit:'g'},{name:'Onion',qty:200,unit:'g'},{name:'Oil',qty:30,unit:'ml'}], 'Boil eggs, prepare a spiced tomato-onion gravy and simmer the eggs in it.')
];

export const recipes:Recipe[]=baseRecipes.map(recipe=>({ ...recipe, steps:detailedRecipeSteps[recipe.id]||recipe.steps }));

export const ingredientNames:Record<AppLanguage,Record<string,string>>={
 en:{}, gu:{'Whole wheat flour':'ઘઉંનો લોટ','All purpose flour':'મેંદો','Rice':'ચોખા','Moong dal':'મગની દાળ','Tuvar dal':'તુવેર દાળ','Chana dal':'ચણાની દાળ','Besan':'ચણાનો લોટ','Yogurt':'દહીં','Milk':'દૂધ','Whole milk':'ફુલ ફેટ દૂધ','Potato':'બટાકા','Tomato':'ટમેટા','Eggplant':'રીંગણ','Oil':'તેલ','Ghee':'ઘી','Sugar':'ખાંડ','Jaggery':'ગોળ','Water':'પાણી','Sev':'સેવ','Fresh methi':'તાજી મેથી'},
 hi:{'Whole wheat flour':'गेहूं का आटा','All purpose flour':'मैदा','Rice':'चावल','Moong dal':'मूंग दाल','Tuvar dal':'तुअर दाल','Chana dal':'चना दाल','Besan':'बेसन','Yogurt':'दही','Milk':'दूध','Whole milk':'फुल क्रीम दूध','Potato':'आलू','Tomato':'टमाटर','Eggplant':'बैंगन','Oil':'तेल','Ghee':'घी','Sugar':'चीनी','Jaggery':'गुड़','Water':'पानी','Sev':'सेव','Fresh methi':'ताज़ी मेथी'},
 fr:{'Whole wheat flour':'farine de blé complet','All purpose flour':'farine tout usage','Rice':'riz','Moong dal':'moong dal','Tuvar dal':'toor dal','Chana dal':'chana dal','Besan':'farine de pois chiches','Yogurt':'yaourt','Milk':'lait','Whole milk':'lait entier','Potato':'pomme de terre','Tomato':'tomate','Eggplant':'aubergine','Oil':'huile','Ghee':'ghee','Sugar':'sucre','Jaggery':'jaggery','Water':'eau','Sev':'sev','Fresh methi':'fenugrec frais'}
};
